"use strict";
/**
 * EvidenceForge MONOLITH v1.0.8 — test/test-stream.js : STREAMING TRANSPORT / 524 RESILIENCE / LIVE OBSERVABILITY (T-STREAM-01…).
 * Charge par test/test-monolith.js (memes helpers). Aucun reseau externe, aucun fournisseur : Worker FACTICE local (tools/fake-worker.js,
 * contrat du proxy v0.7 : relais SSE evenement par evenement) sur 127.0.0.1 — le transport reel (fetch natif, ReadableStream) est exerce.
 * Aucun nom de cas, aucune constante de mission. Aucun secret reel : cle factice « FAKE-WORKER-KEY-not-a-secret ».
 */
const fs = require("fs"), path = require("path"), crypto = require("crypto");
module.exports = async function (h) {
  const { T, assert, assertThrows, tmp, sha, setEnv, K_KEY, K_URL, P, RS, PL, ROOT, createLlm, patchSP, patchSeal, fakeProCheckpoint, fakeDownCheckpoint, seedRunAtProfessionals } = h;
  const LS = require("../lib/llm-stream.js"); const LIVE = require("../lib/live-status.js"); const EP = require("../lib/economic-panel.js"); const CL = require("../lib/cost-ledger.js"); const BG = require("../lib/budget-guard.js"); const CV = require("../lib/cost-view.js"); const RSTOP = require("../lib/run-stop.js");
  const { startFakeWorker } = require("../tools/fake-worker.js");
  console.log("\n— v1.0.8 : STREAMING TRANSPORT (SSE), 524 RESILIENCE, LIVE OBSERVABILITY —");
  const LONG = "Réponse complète du jumeau documentaire — §" + "analyse détaillée, citation littérale « … », réserve, exigence ; ".repeat(12);
  const fw = await startFakeWorker({ reply: (prompt) => LONG + " [" + sha(prompt).slice(0, 8) + "]" });
  const savedEnv = { key: process.env[K_KEY], url: process.env[K_URL], spacing: process.env.EVIDENCEFORGE_LLM_MIN_SPACING_MS, stream: process.env.EVIDENCEFORGE_LLM_STREAM, trace: process.env.EVIDENCEFORGE_TRACE_REVIEWS, timeout: process.env.EVIDENCEFORGE_LLM_TIMEOUT_MS };
  setEnv(K_KEY, fw.key); setEnv(K_URL, fw.url); process.env.EVIDENCEFORGE_LLM_MIN_SPACING_MS = "0"; delete process.env.EVIDENCEFORGE_LLM_STREAM; delete process.env.EVIDENCEFORGE_TRACE_REVIEWS;
  const mk = (d, extra) => createLlm(Object.assign({ runDir: d, runId: "t-" + path.basename(d), storePath: path.join(d, "store.jsonl") }, extra || {}));
  const calls = (d) => fs.existsSync(path.join(d, "llm-calls.jsonl")) ? fs.readFileSync(path.join(d, "llm-calls.jsonl"), "utf8").trim().split("\n").filter(Boolean).map(JSON.parse).filter((c) => c.kind === "LLM_CALL") : [];   /* hors TRANSPORT_FAILURE_LATCHED / LLM_REUSE_REFUSED */
  const storeEntries = (d) => fs.existsSync(path.join(d, "store.jsonl")) ? fs.readFileSync(path.join(d, "store.jsonl"), "utf8").trim().split("\n").filter(Boolean).map(JSON.parse) : [];
  const cacheFiles = (d) => fs.existsSync(path.join(d, "llm-cache")) ? fs.readdirSync(path.join(d, "llm-cache")) : [];
  const dirText = (d) => { const out = []; (function walk(p) { fs.readdirSync(p).forEach((f) => { const q = path.join(p, f); if (fs.statSync(q).isDirectory()) walk(q); else out.push(fs.readFileSync(q, "utf8")); }); })(d); return out.join("\n"); };
  const META = { purpose: "EF-03B review", twinId: "twin-01", targetId: "target-01", pass: 1 };
  const withMode = async (mode, fn) => { fw.setStreamMode(mode); try { return await fn(); } finally { fw.setStreamMode("full"); fw.abortOpen(); } };

  try {
  await T("T-STREAM-01", "FANOUT PROOF : 9 documents => 1 cible (MISSION_DOSSIER) ; 19 jumeaux => 19 revues logiques attendues ; jamais 171 / 288 / 480 ; 19 revues x 1 cible => reviewDocuments 19", () => {
    const docs = Array.from({ length: 9 }, (_, i) => ({ documentId: "doc-" + (i + 1), title: "Document " + (i + 1) + ".txt", content: ("Contenu du document " + (i + 1) + ". ").repeat(400), hashSha256: sha("doc" + i) }));
    const rt = EP.buildReviewTargets({ documents: docs, mode: "MISSION_DOSSIER" }); assert(rt.mode === "MISSION_DOSSIER" && rt.targets.length === 1 && rt.sourceDocumentCount === 9 && rt.reviewsPerTwin === 1, JSON.stringify([rt.mode, rt.targets.length]));
    const pj = EP.projectDownstream({ approved: 19, targets: rt.targets.length, dimensions: 8, spentUsd: 5, perReviewUsd: [0.5, 0.5, 0.5], perCoverageUsd: [0.1, 0.1, 0.1] }); assert(pj.EXPECTED_TWINS === 19 && pj.EXPECTED_REVIEWS === 19 && [171, 288, 480].indexOf(pj.EXPECTED_REVIEWS) === -1, JSON.stringify([pj.EXPECTED_TWINS, pj.EXPECTED_REVIEWS]));
    const reviews = Array.from({ length: 19 }, (_, t) => ({ twinId: "twin-" + (t + 1), targetId: "target-01", reviewStatus: "complete", findings: Array.from({ length: 9 }, (_, i) => ({ findingId: "f-" + t + "-" + i, dimensionId: "d" + i, disposition: "support" })) }));
    const u = EP.countReviewUnits({ reviews, summary: { reviewsExpected: 19 } }); assert(u.reviewDocuments === 19 && u.reviewDocumentsComplete === 19 && u.targets === 1 && u.reviewItems === 171, "19 revues completes (171 = items de grille, jamais des revues) : " + JSON.stringify(u)); });

  await T("T-STREAM-02", "requete : `stream: true` + Accept text/event-stream ; meme modele, meme max_tokens, meme prompt qu'en non-streaming (le streaming ne change que le transport) ; EVIDENCEFORGE_LLM_STREAM=0 => corps sans `stream`, transport JSON ; preflight jamais en streaming", async () => {
    const d = tmp(); const n0 = fw.requests.length; const llm = mk(d); const r = await llm.llmCall("prompt de revue A", META); assert(r.text.startsWith(LONG) && r.reused === false && llm.streaming.enabled === true, "reponse streamee");
    const q = fw.requests[n0]; assert(q.stream === true && /text\/event-stream/.test(q.accept) && q.max_tokens === 8192 && q.model === llm.model, JSON.stringify(q));
    process.env.EVIDENCEFORGE_LLM_STREAM = "0"; try { const d2 = tmp(); const llm2 = mk(d2); const r2 = await llm2.llmCall("prompt de revue A", META); const q2 = fw.requests[n0 + 1]; assert(q2.stream === false && q2.max_tokens === q.max_tokens && q2.model === q.model && q2.promptChars === q.promptChars && r2.text === r.text, "meme requete hors streaming"); assert(calls(d2)[0].transport === "JSON" && llm2.streaming.enabled === false, "transport JSON"); } finally { delete process.env.EVIDENCEFORGE_LLM_STREAM; }
    const pf = await llm.preflight(); assert(pf.ok === true && fw.requests[fw.requests.length - 1].stream === false, "preflight non streaming"); assert(calls(d)[0].transport === "SSE_STREAM" && calls(d)[0].stream.canonical === true && calls(d)[0].stream.events > 5, JSON.stringify(calls(d)[0].stream)); });

  await T("T-STREAM-03", "reconstruction canonique deterministe : evenements SSE decoupes a des frontieres d'octets arbitraires (UTF-8 multi-octets, CRLF, ping, commentaires, data multi-lignes, evenement inconnu) => corps identique au corps non streaming (id, model, content, stop_reason, usage fusionne) ; meme hash a chaque rejeu", async () => {
    const text = "Texte avec accents é, flèche → et émoji 🧪 ; « citation littérale »."; const evs = [{ type: "message_start", message: { id: "msg_c1", type: "message", role: "assistant", model: "m-test", content: [], usage: { input_tokens: 1234, output_tokens: 1, cache_creation_input_tokens: 0, cache_read_input_tokens: 0 } } }, { type: "content_block_start", index: 0, content_block: { type: "text", text: "" } }]
      .concat((text.match(/[\s\S]{1,5}/g)).map((t) => ({ type: "content_block_delta", index: 0, delta: { type: "text_delta", text: t } }))).concat([{ type: "ping" }, { type: "future_event", x: 1 }, { type: "content_block_stop", index: 0 }, { type: "message_delta", delta: { stop_reason: "end_turn", stop_sequence: null }, usage: { output_tokens: 57 } }, { type: "message_stop" }]);
    const sseTxt = ": comment\r\n\r\n" + evs.map((e) => "event: " + e.type + "\r\ndata: " + JSON.stringify(e) + "\r\n\r\n").join("") + "event: message_stop\ndata: {\"type\":\"ping\"}\ndata: \n\n";
    const buf = Buffer.from(sseTxt, "utf8"); const chunksOf = (n) => { const out = []; for (let i = 0; i < buf.length; i += n) out.push(buf.subarray(i, i + n)); return out; };
    const mkRes = (chunks) => ({ body: new ReadableStream({ start(c) { chunks.forEach((x) => c.enqueue(new Uint8Array(x))); c.close(); } }) });
    const expected = { id: "msg_c1", type: "message", role: "assistant", model: "m-test", content: [{ type: "text", text }], stop_reason: "end_turn", stop_sequence: null, usage: { input_tokens: 1234, output_tokens: 57, cache_creation_input_tokens: 0, cache_read_input_tokens: 0 } };
    const hashes = []; for (const n of [1, 3, 7, 64, 100000]) { const r = await LS.readSseResponse(mkRes(chunksOf(n)), { inactivityMs: 1000, maxTotalMs: 5000 }); assert(JSON.stringify(r.canonical) === JSON.stringify(expected), "chunk=" + n + " : " + JSON.stringify(r.canonical)); assert(Object.keys(r.canonical).join(",") === LS.CANONICAL_KEYS.join(","), "ordre des cles"); hashes.push(r.stats.rawSha256); }
    assert(new Set(hashes).size === 1 && hashes[0] === sha(JSON.stringify(expected)), "hash identique a chaque rejeu"); const b = LS.assembleFromSseText(sseTxt); assert(b.complete === true && b.raw === JSON.stringify(expected), "reconstruction depuis texte bufferise identique"); });

  await T("T-STREAM-04", "usage / model / id / stop_reason conserves ; journal llm-calls (transport SSE_STREAM, evenements, octets, duree) ; cache request/response ecrit avec le corps canonique ; cout du ledger identique a celui du meme usage en transport JSON", async () => {
    const d = tmp(); const ledger = CL.createCostLedger({ runDir: d, runId: "t4" }); ledger.setStage("TWINS_REVIEWS"); const llm = mk(d, { ledger }); const r = await llm.llmCall("prompt de revue B", META);
    const c = calls(d)[0]; assert(c.kind === "LLM_CALL" && c.transport === "SSE_STREAM" && c.httpStatus === 200 && c.providerRequestId && /^msg_/.test(c.providerRequestId) && c.stopReason === "end_turn" && c.modelId === llm.model && c.usage.input_tokens > 0 && c.usage.output_tokens > 0 && c.stream.events > 5 && c.stream.bytes > 100 && typeof c.stream.elapsedMs === "number", JSON.stringify(c));
    assert(r.usage.input_tokens === c.usage.input_tokens && r.providerRequestId === c.providerRequestId && r.callId === c.responseSha256, "retour coherent"); const cf = cacheFiles(d); assert(cf.indexOf(c.promptSha256 + ".request.json") !== -1 && cf.indexOf(c.responseSha256 + ".response.json") !== -1, "cache");
    const body = fs.readFileSync(path.join(d, "llm-cache", c.responseSha256 + ".response.json"), "utf8"); assert(sha(body) === c.responseSha256 && Object.keys(JSON.parse(body)).join(",") === LS.CANONICAL_KEYS.join(",") && JSON.parse(body).content[0].text === r.text, "corps canonique en cache");
    const t1 = ledger.totals(); const e1 = CL.readEntries(d).filter((x) => x.kind === "REAL_CALL"); assert(e1.length === 1 && e1[0].usage.input === c.usage.input_tokens && e1[0].usage.output === c.usage.output_tokens && e1[0].twinId === "twin-01" && e1[0].targetId === "target-01" && e1[0].interrupted === false && t1.totalUsd > 0, JSON.stringify(e1[0]));
    process.env.EVIDENCEFORGE_LLM_STREAM = "0"; try { const d2 = tmp(); const l2 = CL.createCostLedger({ runDir: d2, runId: "t4b" }); l2.setStage("TWINS_REVIEWS"); const llm2 = mk(d2, { ledger: l2 }); await llm2.llmCall("prompt de revue B", META); assert(calls(d2)[0].usage.input_tokens === c.usage.input_tokens && calls(d2)[0].usage.output_tokens === c.usage.output_tokens && l2.totals().totalUsd === t1.totalUsd, "meme cout en JSON : " + l2.totals().totalUsd + " vs " + t1.totalUsd); } finally { delete process.env.EVIDENCEFORGE_LLM_STREAM; } });

  await T("T-STREAM-05", "validation et reuse inchanges : texte identique passe a la validation ; avant VALID => nouvel appel reel ; apres VALID => REUSE (cout 0, jamais compte reel) ; entree du magasin complete (promptSha256, responseSha256, providerRequestId, VALID, providerId, modelId, sourceSealHash, MONO-11-v2)", async () => {
    const d = tmp(); const ledger = CL.createCostLedger({ runDir: d, runId: "t5" }); ledger.setStage("TWINS_REVIEWS"); const seal = "a".repeat(64); const llm = mk(d, { ledger, sealHash: seal }); const n0 = fw.calls();
    const r1 = await llm.llmCall("prompt de revue C", META); const r2 = await llm.llmCall("prompt de revue C", META); assert(r2.reused === false && fw.calls() === n0 + 2, "avant VALID : appel reel");
    llm.onValidation({ callId: r2.callId, valid: true, errors: [], stage: "EF-03B" }); const r3 = await llm.llmCall("prompt de revue C", META); assert(r3.reused === true && r3.text === r2.text && r3.transportKind === "REUSE_OF_VALID_REAL_RESPONSE" && fw.calls() === n0 + 2 && llm.counts().real === 2 && llm.counts().reused === 1, "apres VALID : reuse");
    const en = storeEntries(d).filter((e) => e.responseSha256 === r2.callId).pop(); assert(en && en.promptSha256 === sha("prompt de revue C") && en.providerRequestId === r2.providerRequestId && en.validationStatus === "VALID" && en.providerId === "anthropic" && en.modelId === llm.model && en.sourceSealHash === seal && en.validationContract === "MONO-11-v2", JSON.stringify(en));
    const reuse = CL.readEntries(d).filter((x) => x.kind === "REUSE"); assert(reuse.length === 1 && reuse[0].cost.totalUsd === 0 && reuse[0].callId === r2.callId, JSON.stringify(reuse)); assert(r1.reused === false && r1.callId !== r2.callId, "deux appels reels distincts (identifiants distincts)"); });

  await T("T-STREAM-06", "flux interrompu en pleine generation => PROVIDER_STREAM_INTERRUPTED (fatal, reprenable) ; aucune reponse, aucun cache, aucune entree de magasin, aucun texte partiel nulle part ; journal precis (twinId, targetId, localRequestId, providerRequestId, evenements, octets, duree, cause) ; verrou : appel suivant sans reseau", () => withMode("cut", async () => {
    const d = tmp(); const llm = mk(d); const n0 = fw.calls(); const e = await assertThrows(() => llm.llmCall("prompt de revue D", META), LS.CODE_INTERRUPTED);
    assert(e.fatal === true && e.stream && e.stream.started === true && e.stream.events >= 3 && e.stream.bytes > 0 && /^msg_/.test(e.stream.providerRequestId) && /interrompue/.test(e.userMessage), JSON.stringify(e.stream));
    const c = calls(d); assert(c.length === 1 && c[0].outcome === "STREAM_INTERRUPTED" && c[0].code === LS.CODE_INTERRUPTED && c[0].responseSha256 === null && c[0].twinId === "twin-01" && c[0].targetId === "target-01" && /^efm-/.test(c[0].localRequestId) && c[0].providerRequestId === e.stream.providerRequestId && c[0].stream.completed === false && c[0].stream.events === e.stream.events && c[0].stream.cause && c[0].stream.elapsedMs >= 0, JSON.stringify(c[0]));
    assert(cacheFiles(d).length === 0 && storeEntries(d).length === 0, "aucun cache, aucune entree de magasin"); const partial = LONG.slice(0, 12); assert(dirText(d).indexOf(partial) === -1 && JSON.stringify(c[0]).indexOf("Réponse") === -1, "aucun texte partiel persiste");
    assert(llm.transportFailure() && llm.transportFailure().code === LS.CODE_INTERRUPTED && PL.RESUMABLE.indexOf(LS.CODE_INTERRUPTED) !== -1, "verrou + reprenable"); const e2 = await assertThrows(() => llm.llmCall("prompt de revue E", META), LS.CODE_INTERRUPTED); assert(e2.latched === true && fw.calls() === n0 + 1, "aucun nouvel appel reseau"); }));

  await T("T-STREAM-07", "cout d'un flux interrompu : usage fournisseur connu (message_start recu) => REAL_CALL `interrupted`, `usageIncomplete`, cout sur l'usage connu seulement ; coupure avant message_start => aucune entree de cout (jamais un cout invente), usage null au journal", async () => {
    await withMode("cut", async () => { const d = tmp(); const ledger = CL.createCostLedger({ runDir: d, runId: "t7a" }); ledger.setStage("TWINS_REVIEWS"); const llm = mk(d, { ledger }); await assertThrows(() => llm.llmCall("prompt de revue F", META), LS.CODE_INTERRUPTED);
      const en = CL.readEntries(d).filter((x) => x.kind === "REAL_CALL"); assert(en.length === 1 && en[0].interrupted === true && en[0].usageIncomplete === true && en[0].usage.input > 0 && en[0].usage.output === 1 && en[0].cost.totalUsd > 0 && en[0].twinId === "twin-01", JSON.stringify(en[0])); assert(ledger.totals().totalUsd === en[0].cost.totalUsd, "total = cout connu"); });
    await withMode("cut0", async () => { const d = tmp(); const ledger = CL.createCostLedger({ runDir: d, runId: "t7b" }); ledger.setStage("TWINS_REVIEWS"); const llm = mk(d, { ledger }); const e = await assertThrows(() => llm.llmCall("prompt de revue G", META), LS.CODE_INTERRUPTED);
      assert(e.stream.started === false && CL.readEntries(d).filter((x) => x.kind === "REAL_CALL").length === 0 && ledger.totals().totalUsd === 0, "aucun cout invente"); const c = calls(d)[0]; assert(c.usage === null && c.providerRequestId === null && c.stream.started === false, JSON.stringify(c)); }); });

  await T("T-STREAM-08", "aucun retry automatique apres une interruption de flux (une generation deja lancee serait re-facturee) : exactement 1 requete ; aucune boucle infinie ; la reprise est un acte explicite (nouveau run/tentative)", () => withMode("cut", async () => {
    const d = tmp(); const llm = mk(d, { maxAttemptsOnCapacity: 8 }); const n0 = fw.calls(); await assertThrows(() => llm.llmCall("prompt de revue H", META), LS.CODE_INTERRUPTED); assert(fw.calls() === n0 + 1 && calls(d).length === 1 && calls(d)[0].outcome === "STREAM_INTERRUPTED", "1 requete, 1 journal");
    const src = fs.readFileSync(path.join(ROOT, "lib", "llm.js"), "utf8"); assert(/aucun retry automatique/.test(src) && !/CODE_INTERRUPTED[^\n]*continue;/.test(src), "source : pas de retry sur interruption"); }));

  await T("T-STREAM-09", "chiens de garde bornes : flux qui se tait (message_start puis silence) => interruption STREAM_INACTIVITY ; flux lent mais actif au-dela de la duree totale => STREAM_MAX_DURATION ; flux lent mais actif sous les bornes => succes", async () => {
    await withMode("stall", async () => { const d = tmp(); const llm = mk(d, { streaming: { inactivityMs: 150, maxTotalMs: 5000 } }); const t0 = Date.now(); const e = await assertThrows(() => llm.llmCall("prompt de revue I", META), LS.CODE_INTERRUPTED); assert(e.normalizedCause === "STREAM_INACTIVITY" && Date.now() - t0 < 2000 && e.stream.started === true, e.normalizedCause + " " + (Date.now() - t0)); assert(calls(d)[0].stream.cause === "STREAM_INACTIVITY", "cause journalisee"); });
    await withMode("slow", async () => { const d = tmp(); const llm = mk(d, { streaming: { inactivityMs: 5000, maxTotalMs: 300 } }); const e = await assertThrows(() => llm.llmCall("prompt de revue J", META), LS.CODE_INTERRUPTED); assert(e.normalizedCause === "STREAM_MAX_DURATION" && e.stream.events >= 2, e.normalizedCause); });
    await withMode("slow", async () => { const d = tmp(); const llm = mk(d, { streaming: { inactivityMs: 2000, maxTotalMs: 60000 } }); const r = await llm.llmCall("prompt de revue K", META); assert(r.text.startsWith(LONG) && calls(d)[0].transport === "SSE_STREAM" && calls(d)[0].stream.elapsedMs >= 500, "lent mais complet"); }); });

  await T("T-STREAM-10", "delai local du PREMIER octet (aucun en-tete recu) => PROVIDER_TIMEOUT (reprenable), jamais un faux succes ; en streaming le delai de 180 s ne couvre plus la generation", () => withMode("hang", async () => {
    process.env.EVIDENCEFORGE_LLM_TIMEOUT_MS = "150"; try { const d = tmp(); const llm = mk(d); const t0 = Date.now(); const e = await assertThrows(() => llm.llmCall("prompt de revue L", META), "PROVIDER_TIMEOUT"); assert(Date.now() - t0 < 2000 && /délai/.test(e.userMessage) && llm.streaming.firstByteTimeoutMs === 150 && PL.RESUMABLE.indexOf("PROVIDER_TIMEOUT") !== -1, "premier octet"); } finally { delete process.env.EVIDENCEFORGE_LLM_TIMEOUT_MS; } }));

  await T("T-STREAM-11", "HTTP 524 (edge) => PROVIDER_UNAVAILABLE journalise httpStatus 524, verrou, reprenable, aucun cache reutilisable ; 500 / 502 => PROVIDER_UNAVAILABLE ; 503 => PROVIDER_CAPACITY ; 429 puis 200 => attente bornee puis flux complet (providerAttempts 2)", async () => {
    for (const st of [524, 500, 502]) { const d = tmp(); fw.setStatusOnce(st); const llm = mk(d); const e = await assertThrows(() => llm.llmCall("prompt de revue M" + st, META), "PROVIDER_UNAVAILABLE"); assert(e.httpStatus === st && e.fatal === true && calls(d)[0].httpStatus === st && calls(d)[0].transport === "JSON" && llm.transportFailure().code === "PROVIDER_UNAVAILABLE" && storeEntries(d).length === 0, "HTTP " + st); }
    { const d = tmp(); fw.setStatusOnce(503); const llm = mk(d, { maxAttemptsOnCapacity: 1 }); const e = await assertThrows(() => llm.llmCall("prompt de revue N", META), "PROVIDER_CAPACITY"); assert(e.httpStatus === 503 && PL.RESUMABLE.indexOf("PROVIDER_CAPACITY") !== -1, "503 => capacite"); }
    { const d = tmp(); fw.setStatusOnce(429); const llm = mk(d); const r = await llm.llmCall("prompt de revue O", META); assert(r.text.startsWith(LONG) && calls(d)[0].providerAttempts === 2 && calls(d)[0].capacityWaits.length === 1 && calls(d)[0].transport === "SSE_STREAM", JSON.stringify(calls(d)[0].capacityWaits)); } });

  await T("T-STREAM-12", "flux malforme / erreur fournisseur en cours de flux : evenement error overloaded => PROVIDER_CAPACITY ; error autre => PROVIDER_UNAVAILABLE ; JSON invalide => PROVIDER_BAD_RESPONSE ; fin sans message_stop => interrompu ; flux vide => interrompu ; complet sans texte => PROVIDER_EMPTY_RESPONSE — jamais une reponse, jamais un cache reutilisable", async () => {
    const cases = [["error-overloaded", "PROVIDER_CAPACITY", null], ["error-other", "PROVIDER_UNAVAILABLE", null], ["malformed", "PROVIDER_BAD_RESPONSE", null], ["nostop", LS.CODE_INTERRUPTED, "STREAM_ENDED_BEFORE_MESSAGE_STOP"], ["empty", LS.CODE_INTERRUPTED, "STREAM_ENDED_WITHOUT_MESSAGE_START"], ["emptytext", "PROVIDER_EMPTY_RESPONSE", null]];
    for (const [mode, code, cause] of cases) await withMode(mode, async () => { const d = tmp(); const llm = mk(d); const e = await assertThrows(() => llm.llmCall("prompt de revue P " + mode, META), code); if (cause) assert(e.normalizedCause === cause, mode + " cause " + e.normalizedCause); assert(storeEntries(d).length === 0 && llm.transportFailure() && llm.transportFailure().code === code, mode + " : aucune entree de magasin, verrou " + code); assert(mode === "emptytext" ? cacheFiles(d).length === 2 : cacheFiles(d).length === 0, mode + " : cache"); }); });

  await T("T-STREAM-13", "compatibilite ancien proxy (v0.6 bufferise le SSE en application/json) : reponse reconstruite (transport SSE_BUFFERED_BY_PROXY) ; SSE bufferise incomplet => interrompu (BUFFERED_SSE_INCOMPLETE), rien de partiel", async () => {
    await withMode("buffered", async () => { const d = tmp(); const llm = mk(d); const r = await llm.llmCall("prompt de revue Q", META); assert(r.text.startsWith(LONG) && calls(d)[0].transport === "SSE_BUFFERED_BY_PROXY" && r.usage.output_tokens > 0, JSON.stringify(calls(d)[0].transport)); });
    await withMode("buffered-incomplete", async () => { const d = tmp(); const llm = mk(d); const e = await assertThrows(() => llm.llmCall("prompt de revue R", META), LS.CODE_INTERRUPTED); assert(e.normalizedCause === "BUFFERED_SSE_INCOMPLETE" && cacheFiles(d).length === 0 && storeEntries(d).length === 0, e.normalizedCause); }); });

  await T("T-STREAM-14", "arret utilisateur PENDANT un flux => STOPPED_BY_USER (userStop), flux annule, rien de partiel, journal STREAM_STOPPED_BY_USER, verrou : aucun appel suivant ; arret demande AVANT l'appel => aucune requete", async () => {
    await withMode("slow", async () => { const d = tmp(); let stop = false; const llm = mk(d, { stopCheck: () => (stop ? { requestedAt: new Date().toISOString() } : null), onStream: (e) => { if (e.kind === "STREAM_PROGRESS" && e.events >= 3) stop = true; }, streaming: { progressEveryMs: 0 } }); const n0 = fw.calls();
      const e = await assertThrows(() => llm.llmCall("prompt de revue S", META), "STOPPED_BY_USER"); assert(e.userStop === true && e.stream && e.stream.started === true && /arrêté à votre demande/.test(e.userMessage), JSON.stringify(e.stream)); const c = calls(d); assert(c.length === 1 && c[0].outcome === "STREAM_STOPPED_BY_USER" && c[0].code === "STOPPED_BY_USER" && c[0].responseSha256 === null && cacheFiles(d).length === 0, JSON.stringify(c[0]));
      const e2 = await assertThrows(() => llm.llmCall("prompt de revue T", META), "STOPPED_BY_USER"); assert(e2.latched === true && fw.calls() === n0 + 1, "verrou"); });
    { const d = tmp(); const llm = mk(d, { stopCheck: () => ({ requestedAt: new Date().toISOString() }) }); const n0 = fw.calls(); await assertThrows(() => llm.llmCall("prompt de revue U", META), "STOPPED_BY_USER"); assert(fw.calls() === n0 && calls(d).length === 0, "aucune requete"); } });

  await T("T-STREAM-15", "budget LIMITED atteint => BUDGET_LIMIT_REACHED AVANT la requete (aucune requete streamee lancee), verrou, reprenable ; le budget reste une autorite de transport (jamais scientifique)", async () => {
    const d = tmp(); const ledger = CL.createCostLedger({ runDir: d, runId: "t15" }); ledger.setStage("TWINS_REVIEWS"); const budget = BG.createBudgetGuard({ runDir: d, runId: "t15", ledger }); budget.set({ costBudgetUsd: 0.01, warningThresholdUsd: null }, "user", { mode: "LIMITED" }); ledger.attachBudget(budget);
    ledger.record({ kind: "REAL_CALL", model: "claude-sonnet-4-6", purpose: "EF-03B review", usage: { input_tokens: 100000, output_tokens: 1000 } }); const llm = mk(d, { ledger, budget }); const n0 = fw.calls(); const e = await assertThrows(() => llm.llmCall("prompt de revue V", META), "BUDGET_LIMIT_REACHED");
    assert(fw.calls() === n0 && e.fatal === true && llm.transportFailure().code === "BUDGET_LIMIT_REACHED" && PL.RESUMABLE.indexOf("BUDGET_LIMIT_REACHED") !== -1 && /budget maximum/.test(e.userMessage), "aucune requete"); });

  await T("T-STREAM-16", "coupure reseau : URL injoignable => code de transport classe (connexion refusee), verrou, reprenable ; annulation du lecteur en cours de flux (AbortController / socket detruit) => interruption avec cause STREAM_READ_ERROR ou fin prematuree, jamais une reponse", async () => {
    { const d = tmp(); setEnv(K_URL, "http://127.0.0.1:1"); try { const llm = mk(d); const e = await assertThrows(() => llm.llmCall("prompt de revue W", META)); assert(["PROVIDER_CONNECTION_REFUSED", "NETWORK_UNAVAILABLE"].indexOf(e.code) !== -1 && llm.TRANSPORT_CODES.indexOf(e.code) !== -1 && PL.RESUMABLE.indexOf(e.code) !== -1, e.code); } finally { setEnv(K_URL, fw.url); } }
    { const ac = new AbortController(); const res = { body: new ReadableStream({ start(c) { c.enqueue(new TextEncoder().encode("event: message_start\ndata: " + JSON.stringify({ type: "message_start", message: { id: "msg_x", model: "m", usage: { input_tokens: 5, output_tokens: 1 } } }) + "\n\n")); setTimeout(() => c.error(Object.assign(new Error("aborted"), { name: "AbortError" })), 30); } }) };
      const e = await assertThrows(() => LS.readSseResponse(res, { inactivityMs: 5000, maxTotalMs: 5000 }), LS.CODE_INTERRUPTED); assert(/STREAM_READ_ERROR/.test(e.normalizedCause) && e.stream.started === true && e.stream.providerRequestId === "msg_x", e.normalizedCause); ac.abort(); }
    await withMode("cut", async () => { const d = tmp(); const llm = mk(d); const e = await assertThrows(() => llm.llmCall("prompt de revue X", META), LS.CODE_INTERRUPTED); assert(/STREAM_READ_ERROR|STREAM_ENDED_BEFORE_MESSAGE_STOP/.test(e.normalizedCause), e.normalizedCause); }); });

  await T("T-STREAM-17", "observabilite live : live-status.json (tous les champs du mandat), providerCallState IDLE/STARTED/STREAMING/COMPLETED/FAILED, heartbeat borne (updatedAt bouge pendant le flux, jamais par jeton), compteurs llmReal/llmReused coherents, revues logiques attendues = jumeaux x cibles, completes seulement apres VALID ; state.live expose par publicState ; vue de cout `live`", async () => {
    const store = RS.createRunStore(RS.newRunId()); const state = { runId: store.runId, status: "RUNNING", stage: "TWINS_REVIEWS", attempts: 2, counters: { llmReal: 3, llmReused: 1 }, createdAt: new Date().toISOString() }; store.write(state); const d = store.dir; const ledger = CL.createCostLedger({ runDir: d, runId: store.runId }); ledger.setStage("TWINS_REVIEWS");
    const llm = mk(d, { ledger }); const live = LIVE.createLiveStatus({ store, state, llm, baseCounters: { real: 3, reused: 1 }, heartbeatMs: 1000, minWriteMs: 200 });
    try { live.note({ reviewTargetMode: "MISSION_DOSSIER", targetsTotal: 1, targetId: "target-01" }); live.onTrace({ event: "twins_built", built: 19 }); let s = LIVE.readLiveStatus(d); assert(s.schema === "EvidenceForge.LiveStatus" && s.twinsTotal === 19 && s.logicalReviewsExpected === 19 && s.logicalReviewsComplete === 0 && s.providerCallState === "IDLE" && s.reviewTargetMode === "MISSION_DOSSIER", JSON.stringify(s));
      const MANDATED = ["currentTwinIndex", "currentTwinId", "twinsTotal", "currentTargetIndex", "targetId", "reviewTargetMode", "logicalReviewsExpected", "logicalReviewsComplete", "providerCallState", "providerCallStartedAt", "lastProviderActivityAt", "streamEventsReceived", "streamBytesReceived", "elapsedMs", "llmReal", "llmReused", "lastCheckpointAt", "lastValidatedReviewAt", "totalUsd", "currentStageUsd", "lastTransportCode", "updatedAt"]; MANDATED.forEach((k) => assert(k in s, "champ " + k));
      live.onStream({ kind: "STREAM_STARTED", purpose: "EF-03B review", twinId: "twin-07", targetId: "target-01", localRequestId: "efm-x" }); s = LIVE.readLiveStatus(d); assert(s.providerCallState === "STARTED" && s.currentTwinId === "twin-07" && s.currentTwinIndex === 1 && s.currentTargetIndex === 1 && s.providerCallStartedAt && s.providerCallPurpose === "EF-03B review", JSON.stringify(s));
      const u0 = s.updatedAt; const st0 = store.read().updatedAt; live.onStream({ kind: "STREAM_PROGRESS", twinId: "twin-07", events: 12, bytes: 3400, lastActivityAt: new Date().toISOString(), providerRequestId: "msg_live" }); await new Promise((r) => setTimeout(r, 1300)); s = LIVE.readLiveStatus(d);
      assert(s.providerCallState === "STREAMING" && s.streamEventsReceived === 12 && s.streamBytesReceived === 3400 && s.heartbeats >= 1 && s.updatedAt > u0 && s.elapsedMs >= 500 && store.read().updatedAt > st0 && s.providerRequestId === "msg_live", "heartbeat : " + JSON.stringify([s.heartbeats, s.updatedAt, u0, s.elapsedMs]));
      const w0 = s.writes; for (let i = 0; i < 50; i++) live.onStream({ kind: "STREAM_PROGRESS", twinId: "twin-07", events: 13 + i, bytes: 3500 + i }); assert(LIVE.readLiveStatus(d).writes <= w0 + 1, "ecriture bornee (jamais par jeton)");
      live.onStream({ kind: "STREAM_COMPLETED", twinId: "twin-07", events: 70, bytes: 9000 }); live.onTrace({ event: "llm_call", outcome: "OK", purpose: "EF-03B review", providerRequestId: "msg_live" }); s = LIVE.readLiveStatus(d); assert(s.providerCallState === "COMPLETED" && s.streamEventsReceived === 70 && s.logicalReviewsComplete === 0 && s.llmReal === 3 && s.llmReused === 1, "complete sans validation");
      live.onValidation({ valid: false, stage: "EF-03B", callId: "x", errors: ["schema"] }); live.onValidation({ valid: true, stage: "EF-03B", callId: "y" }); s = LIVE.readLiveStatus(d); assert(s.logicalReviewsComplete === 1 && s.reviewsInvalidPasses === 1 && s.lastValidatedReviewAt, "1 revue logique complete apres VALID");
      live.onTrace({ event: "checkpoint_saved", checkpoint: "downstream" }); live.onTrace({ event: "llm_stream_interrupted", code: LS.CODE_INTERRUPTED, twinId: "twin-08", targetId: "target-01", streamEvents: 4, streamBytes: 500 }); s = LIVE.readLiveStatus(d); assert(s.providerCallState === "FAILED" && s.lastTransportCode === LS.CODE_INTERRUPTED && s.currentTwinId === "twin-08" && s.currentTwinIndex === 2 && s.lastCheckpointAt && s.lastTransportAt, JSON.stringify([s.providerCallState, s.lastTransportCode]));
      await llm.llmCall("prompt live", META); live.onTrace({ event: "llm_call", outcome: "OK", twinId: "twin-08" }); s = LIVE.readLiveStatus(d); assert(s.llmReal === 4 && s.totalUsd > 0 && s.currentStageUsd === s.totalUsd, "compteurs et cout : " + JSON.stringify([s.llmReal, s.totalUsd]));
      const pub = store.publicState(store.read()); assert(pub.live && pub.live.providerCallState === "COMPLETED" && pub.live.twinsTotal === 19 && pub.counters.llmReal === 4, "state.live public : " + JSON.stringify(pub.live)); const cv = fs.readFileSync(path.join(ROOT, "lib", "cost-view.js"), "utf8"); assert(/live: liveOf\(store, state\)/.test(cv) && /readLiveStatus/.test(cv), "vue de cout"); const ui = fs.readFileSync(path.join(ROOT, "index.html"), "utf8"); assert(/Appel fournisseur en cours/.test(ui) && /Revues logiques/.test(ui) && /providerCallState/.test(ui), "UI");
      assert(JSON.stringify(s).indexOf(fw.key) === -1 && JSON.stringify(s).indexOf("prompt live") === -1, "aucun secret ni prompt dans le statut live"); } finally { live.stop(); } });

  await T("T-STREAM-18", "mode trace console (EVIDENCEFORGE_TRACE_REVIEWS=1) : lignes [EF REVIEW] / [EF STREAM] / [EF REVIEW ERROR] ; JAMAIS la cle, Authorization, le prompt ni la reponse ; desactive par defaut (aucune ligne)", async () => {
    const lines = []; const orig = console.log; console.log = (l) => lines.push(String(l));
    try { const d = tmp(); await mk(d).llmCall("prompt secret de revue Y", META); assert(!lines.some((l) => /\[EF /.test(l)), "desactive par defaut : aucune ligne"); process.env.EVIDENCEFORGE_TRACE_REVIEWS = "1";
      const d2 = tmp(); await mk(d2).llmCall("prompt secret de revue Y", META); await withMode("cut", () => assertThrows(() => mk(tmp()).llmCall("prompt secret de revue Z", META), LS.CODE_INTERRUPTED)); }
    finally { console.log = orig; delete process.env.EVIDENCEFORGE_TRACE_REVIEWS; }
    const ef = lines.filter((l) => /\[EF /.test(l)); assert(ef.some((l) => /^\[EF REVIEW\] twin=twin-01 .*state=STARTED/.test(l)) && ef.some((l) => /^\[EF STREAM\] .*state=STREAM_(STARTED|PROGRESS|COMPLETED)/.test(l)) && ef.some((l) => /^\[EF REVIEW\] .*state=RECEIVED transport=SSE_STREAM/.test(l)) && ef.some((l) => /^\[EF REVIEW ERROR\] twin=twin-01 code=PROVIDER_STREAM_INTERRUPTED .*checkpoint=UNCHANGED resumable=true/.test(l)), ef.join("\n"));
    const all = lines.join("\n"); assert(all.indexOf(fw.key) === -1 && !/authorization|bearer/i.test(all) && all.indexOf("prompt secret") === -1 && all.indexOf("Réponse complète") === -1, "aucun secret, prompt ni reponse dans la trace"); });

  await T("T-STREAM-19", "aucun secret dans llm-calls.jsonl, cost-ledger, live-status, magasin ni cache apres tous les modes (succes, interruption, arret) ; la cle n'est envoyee qu'au transport (Bearer)", async () => {
    const d = tmp(); const ledger = CL.createCostLedger({ runDir: d, runId: "t19" }); const llm = mk(d, { ledger }); await llm.llmCall("prompt de revue AA", META); await withMode("cut", () => assertThrows(() => mk(d).llmCall("prompt de revue AB", META), LS.CODE_INTERRUPTED));
    const txt = dirText(d); assert(txt.indexOf(fw.key) === -1 && !/Bearer /.test(txt) && txt.indexOf(fw.url) === -1, "aucun secret ni URL de worker dans le run"); assert(/authorization: "Bearer " \+ key/.test(fs.readFileSync(path.join(ROOT, "lib", "llm.js"), "utf8")), "cle uniquement au transport"); });

  await T("T-STREAM-20", "invariants : lib/panel-sufficiency.js byte-identique (sha256 fd05e26b…) ; lots geles 0 divergence ; Worker gele MONO-08 v0.6 intact (sha256 a4f70bda…) ; proxy v0.8 additif (delais separes, HEADER_TIMEOUT_MS 60 s, lecture stricte) (relais `new Response(upstreamResponse.body`, compat bufferisee conservee, cle Anthropic jamais renvoyee, credential Worker verifie) ; config streaming/observabilite ; RESUMABLE", () => {
    assert(sha(fs.readFileSync(path.join(ROOT, "lib", "panel-sufficiency.js"))) === "fd05e26b708c4d4cdc59595838145669d05a267393629dbd922827c289bf7a3e", "panel-sufficiency inchange"); const fr = P.verifyFrozenLots(); ["MONO-01", "MONO-09", "MONO-10", "MONO-11"].forEach((k) => assert(fr[k] && fr[k].verified === true, k));
    const frozenWorker = path.join(P.MONO08_V06, "worker", "evidenceforge-llm-proxy", "src", "worker.js"); assert(sha(fs.readFileSync(frozenWorker)) === "a4f70bdac987fa712a2f0937682ded249a11f2124e0028896a8d90cc0b212fd0", "worker v0.6 gele intact");
    const w7 = fs.readFileSync(path.join(ROOT, "worker", "evidenceforge-llm-proxy-v0.8", "src", "worker.js"), "utf8"); assert(/payload\.stream === true/.test(w7) && /new Response\(upstreamResponse\.body/.test(w7) && /await upstreamResponse\.text\(\)/.test(w7) && /text\/event-stream/.test(w7) && /0\.8-stream-timeouts/.test(w7), "proxy v0.8 : relais + compat");
    { const uses = w7.split("\n").filter((l) => /anthropicKey/.test(l) && !/^\s*\*/.test(l)); assert(uses.length === 3 && uses.every((l) => /const anthropicKey = env\.ANTHROPIC_API_KEY|if \(!anthropicKey\)|"x-api-key": anthropicKey/.test(l)), "cle amont : lue, verifiee, envoyee en amont seulement — jamais dans une reponse : " + JSON.stringify(uses)); assert(/env\.WORKER_API_KEY/.test(w7) && /authorization/i.test(w7), "credential Worker conserve"); } assert(w7 !== fs.readFileSync(frozenWorker, "utf8"), "copie versionnee distincte");
    /* v1.0.9 — proxy v0.8 : delais separes, seul HEADER_TIMEOUT_MS applique (defaut 60 000, bornes 1 000–90 000), lecture stricte (jamais typeof === "number" seul), variable explicite dans wrangler.jsonc, un seul setTimeout */
    assert(/DEFAULT_HEADER_TIMEOUT_MS = 60000/.test(w7) && /HEADER_TIMEOUT_BOUNDS = \{ min: 1000, max: 90000 \}/.test(w7) && /function readTimeoutConfig/.test(w7) && /function parseBoundedMs/.test(w7) && !/typeof env\.TIMEOUT_MS === "number"/.test(w7) && (w7.match(/setTimeout\(/g) || []).length === 1 && /STREAM_INACTIVITY_TIMEOUT_MS/.test(w7) && /STREAM_MAX_DURATION_MS/.test(w7) && /phase: "upstream_headers"/.test(w7), "proxy v0.8 : delais separes");
    const wr = fs.readFileSync(path.join(ROOT, "worker", "evidenceforge-llm-proxy-v0.8", "wrangler.jsonc"), "utf8"); assert(/"HEADER_TIMEOUT_MS": "60000"/.test(wr) && !/"vars": \{\}/.test(wr), "wrangler : HEADER_TIMEOUT_MS explicite (chaine)"); assert(JSON.parse(fs.readFileSync(path.join(ROOT, "worker", "evidenceforge-llm-proxy-v0.8", "package.json"), "utf8")).version === "0.8.0", "proxy 0.8.0");
    const cfg = P.CONFIG; assert(cfg.llm.streaming && cfg.llm.streaming.enabled === true && cfg.llm.streaming.inactivityMs >= 30000 && cfg.llm.streaming.maxTotalMs >= 300000 && cfg.observability && cfg.observability.heartbeatMs >= 5000 && cfg.observability.heartbeatMs <= 15000, "config"); assert(PL.RESUMABLE.indexOf(LS.CODE_INTERRUPTED) !== -1 && cfg.product.version === "MONOLITH-v1.0.10", "reprenable + version"); });

  await T("T-STREAM-21", "PIPELINE bout en bout (lots geles patches, transport reel streame vers le Worker factice) : flux coupe pendant TWINS_REVIEWS => STOPPED / PROVIDER_STREAM_INTERRUPTED reprenable, etape INTERRUPTED, aucun checkpoint aval, compteurs exacts, live-status persiste (FAILED, code, cible), state.live public, vue de cout `live` ; reprise explicite => flux complet, COMPLETED, checkpoint, revue journalisee SSE_STREAM", async () => {
    const r = seedRunAtProfessionals("Examinez cette demande de test de transport streame"); const un = patchSeal(); let down = 0; const seen = [];
    let restore = patchSP({ runPanel: async (input) => ({ checkpoint: fakeProCheckpoint(input.runId, input.attemptRunId), stats: { evaluated: 1 }, panelCounts: {} }), runDownstreamFromCheckpoint: async (input) => { down++; input.log({ event: "twins_built", built: 2, blocked: 0 }); const out = await input.llm.llmCall("Revue du dossier de mission (jumeau 1) " + down, { purpose: "EF-03B review", twinId: "twin-01", targetId: "target-01", pass: 1 }); seen.push(out.text.length); input.llm.onValidation({ callId: out.callId, valid: true, errors: [], stage: "EF-03B" }); return { checkpoint: fakeDownCheckpoint(input.runId, input.attemptRunId), summary: { twins: 2, blocked: 0, reviews: {}, qualification: "QUALIFIED_WITH_RESERVATIONS" } }; } });
    const hb = P.CONFIG.observability.heartbeatMs, mw = P.CONFIG.observability.minWriteMs; P.CONFIG.observability.heartbeatMs = 100; P.CONFIG.observability.minWriteMs = 50;
    try {
      fw.setStreamMode("cut"); const out = await PL.advance(r.runId); fw.setStreamMode("full"); fw.abortOpen();
      assert(out.status === "STOPPED" && out.error.code === LS.CODE_INTERRUPTED && out.resumable === true && out.stages.TWINS_REVIEWS.status === "INTERRUPTED" && out.stages.PROFESSIONALS.status === "DONE" && !fs.existsSync(path.join(r.dir, "checkpoint-downstream.json")) && /interrompue/.test(out.userMessage), JSON.stringify(out.error) + " " + JSON.stringify(out.stages));
      const ls = LIVE.readLiveStatus(r.dir); assert(ls && ls.providerCallState === "FAILED" && ls.lastTransportCode === LS.CODE_INTERRUPTED && ls.reviewTargetMode === "MISSION_DOSSIER" && ls.targetId === "target-01" && ls.twinsTotal === 2 && ls.logicalReviewsExpected === 2 && ls.logicalReviewsComplete === 0 && ls.currentTwinId === "twin-01", JSON.stringify(ls));
      assert(out.live && out.live.lastTransportCode === LS.CODE_INTERRUPTED && out.counters.llmReal >= 1, "state.live public : " + JSON.stringify(out.live)); const cv = CV.buildCostView(r); assert(cv.live && cv.live.providerCallState === "FAILED" && cv.live.lastTransportCode === LS.CODE_INTERRUPTED && cv.live.active === false, "vue de cout live : " + JSON.stringify(cv.live));
      const lc = calls(r.dir).filter((c) => c.purpose === "EF-03B review"); assert(lc.length === 1 && lc[0].outcome === "STREAM_INTERRUPTED" && lc[0].twinId === "twin-01" && lc[0].targetId === "target-01", JSON.stringify(lc)); const ev = r.events(); assert(ev.some((e) => e.event === "llm_stream_interrupted" && e.twinId === "twin-01" && e.streamStarted === true) && ev.some((e) => e.event === "transport_failure_latched"), "journal des evenements");
      /* reprise explicite : flux complet, updatedAt bouge pendant le flux (heartbeat 100 ms, flux lent 60 ms x ~30 evenements) */
      fw.setStreamMode("slow"); const samples = []; const tm = setInterval(() => { try { const s = r.read(); samples.push(s.updatedAt + "|" + (s.live && s.live.providerCallState)); } catch (e) { /* */ } }, 60);
      const out2 = await PL.advance(r.runId).finally(() => { clearInterval(tm); fw.setStreamMode("full"); });
      assert(out2.status === "COMPLETED" && down === 2 && out2.stages.TWINS_REVIEWS.status === "DONE" && r.loadCheckpoint("checkpoint-downstream.json").complete === true && seen[0] > 100, JSON.stringify(out2.stages) + " down=" + down);
      const lc2 = calls(r.dir).filter((c) => c.purpose === "EF-03B review"); assert(lc2.length === 2 && lc2[1].transport === "SSE_STREAM" && lc2[1].stream.canonical === true, JSON.stringify(lc2[1].transport)); const distinct = new Set(samples.filter((s) => /STARTED|STREAMING/.test(s)).map((s) => s.split("|")[0])); assert(distinct.size >= 2, "updatedAt rafraichi pendant le flux : " + JSON.stringify(samples.slice(0, 12)));
      const ls2 = LIVE.readLiveStatus(r.dir); assert(ls2.logicalReviewsComplete === 1 && ls2.lastValidatedReviewAt && ls2.lastCheckpointAt && ls2.providerCallState === "COMPLETED", JSON.stringify(ls2)); assert(dirText(r.dir).indexOf(fw.key) === -1, "aucun secret dans le run");
    } finally { restore(); un(); P.CONFIG.observability.heartbeatMs = hb; P.CONFIG.observability.minWriteMs = mw; } });

  await T("T-STREAM-22", "reprise apres interruption : la revue interrompue est recalculee en REEL (jamais reutilisee : aucune entree de magasin) ; une revue VALIDEE avant l'interruption est reutilisee a cout 0 a la reprise (contrat MONO-11 inchange)", async () => {
    const d = tmp(); const store = path.join(d, "store.jsonl"); const llm = mk(d); const ok = await llm.llmCall("revue jumeau A", META); llm.onValidation({ callId: ok.callId, valid: true, errors: [], stage: "EF-03B" });
    await withMode("cut", () => assertThrows(() => llm.llmCall("revue jumeau B", Object.assign({}, META, { twinId: "twin-02" })), LS.CODE_INTERRUPTED));
    const d2 = tmp(); const llm2 = createLlm({ runDir: d2, runId: "t22b", storePath: store, extraCacheDirs: [path.join(d, "llm-cache")] }); const n0 = fw.calls(); const a = await llm2.llmCall("revue jumeau A", META); assert(a.reused === true && fw.calls() === n0, "revue validee reutilisee"); const b = await llm2.llmCall("revue jumeau B", Object.assign({}, META, { twinId: "twin-02" })); assert(b.reused === false && fw.calls() === n0 + 1 && b.text.startsWith(LONG), "revue interrompue recalculee en reel"); });
  await T("T-STREAM-23", "v1.0.9 — sonde gratuite (doctor) : le proxy v0.8 annonce sa version et ses delais (X-EvidenceForge-Proxy-Version / -Timeouts) ; probeWorker les rapporte ; un proxy v0.6 / v0.7 (sans en-tetes) donne null — aucun appel amont, aucun secret", async () => {
    const PD = require("../lib/provider-diagnostic.js"); const d = await PD.probeWorker({ env: process.env, timeoutMs: 5000 }); assert(d.ready === true && d.code === "OK" && d.httpStatus === 400 && d.proxyVersion === "evidenceforge-llm-proxy/0.8-stream-timeouts" && d.proxyTimeouts === "header=60000;stream-inactivity=client;stream-max=client" && JSON.stringify(d).indexOf(fw.key) === -1, JSON.stringify(d));
    const fw2 = await startFakeWorker({ proxyVersion: null, timeoutsHeader: null }); try { const env2 = Object.assign({}, process.env); env2[K_URL] = fw2.url; env2[K_KEY] = fw2.key; const d2 = await PD.probeWorker({ env: env2, timeoutMs: 5000 }); assert(d2.ready === true && d2.proxyVersion === null && d2.proxyTimeouts === null, JSON.stringify(d2)); } finally { await fw2.close(); } });
  } finally { await fw.close(); setEnv(K_KEY, savedEnv.key || null); setEnv(K_URL, savedEnv.url || null); if (savedEnv.spacing != null) process.env.EVIDENCEFORGE_LLM_MIN_SPACING_MS = savedEnv.spacing; if (savedEnv.stream != null) process.env.EVIDENCEFORGE_LLM_STREAM = savedEnv.stream; if (savedEnv.trace != null) process.env.EVIDENCEFORGE_TRACE_REVIEWS = savedEnv.trace; if (savedEnv.timeout != null) process.env.EVIDENCEFORGE_LLM_TIMEOUT_MS = savedEnv.timeout; }
};
