#!/usr/bin/env node
"use strict";
/**
 * MONOLITH v1.0.8 — tools/stream-replay.js : REPLAY HORS LIGNE d'un run reel (aucun appel fournisseur, aucun reseau) centre sur les pannes
 * de transport pendant TWINS_REVIEWS : appels reels / reutilisations / couts / horodatages / durees par tentative, chaque echec HTTP
 * (524, 5xx, 429…) avec finalite, passe, identifiants disponibles, moments de reprise, ce qui a ete valide / recalcule / reutilise, et
 * ou le progres est perdu (passes invalides rejouees). Lit : state.json, events.jsonl, llm-calls.jsonl, cost-ledger.jsonl, budget.json,
 * review-targets.json, economic-projection.json, llm-cache/*.request.json (taille du prompt seulement — jamais son contenu).
 * v1.0.9 : + attente des EN-TETES par finalite (duree totale - stream.elapsedMs, appels SSE reussis) et champ `error` du corps d'un echec HTTP
 * (lu dans llm-cache, cle `error` / `phase` / `headerTimeoutMs` seulement — jamais un message libre).
 * Usage : node tools/stream-replay.js <runDir> [--out <prefixe>]  => <prefixe>.json + <prefixe>.md (defaut : ./STREAM-REPLAY-<runId>)
 * Aucun nom de mission, aucun contenu de document, aucun secret dans la sortie.
 */
const fs = require("fs"), path = require("path");
const lines = (f) => fs.existsSync(f) ? fs.readFileSync(f, "utf8").split("\n").filter(Boolean).map((l) => { try { return JSON.parse(l); } catch (e) { return null; } }).filter(Boolean) : [];
const json = (f) => { try { return JSON.parse(fs.readFileSync(f, "utf8")); } catch (e) { return null; } };
const r4 = (x) => Math.round(Number(x || 0) * 1e4) / 1e4;
const secs = (ms) => (ms == null ? null : Math.round(ms / 100) / 10);

function replay(runDir) {
  const state = json(path.join(runDir, "state.json")) || {}; const events = lines(path.join(runDir, "events.jsonl")); const calls = lines(path.join(runDir, "llm-calls.jsonl")); const ledger = lines(path.join(runDir, "cost-ledger.jsonl"));
  const budget = json(path.join(runDir, "budget.json")); const targets = json(path.join(runDir, "review-targets.json")); const projection = json(path.join(runDir, "economic-projection.json"));
  const errorBody = (sha) => { const f = path.join(runDir, "llm-cache", sha + ".response.json"); try { const j = JSON.parse(fs.readFileSync(f, "utf8")); const e = j && (j.error || (j.type === "error" && j)); return e ? { error: typeof e === "string" ? e : (e.error || e.type || null), phase: j.phase || null, headerTimeoutMs: j.headerTimeoutMs != null ? j.headerTimeoutMs : null, upstreamWaitMs: j.upstreamWaitMs != null ? j.upstreamWaitMs : null } : null; } catch (e) { return null; } };
  const promptChars = (sha) => { const f = path.join(runDir, "llm-cache", sha + ".request.json"); try { const j = JSON.parse(fs.readFileSync(f, "utf8")); return typeof j.prompt === "string" ? j.prompt.length : null; } catch (e) { return null; } };
  /* tentatives : bornees par les evenements de reprise (previousState RESUME) et l'arret suivant */
  const resumes = events.filter((e) => e.previousState === "RESUME"); const stops = events.filter((e) => e.nextState === "STOPPED" || e.nextState === "FAILED" || e.nextState === "COMPLETED");
  const attempts = resumes.map((rs, i) => { const next = resumes[i + 1]; const end = stops.find((s) => s.at > rs.at && (!next || s.at <= next.at)) || null;
    const led = ledger.filter((l) => l.attemptId === rs.attemptId); const real = led.filter((l) => l.kind === "REAL_CALL" || l.kind === "KIT_CALL" || l.kind === "PROBE" || l.kind === "PREFLIGHT"); const reuse = led.filter((l) => l.kind === "REUSE");
    const byPurpose = {}; real.forEach((l) => { const k = l.purpose || "?"; byPurpose[k] = byPurpose[k] || { calls: 0, usd: 0 }; byPurpose[k].calls++; byPurpose[k].usd = r4(byPurpose[k].usd + ((l.cost && l.cost.totalUsd) || 0)); });
    const ev = events.filter((e) => e.attemptId === rs.attemptId); const failures = ev.filter((e) => e.event === "transport_failure_latched").map((e) => ({ at: e.at, code: e.code, where: e.where ? String(e.where).replace(/https?:\/\/\S+/g, "<ref>") : null }));   /* jamais une reference nominative (identite de professionnel) */
    return { attemptId: rs.attemptId, resumedAt: rs.at, resumedAtStage: rs.stage, endedAt: end ? end.at : null, endState: end ? end.nextState : null, endCode: end ? end.code || null : null, durationMin: end ? Math.round((Date.parse(end.at) - Date.parse(rs.at)) / 6000) / 10 : null,
      realCalls: real.length, reuses: reuse.length, usd: r4(real.reduce((a, l) => a + ((l.cost && l.cost.totalUsd) || 0), 0)), byPurpose, twinsBuilt: (ev.find((e) => e.event === "twins_built") || {}).built || null, transportFailures: failures }; });
  /* echecs HTTP (journal des appels) */
  const failed = calls.filter((c) => c.kind === "LLM_CALL" && c.httpStatus !== 200).map((c) => { const at = c.completedAt; const ev = events.find((e) => e.event === "llm_call" && e.promptSha256 === c.promptSha256 && Math.abs(Date.parse(e.at) - Date.parse(at)) < 5000) || {}; const latch = events.find((e) => e.event === "transport_failure_latched" && Date.parse(e.at) >= Date.parse(at) && Date.parse(e.at) - Date.parse(at) < 5000) || {};
    return { attemptId: ev.attemptId || null, stage: ev.stage || null, purpose: c.purpose, pass: c.pass, startedAt: c.startedAt, completedAt: c.completedAt, durationSec: secs(Date.parse(c.completedAt) - Date.parse(c.startedAt)), httpStatus: c.httpStatus, outcome: c.outcome || ("HTTP_" + c.httpStatus), providerRequestId: c.providerRequestId || null, localRequestId: c.localRequestId, promptSha256Prefix: String(c.promptSha256 || "").slice(0, 16), promptChars: promptChars(c.promptSha256), estimatedPromptTokens: promptChars(c.promptSha256) ? Math.round(promptChars(c.promptSha256) / 4) : null,
      twinId: c.twinId || null, targetId: c.targetId || null, identityNote: c.twinId ? null : "twinId / targetId non journalises par cette version (ajoutes en v1.0.8)", usage: c.usage || null, costUsd: 0, classifiedAs: latch.code || null, resumable: true, transport: c.transport || "JSON (non streaming)", streamStarted: !!(c.stream && c.stream.started), providerBody: c.responseSha256 ? errorBody(c.responseSha256) : null }; });
  /* v1.0.9 — attente des en-tetes (vue client) sur les appels SSE reussis : duree totale - stream.elapsedMs */
  const headerWait = {}; const allHw = []; calls.filter((c) => c.kind === "LLM_CALL" && c.httpStatus === 200 && c.transport === "SSE_STREAM" && c.stream && typeof c.stream.elapsedMs === "number").forEach((c) => { const hw = (Date.parse(c.completedAt) - Date.parse(c.startedAt)) - c.stream.elapsedMs; const k = c.purpose || "?"; const o = headerWait[k] = headerWait[k] || { calls: 0, values: [] }; o.calls++; o.values.push(hw); allHw.push(hw); });
  const stats = (v) => { if (!v.length) return null; const s = v.slice().sort((a, b) => a - b); const q = (p) => s[Math.min(s.length - 1, Math.floor(p * s.length))]; return { calls: s.length, minMs: s[0], p50Ms: q(0.5), p90Ms: q(0.9), maxMs: s[s.length - 1] }; };
  const headerWaitStats = { all: stats(allHw), byPurpose: {} }; Object.keys(headerWait).forEach((k) => { headerWaitStats.byPurpose[k] = stats(headerWait[k].values); });
  /* durees des appels reussis par finalite */
  const okByPurpose = {}; calls.filter((c) => c.kind === "LLM_CALL" && c.httpStatus === 200).forEach((c) => { const d = Date.parse(c.completedAt) - Date.parse(c.startedAt); const k = c.purpose || "?"; const o = okByPurpose[k] = okByPurpose[k] || { calls: 0, maxSec: 0, sumMs: 0, maxInputTokens: 0 }; o.calls++; o.sumMs += d; o.maxSec = Math.max(o.maxSec, secs(d)); o.maxInputTokens = Math.max(o.maxInputTokens, (c.usage && c.usage.input_tokens) || 0); }); Object.keys(okByPurpose).forEach((k) => { const o = okByPurpose[k]; o.avgSec = secs(o.sumMs / o.calls); delete o.sumMs; });
  /* revues : attendues, validees, reutilisees, recalculees */
  const reviewCalls = calls.filter((c) => c.kind === "LLM_CALL" && c.purpose === "EF-03B review"); const reviewOk = reviewCalls.filter((c) => c.httpStatus === 200); const reviewReuse = calls.filter((c) => c.kind === "LLM_REUSE" && /EF-03B/.test(c.purpose || ""));
  const coverage = ledger.filter((l) => l.kind === "REAL_CALL" && /EF-02D3/.test(l.purpose || "")); const coverageByAttempt = {}; coverage.forEach((l) => { const a = coverageByAttempt[l.attemptId] = coverageByAttempt[l.attemptId] || { pass1: 0, informedRetry: 0, usd: 0 }; if (/informed/.test(l.purpose)) a.informedRetry++; else a.pass1++; a.usd = r4(a.usd + ((l.cost && l.cost.totalUsd) || 0)); });
  const twinsAttempts = attempts.filter((a) => a.twinsBuilt != null); const reSpent = twinsAttempts.slice(1).map((a) => ({ attemptId: a.attemptId, coverage: coverageByAttempt[a.attemptId] || null, note: "passes de couverture rejouees apres une reprise (passes invalides jamais reutilisables : contrat MONO-11 VALID uniquement)" }));
  const totals = { realCalls: ledger.filter((l) => l.kind !== "REUSE").length, reuses: ledger.filter((l) => l.kind === "REUSE").length, usd: r4(ledger.reduce((a, l) => a + ((l.cost && l.cost.totalUsd) || 0), 0)) };
  return { schema: "EvidenceForge.StreamReplay", schemaVersion: "MONOLITH-v1.0.8", generatedAt: new Date().toISOString(), runId: state.runId || path.basename(runDir), offline: true, providerCallsDuringReplay: 0,
    run: { status: state.status, stage: state.stage, attempts: state.attempts, errorCode: state.error && state.error.code, errorAt: state.error && state.error.at, resumable: state.error && state.error.resumable, counters: state.counters || null, budget: budget ? { mode: budget.mode, costBudgetUsd: budget.costBudgetUsd, warningThresholdUsd: budget.warningThresholdUsd } : null, totals, checkpoints: state.checkpoints ? Object.keys(state.checkpoints) : [] },
    fanout: { reviewTargetMode: targets && targets.mode, sourceDocumentCount: targets && targets.sourceDocumentCount, targets: targets ? targets.targets.length : null, targetCharacters: targets && targets.targets[0] ? targets.targets[0].characters : null, expectedTwins: projection && projection.EXPECTED_TWINS, expectedReviews: projection && projection.EXPECTED_REVIEWS, twinsBuiltPerAttempt: twinsAttempts.map((a) => ({ attemptId: a.attemptId, built: a.twinsBuilt })) },
    attempts, failures: failed, http524: failed.filter((f) => f.httpStatus === 524).length, http504: failed.filter((f) => f.httpStatus === 504).length, successfulCallDurations: okByPurpose, headerWait: headerWaitStats, sseCalls: allHw.length,
    reviews: { expected: projection && projection.EXPECTED_REVIEWS, attempted: reviewCalls.length, validated: reviewOk.length, reused: reviewReuse.length, recomputedAfterFailure: Math.max(0, reviewCalls.length - 1), note: reviewOk.length === 0 ? "aucune revue n'a jamais abouti : chaque tentative echoue sur la premiere revue" : null },
    progressLost: { resumes: twinsAttempts.length, coverageRespentPerResume: reSpent, coverageByAttempt, reviewsLost: failed.filter((f) => f.purpose === "EF-03B review").length, costOfFailedReviewsUsd: 0, costNote: "les appels en echec HTTP n'ont ni usage ni cout (aucun cout invente) ; le cout perdu est celui des passes de couverture rejouees a chaque reprise" } };
}
function md(r) {
  const L = []; L.push("# STREAM REPLAY — run `" + r.runId + "` (hors ligne, 0 appel fournisseur)"); L.push(""); L.push("Généré le " + r.generatedAt + " par `tools/stream-replay.js` (MONOLITH-v1.0.8). Lecture seule des artefacts du run ; aucun contenu de document, aucun prompt, aucun secret."); L.push("");
  L.push("## 1. État du run"); L.push(""); L.push("| Champ | Valeur |"); L.push("|---|---|"); [["statut", r.run.status + " / " + r.run.stage], ["tentatives", r.run.attempts], ["erreur finale", (r.run.errorCode || "—") + (r.run.errorAt ? " à " + r.run.errorAt : "") + (r.run.resumable ? " (reprenable)" : "")], ["compteurs", JSON.stringify(r.run.counters)], ["budget", r.run.budget ? r.run.budget.mode + " " + r.run.budget.costBudgetUsd + " USD (alerte " + r.run.budget.warningThresholdUsd + ")" : "—"], ["ledger", r.run.totals.realCalls + " appels réels, " + r.run.totals.reuses + " réutilisations, " + r.run.totals.usd + " USD"], ["checkpoints", r.run.checkpoints.join(", ") || "—"]].forEach((x) => L.push("| " + x[0] + " | " + x[1] + " |")); L.push("");
  L.push("## 2. Fanout (cibles de revue)"); L.push(""); L.push("| Mode | Documents | Cibles | Caractères de la cible | Jumeaux attendus | Revues attendues | Jumeaux construits par tentative |"); L.push("|---|---|---|---|---|---|---|"); L.push("| " + r.fanout.reviewTargetMode + " | " + r.fanout.sourceDocumentCount + " | " + r.fanout.targets + " | " + r.fanout.targetCharacters + " | " + r.fanout.expectedTwins + " | " + r.fanout.expectedReviews + " | " + r.fanout.twinsBuiltPerAttempt.map((a) => "t" + a.attemptId + ":" + a.built).join(", ") + " |"); L.push("");
  L.push("## 3. Tentatives (reprises)"); L.push(""); L.push("| Tentative | Reprise à | Étape | Fin | État | Code | Durée (min) | Appels réels | Réutilisations | USD | Jumeaux | Pannes |"); L.push("|---|---|---|---|---|---|---|---|---|---|---|---|");
  r.attempts.forEach((a) => L.push("| " + a.attemptId + " | " + a.resumedAt + " | " + a.resumedAtStage + " | " + (a.endedAt || "—") + " | " + (a.endState || "—") + " | " + (a.endCode || "—") + " | " + (a.durationMin != null ? a.durationMin : "—") + " | " + a.realCalls + " | " + a.reuses + " | " + a.usd + " | " + (a.twinsBuilt != null ? a.twinsBuilt : "—") + " | " + (a.transportFailures.map((f) => f.code + "@" + f.at.slice(11, 19)).join(" ") || "—") + " |")); L.push("");
  L.push("Détail par finalité (appels réels / USD) :"); L.push(""); r.attempts.forEach((a) => L.push("- tentative " + a.attemptId + " : " + Object.keys(a.byPurpose).map((k) => k + " " + a.byPurpose[k].calls + " (" + a.byPurpose[k].usd + " USD)").join(" ; "))); L.push("");
  L.push("## 4. Échecs HTTP (" + r.failures.length + ", dont " + r.http524 + " × 524, " + r.http504 + " × 504)"); L.push(""); L.push("| Tentative | Finalité | Passe | Début | Fin | Durée (s) | HTTP | Classé | providerRequestId | Flux commencé | Corps d'erreur | Prompt (car.) | ≈ jetons | twinId / targetId | Usage / coût |"); L.push("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
  r.failures.forEach((f) => L.push("| " + f.attemptId + " | " + f.purpose + " | " + (f.pass == null ? "—" : f.pass) + " | " + f.startedAt.slice(11, 23) + " | " + f.completedAt.slice(11, 23) + " | " + f.durationSec + " | " + f.httpStatus + " | " + (f.classifiedAs || "—") + " | " + (f.providerRequestId || "null") + " | " + (f.streamStarted ? "oui" : "non") + " | " + (f.providerBody ? f.providerBody.error + (f.providerBody.phase ? " / " + f.providerBody.phase : "") + (f.providerBody.headerTimeoutMs != null ? " / " + f.providerBody.headerTimeoutMs + " ms" : "") : "—") + " | " + (f.promptChars || "?") + " | " + (f.estimatedPromptTokens || "?") + " | " + (f.twinId || "non journalisé") + " / " + (f.targetId || "non journalisé") + " | " + (f.usage ? JSON.stringify(f.usage) : "null") + " / " + f.costUsd + " USD |")); L.push("");
  if (r.headerWait && r.headerWait.all) { L.push("## 4 bis. Attente des en-têtes (appels SSE réussis : " + r.sseCalls + ") — durée totale − flux, vue client"); L.push(""); L.push("| Finalité | Appels | min (ms) | p50 (ms) | p90 (ms) | max (ms) |"); L.push("|---|---|---|---|---|---|"); const a = r.headerWait.all; L.push("| **tous** | " + a.calls + " | " + a.minMs + " | " + a.p50Ms + " | " + a.p90Ms + " | " + a.maxMs + " |"); Object.keys(r.headerWait.byPurpose).forEach((k) => { const o = r.headerWait.byPurpose[k]; L.push("| " + k + " | " + o.calls + " | " + o.minMs + " | " + o.p50Ms + " | " + o.p90Ms + " | " + o.maxMs + " |"); }); L.push(""); }
  L.push("## 5. Durée des appels réussis (par finalité)"); L.push(""); L.push("| Finalité | Appels | Moy. (s) | Max (s) | Max jetons d'entrée |"); L.push("|---|---|---|---|---|"); Object.keys(r.successfulCallDurations).forEach((k) => { const o = r.successfulCallDurations[k]; L.push("| " + k + " | " + o.calls + " | " + o.avgSec + " | " + o.maxSec + " | " + o.maxInputTokens + " |"); }); L.push("");
  L.push("## 6. Revues logiques"); L.push(""); L.push("| Attendues | Tentées | Validées | Réutilisées | Recalculées après panne |"); L.push("|---|---|---|---|---|"); L.push("| " + r.reviews.expected + " | " + r.reviews.attempted + " | " + r.reviews.validated + " | " + r.reviews.reused + " | " + r.reviews.recomputedAfterFailure + " |"); if (r.reviews.note) L.push("\n" + r.reviews.note); L.push("");
  L.push("## 7. Où le progrès est perdu"); L.push(""); L.push("- Reprises à TWINS_REVIEWS : " + r.progressLost.resumes + " ; revues perdues (échec HTTP) : " + r.progressLost.reviewsLost + " ; coût des revues en échec : " + r.progressLost.costOfFailedReviewsUsd + " USD (" + r.progressLost.costNote + ")."); r.progressLost.coverageRespentPerResume.forEach((x) => L.push("- tentative " + x.attemptId + " : couverture rejouée — passe 1 : " + (x.coverage ? x.coverage.pass1 : 0) + ", reprises informées : " + (x.coverage ? x.coverage.informedRetry : 0) + ", " + (x.coverage ? x.coverage.usd : 0) + " USD (" + x.note + ")")); L.push("");
  return L.join("\n") + "\n";
}
if (require.main === module) {
  const args = process.argv.slice(2); const runDir = args[0]; if (!runDir || !fs.existsSync(path.join(runDir, "state.json"))) { console.error("usage: node tools/stream-replay.js <runDir> [--out <prefixe>]"); process.exit(2); }
  const oi = args.indexOf("--out"); const r = replay(path.resolve(runDir)); const prefix = oi !== -1 ? args[oi + 1] : path.join(process.cwd(), "STREAM-REPLAY-" + r.runId);
  fs.writeFileSync(prefix + ".json", JSON.stringify(r, null, 2) + "\n"); fs.writeFileSync(prefix + ".md", md(r)); console.log("replay ecrit : " + prefix + ".json / .md (appels fournisseur : 0)");
}
module.exports = { replay, md };
