"use strict";
/**
 * EvidenceForge MONOLITH v1.0.5 — test/test-panel.js
 * PROFESSIONAL PANEL COST OPTIMIZER : early-stop par suffisance (PRO-EARLY-01…12), normalisation des references d'oeuvres (WORKREF-01…04),
 * routage de modele par finalite (ROUTING-01). Aucun reseau : OpenAlex et le fournisseur sont simules par URL ; MONO-10 / MONO-11 GELES
 * sont exerces REELLEMENT (runPanel non mocke) pour verifier le contrat de la boucle gelee avec l'arret anticipe. Aucun jeton de cas.
 */
const fs = require("fs"), path = require("path");
module.exports = async function (h) {
  const { T, assert, assertThrows, tmp, sha, setEnv, K_KEY, K_URL, P, ROOT, createLlm } = h;
  const SP = require("../lib/stage-professionals.js"); const PS = require("../lib/panel-sufficiency.js"); const WN = require("../lib/workref-normalization.js"); const CL = require("../lib/cost-ledger.js"); const BG = require("../lib/budget-guard.js"); const PSEL = require("../lib/professional-selection.js");
  const V104 = path.join(ROOT, "..", "MONOLITH-v1.0.4"); const D2 = require(path.join(P.MONO01, "dependencies", "ef-02d2-mission-relevance-v1.js"));
  const dimSet = (ids) => ({ schema: "EvidenceForge.MissionDimensionSet", schemaVersion: "EF-PR-GEN-v1", dimensions: ids.map((id) => ({ id, label: id, definition: "def " + id })) });

  /* ---------- monde synthetique : D disciplines x K candidats, oeuvres suffisantes (>=3 travaux, DOI, 2 annees, 2 themes) ---------- */
  function world(D, K) {
    const dims = Array.from({ length: D }, (_, i) => "d" + (i + 1)); const cands = [];
    dims.forEach((d, di) => { for (let k = 1; k <= K; k++) { const ref = "https://openalex.org/A" + (di + 1) + "0" + k; const works = Array.from({ length: 4 }, (_, w) => ({ id: "https://openalex.org/W" + (di + 1) + "0" + k + "0" + w, display_name: "Travail " + (di + 1) + "-" + k + "-" + w + " sur l’angle " + d, doi: "https://doi.org/10.1000/w" + (di + 1) + k + w, publication_year: 2020 + (w % 3), type: "article", topics: [{ display_name: "Theme " + d, id: "T1", score: 0.9 }, { display_name: "Theme commun", id: "T2", score: 0.5 }], authorships: [{ author: { id: ref, orcid: null } }] }));
      cands.push({ ref, dim: d, rank: k, works }); } });
    return { dims, cands };
  }
  /** fetch simule PAR URL : OpenAlex (oeuvres du candidat), fournisseur (sonde + oracle EF-02D2 avec regle de decision par candidat) */
  function withWorldFetch(w, decide, fn, opts) {
    setEnv(K_KEY, "TESTKEY-not-a-real-secret-0000"); setEnv(K_URL, "http://127.0.0.1:1"); process.env.EVIDENCEFORGE_LLM_MIN_SPACING_MS = "0"; const orig = global.fetch; const seen = { openalex: [], llm: [] };
    global.fetch = async (u, init) => {
      const url = String(u);
      if (/api\.openalex\.org\/works\?filter=author\.id:/.test(url)) { const id = /author\.id:([^&]+)/.exec(url)[1]; const c = w.cands.find((x) => x.ref.endsWith("/" + id)); seen.openalex.push(id); return new Response(JSON.stringify({ results: c ? c.works : [] }), { status: 200, headers: { "content-type": "application/json" } }); }
      if (/\/v1\/messages$/.test(url)) { const body = JSON.parse(init.body); const prompt = body.messages[0].content; seen.llm.push({ model: body.model, prompt });
        if (/Reponds uniquement/.test(prompt) || body.max_tokens <= 64) return new Response(JSON.stringify({ id: "msg_p", model: body.model, content: [{ type: "text", text: /"probe":"evidenceforge"/.test(prompt) ? '{"ok":true,"probe":"evidenceforge"}' : "ok" }], usage: { input_tokens: 1, output_tokens: 1 } }), { status: 200 });
        const m = /"professionalRef":"([^"]+)"/.exec(prompt); const c = w.cands.find((x) => x.ref === (m && m[1])); const titles = (WN.corpusFromPrompt(prompt) || { corpus: { works: [] } }).corpus.works.map((x) => x.title);
        const sup = decide(c, seen.llm.length); const judgments = w.dims.map((d) => ({ dimensionId: d, relevanceStatus: sup.indexOf(d) !== -1 ? "mission_relevant" : "mission_irrelevant", epistemicStatus: "documented", rationale: "r", supportingWorkRefs: sup.indexOf(d) !== -1 ? [opts && opts.curly ? titles[1].replace("’", "'") : titles[1]] : [], limitations: [] }));   /* oeuvre NON graine (G8 anti-circularite du gate gele) */
        const usage = (opts && opts.usage) || { input_tokens: 2700, output_tokens: 2000 };
        return new Response(JSON.stringify({ id: "msg_" + seen.llm.length, model: body.model, content: [{ type: "text", text: JSON.stringify({ professionalRef: c ? c.ref : null, judgments }) }], usage, stop_reason: "end_turn" }), { status: 200 }); }
      throw new Error("URL inattendue : " + url);
    };
    return Promise.resolve().then(() => fn(seen)).finally(() => { global.fetch = orig; setEnv(K_KEY, null); setEnv(K_URL, null); });
  }
  /** runPanel REEL (MONO-10 + MONO-11 geles) sur le monde synthetique */
  async function realPanel(w, decide, extra, fetchOpts) {
    const d = tmp(); const question = "Examinez cette demande de test de suffisance du panel"; const MH = sha(question);
    const discovery = { schema: "EvidenceForge.ProfessionalDiscovery", candidates: w.cands.map((c) => ({ candidateRef: c.ref, displayName: "Pro " + c.ref.slice(-3), dimensionRef: c.dim, candidateStatus: "SEED_CANDIDATE", resolutionStatus: "RESOLVED", orcid: null, seedReferences: [{ providerWorkId: c.works[0].id, localSourceId: "s-" + c.dim, titre: c.works[0].display_name }], evidenceRefs: [c.works[0].id], provenance: [] })) };
    const verification = { schema: "EvidenceForge.ProfessionalVerification", schemaVersion: "test", missionId: "efm-mission-test", verified: [], summary: {} };
    const corpusSnapshot = { sources: w.dims.map((dm) => ({ id: "s-" + dm, statutScreening: "inclus", provenance: { originalReference: w.cands.find((c) => c.dim === dm).works[0].id } })), dateGel: "2026-01-01" };
    const runContract = { createdAt: "2026-01-01", runContractHash: "rc", disciplinesProposees: w.dims.map((dm) => ({ id: dm, discipline: dm, justification: "def " + dm, statut: "retenue" })) };
    const ledger = CL.createCostLedger({ runDir: d, runId: "efm-test-panel" }); const budget = BG.createBudgetGuard({ runDir: d, runId: "efm-test-panel", ledger }); ledger.attachBudget(budget); ledger.activate(["efm-test-panel-a1"]); if (extra && extra.budget) budget.set(extra.budget);
    const llm = createLlm({ runDir: d, runId: "efm-test-panel", storePath: path.join(d, "s.jsonl"), ledger, budget, routing: extra && extra.routing }); const events = []; let selection = null; const suff = [];
    const out = await withWorldFetch(w, decide, async (seen) => { const r = await SP.runPanel({ runDir: d, runId: "efm-test-panel", attemptId: 1, attemptRunId: "efm-test-panel-a1", missionId: "efm-mission-test", missionHash: MH, missionQuestion: question, runContract, corpusSnapshot, discovery, verification, llm, log: (e) => events.push(e), selection: null, onSelection: async (s) => { selection = s; }, onSufficiency: (x) => suff.push(x) }); return { r, seen }; }, fetchOpts);
    return Object.assign(out, { dir: d, ledger, events, selection, suff, llm });
  }
  const supportedFirstN = (n) => (c) => (c && c.rank <= n ? [c.dim] : []);

  console.log("\n  --- v1.0.5 : EARLY-STOP PAR SUFFISANCE DU PANEL ---");
  await T("PRO-EARLY-01", "panel convergent : 3 angles x 5 candidats, les 3 premiers de chaque angle sont SUPPORTED => EARLY_STOP_CONFIRMED apres 9 evaluations, 6 candidats non evalues (0 appel, 0 reseau), gate gele : 9 admis, chaines valides, checkpoint complet", async () => {
    const w = world(3, 5); const o = await realPanel(w, supportedFirstN(3)); const cp = o.r.checkpoint;
    assert(cp.sufficiency.state === "EARLY_STOP_CONFIRMED" && cp.sufficiency.evaluated === 9 && cp.sufficiency.skipped === 6 && cp.sufficiency.admissible === 9, JSON.stringify(cp.sufficiency.perDimension));
    assert(o.seen.llm.filter((x) => !/Reponds uniquement/.test(x.prompt)).length === 9, "exactement 9 appels oracle : " + o.seen.llm.length); assert(o.seen.openalex.length === 9, "aucun appel OpenAlex pour les 6 non evalues : " + o.seen.openalex.length);
    assert(cp.panel.counts.AUTO_APPROVED_FOR_DOCUMENTARY_PANEL === 9 && cp.chains.mono10.valid && cp.chains.mono11.valid && cp.complete === true, JSON.stringify(cp.panel.counts));
    assert(o.events.filter((e) => e.event === "candidate_skipped_sufficiency").length === 6 && o.suff.some((s) => s.state === "EARLY_STOP_CONFIRMED"), "evenements de non-evaluation + transition annoncee");
    assert(cp.assessment.evaluationCap.evaluationOrder === "SELECTION_ORDER" && o.seen.openalex.slice(0, 3).join() === "A101,A201,A301", "ordre tourniquet : un candidat par angle a chaque tour : " + o.seen.openalex.slice(0, 3).join());
    assert(o.r.stats.evaluatedReal === 9 && o.r.stats.skippedBySufficiency === 6 && o.r.stats.sufficiency === "EARLY_STOP_CONFIRMED"); });
  await T("PRO-EARLY-02", "nouvelle discipline tardive : deux angles a la cible mais un troisieme angle encore jamais vu => CONTINUE (jamais CONFIRMED tant qu'un angle a des candidats non echantillonnes) ; vivier epuise => CONFIRMED", () => {
    const t = PS.createSufficiencyTracker({ dimensions: ["d1", "d2", "d3"], candidates: [1, 2, 3].map((i) => ({ candidateRef: "a" + i, dimension: "d1" })).concat([1, 2, 3].map((i) => ({ candidateRef: "b" + i, dimension: "d2" })), [{ candidateRef: "c1", dimension: "d3" }]), policy: { targetAdmissiblePerDimension: 3 } });
    ["a1", "b1", "a2", "b2", "a3", "b3"].forEach((id) => t.observe({ candidateRef: id, relevanceClass: "SUPPORTED", supportedDimensions: [id[0] === "a" ? "d1" : "d2"] }));
    const d = t.decision(); assert(d.state === "EARLY_STOP_CONTINUE" && d.perDimension.d1.closed && d.perDimension.d2.closed && !d.perDimension.d3.closed, JSON.stringify(d.perDimension));
    assert(t.shouldEvaluate("c1").evaluate === true && t.shouldEvaluate("a1").evaluate === false, "l'angle non vu est evalue, les angles a la cible sont fermes");
    t.observe({ candidateRef: "c1", relevanceClass: "OUT_OF_SCOPE" }); assert(t.decision().state === "EARLY_STOP_CONFIRMED" && t.decision().coverage.exhausted.join() === "d3", "vivier de d3 epuise => suffisance demontree (avec reserve)"); });
  await T("PRO-EARLY-03", "divergence majeure tardive : un plateau (CANDIDATE) est annule par un candidat admissible ou un angle nouvellement SUPPORTED => CONTINUE ; la fenetre de grace repart", () => {
    const cands = []; ["d1", "d2"].forEach((d) => { for (let i = 1; i <= 30; i++) cands.push({ candidateRef: d + "-" + i, dimension: d }); });
    const t = PS.createSufficiencyTracker({ dimensions: ["d1", "d2"], candidates: cands, policy: { closeOnPlateau: true, plateauWindowMin: 6, plateauWindowFactor: 2, plateauGraceFactor: 2, minEvaluatedPerDimension: 2 } });
    let i = 0; const next = (cls, sup) => { i++; const d = i % 2 ? "d1" : "d2"; return t.observe({ candidateRef: d + "-" + Math.ceil(i / 2), relevanceClass: cls, supportedDimensions: sup || [] }).state; };
    for (let k = 0; k < 8; k++) next("PARTIAL"); assert(t.decision().state === "EARLY_STOP_CANDIDATE", "plateau atteint : " + t.decision().state + " since " + t.decision().sinceNovelty);
    const s = next("SUPPORTED", ["d2"]); assert(s === "EARLY_STOP_CONTINUE" && t.decision().sinceNovelty === 0, "nouveaute tardive => poursuite");
    for (let k = 0; k < 6; k++) next("OUT_OF_SCOPE"); assert(t.decision().state === "EARLY_STOP_CANDIDATE"); for (let k = 0; k < 4; k++) next("OUT_OF_SCOPE"); assert(t.decision().state === "EARLY_STOP_CONFIRMED", "grace ecoulee sans nouveaute (politique explicite closeOnPlateau) => CONFIRMED"); });
  await T("PRO-EARLY-04", "redondance prolongee : par defaut (closeOnPlateau=false) le plateau reste un SIGNAL (CANDIDATE, l'evaluation continue) ; avec closeOnPlateau=true (politique explicite) => arret apres fenetre + grace", () => {
    const mk = (pol) => { const cands = []; ["d1", "d2", "d3"].forEach((d) => { for (let i = 1; i <= 20; i++) cands.push({ candidateRef: d + "-" + i, dimension: d }); }); return PS.createSufficiencyTracker({ dimensions: ["d1", "d2", "d3"], candidates: cands, policy: Object.assign({ minEvaluatedPerDimension: 2, plateauWindowMin: 6, plateauWindowFactor: 2, plateauGraceFactor: 2 }, pol) }); };
    const run = (t, n) => { for (let i = 1; i <= n; i++) { const d = ["d1", "d2", "d3"][(i - 1) % 3]; t.observe({ candidateRef: d + "-" + Math.ceil(i / 3), relevanceClass: "PARTIAL", partialDimensions: [d] }); } return t.decision(); };
    const a = run(mk({ closeOnPlateau: false }), 40); assert(a.state === "EARLY_STOP_CANDIDATE" && a.evaluated === 40 && a.sinceNovelty >= 30, "signal seulement : " + a.state);
    const t2 = mk({ closeOnPlateau: true }); const b = run(t2, 40); assert(b.state === "EARLY_STOP_CONFIRMED" && b.confirmedAt <= 3 + 6 + 6 + 1 && t2.shouldEvaluate("d1-20").evaluate === false, "arret apres fenetre+grace : " + JSON.stringify([b.state, b.confirmedAt])); });
  await T("PRO-EARLY-05", "couverture insuffisante : un angle sans admissible et avec des candidats restants => CONTINUE, ses candidats restent evalues, meme si tous les autres angles ont atteint leur cible", () => {
    const cands = []; ["d1", "d2", "d3"].forEach((d) => { for (let i = 1; i <= 6; i++) cands.push({ candidateRef: d + "-" + i, dimension: d }); });
    const t = PS.createSufficiencyTracker({ dimensions: ["d1", "d2", "d3"], candidates: cands, policy: { targetAdmissiblePerDimension: 2 } });
    for (let i = 1; i <= 6; i++) { const d = ["d1", "d2", "d3"][(i - 1) % 3]; t.observe({ candidateRef: d + "-" + Math.ceil(i / 3), relevanceClass: d === "d3" ? "OUT_OF_SCOPE" : "SUPPORTED", supportedDimensions: d === "d3" ? [] : [d] }); }
    const d = t.decision(); assert(d.state === "EARLY_STOP_CONTINUE" && d.coverage.satisfied.join() === "d1,d2" && t.shouldEvaluate("d3-3").evaluate === true && t.shouldEvaluate("d1-3").evaluate === false, JSON.stringify(d.coverage)); });
  await T("PRO-EARLY-06", "aucun hardcoding : les modules et la configuration ne portent ni nom de cas, ni discipline particuliere, ni nombre issu du run reel ; le scanner anti-hardcoding passe", () => {
    const AH = require("../tools/anti-hardcoding-scan.js"); const hits = AH.scan(AH.SCAN.flatMap(AH.listFiles), AH.caseTokens()); assert(hits.length === 0, JSON.stringify(hits));
    const TOK = ["JM" + "JS", "fati" + "gue", "mar" + "che", "disc-0", "psychometr", "270", "274", "138", "4.19", "5.02"]; ["lib/panel-sufficiency.js", "lib/workref-normalization.js", "lib/stage-professionals.js", "lib/professional-selection.js"].forEach((f) => { const src = fs.readFileSync(path.join(ROOT, f), "utf8"); TOK.forEach((t) => assert(src.indexOf(t) === -1, t + " dans " + f)); });
    const es = P.CONFIG.professionals.earlyStop; assert(!Object.keys(es).some((k) => /^(max|stopAfter|targetCount|targetEvaluated)/i.test(k)), Object.keys(es).join()); assert(Object.keys(es).filter((k) => typeof es[k] === "number").every((k) => es[k] < 20), "aucun grand nombre absolu (cible d'evaluations) dans la politique"); });
  await T("PRO-EARLY-07", "aucun cap arbitraire comme cible : le plafond reste 150 (garde) ; la politique ne contient aucun nombre absolu d'evaluations ; 200 candidats sans admission => jamais CONFIRMED par simple comptage ; 151 selectionnes => 150 (garde inchangee)", () => {
    assert(P.CONFIG.professionals.maxCandidatesToEvaluate === 150 && /GARDE/.test(P.CONFIG.professionals.$comment)); const keys = Object.keys(PS.DEFAULTS); assert(keys.every((k) => !/maxEvaluated|maxProfessionals|stopAfter|targetCount/i.test(k)), keys.join());
    const cands = Array.from({ length: 200 }, (_, i) => ({ candidateRef: "c" + i, dimension: "d" + (i % 4) })); const t = PS.createSufficiencyTracker({ dimensions: ["d0", "d1", "d2", "d3"], candidates: cands });
    for (let i = 0; i < 199; i++) t.observe({ candidateRef: "c" + i, relevanceClass: "OUT_OF_SCOPE" }); assert(t.decision().state !== "EARLY_STOP_CONFIRMED", "pas d'arret par comptage"); t.observe({ candidateRef: "c199", relevanceClass: "OUT_OF_SCOPE" }); assert(t.decision().state === "EARLY_STOP_CONFIRMED" && t.decision().coverage.exhausted.length === 4, "vivier epuise = seule suffisance possible, avec reserve");
    const pool = (n) => ({ assessment: { assessments: Array.from({ length: n }, (_, i) => ({ candidateId: "c" + String(i).padStart(4, "0"), assessmentStatus: "PRESENT_FOR_HUMAN_REVIEW", relevance: "PLAUSIBLE", identityConfidence: "STRONG", missionEvidenceRefs: [] })) }, discovery: { candidates: Array.from({ length: n }, (_, i) => ({ candidateRef: "c" + String(i).padStart(4, "0"), dimensionRef: "d" + (i % 3) })) } });
    assert(PSEL.selectCandidates(Object.assign(pool(151), { cap: 150 })).selectedCount === 150); });
  await T("PRO-EARLY-08", "checkpoint / reprise identiques : fonctions de checkpoint byte-identiques a v1.0.4 ; un checkpoint portant `sufficiency` se charge et se verifie (hash) ; la reprise aval repart du checkpoint sans recalcul (X4 reste vert)", () => {
    const fn = (src, name) => { const i = src.indexOf("function " + name + "("); const ends = ["\n  function ", "\n  /**"].map((m) => src.indexOf(m, i + 10)).filter((x) => x > 0); return src.slice(i, ends.length ? Math.min.apply(null, ends) : undefined); };
    const a = fs.readFileSync(path.join(ROOT, "lib", "run-store.js"), "utf8"), b = fs.readFileSync(path.join(V104, "lib", "run-store.js"), "utf8"); ["saveCheckpoint", "loadCheckpoint", "checkpointHash", "writeAtomic"].forEach((n) => assert(fn(a, n) === fn(b, n), n));
    const RS = require("../lib/run-store.js"); const r = RS.createRunStore(RS.newRunId()); r.saveCheckpoint("cp.json", { v: 1, sufficiency: { state: "EARLY_STOP_CONFIRMED", skipped: 6 }, complete: true }); const cp = r.loadCheckpoint("cp.json"); assert(cp.sufficiency.skipped === 6 && cp.contentHash);
    const src = fs.readFileSync(path.join(ROOT, "lib", "stage-professionals.js"), "utf8"); const down = src.slice(src.indexOf("async function runDownstreamFromCheckpoint"), src.indexOf("module.exports")); const down4 = (function (s) { return s.slice(s.indexOf("async function runDownstreamFromCheckpoint"), s.indexOf("module.exports")); })(fs.readFileSync(path.join(V104, "lib", "stage-professionals.js"), "utf8")); assert(down === down4, "runDownstreamFromCheckpoint byte-identique a v1.0.4"); });
  await T("PRO-EARLY-09", "lignee complete : chaque candidat selectionne a un artefact corpus/relevance dans le registre MONO-11 (les non evalues portent le motif PANEL_SUFFICIENT_EARLY_STOP), professionals-sufficiency (history) liste 9 observes + 6 non evalues, reserve explicite construite pour l'aval", async () => {
    const w = world(3, 5); const o = await realPanel(w, supportedFirstN(3)); const cp = o.r.checkpoint; const ev = cp.evidence;
    w.cands.forEach((c) => { assert(ev["mono11:corpus-sufficiency:" + c.ref] && ev["mono11:relevance:" + c.ref], "artefacts pour " + c.ref); });
    const skipped = w.cands.filter((c) => c.rank > 3); skipped.forEach((c) => { const cs = ev["mono11:corpus-sufficiency:" + c.ref].artifact || ev["mono11:corpus-sufficiency:" + c.ref]; assert(JSON.stringify(cs).indexOf("PANEL_SUFFICIENT_EARLY_STOP") !== -1, "motif dans la lignee : " + c.ref); });
    const rec = o.r.sufficiencyRecord; assert(rec.history.filter((x) => !x.skipped).length === 9 && rec.history.filter((x) => x.skipped).length === 6 && rec.history.filter((x) => x.skipped).every((x) => /TARGET_ADMISSIBLE_REACHED|PANEL_SUFFICIENT/.test(x.reason)), "historique");
    assert(cp.sufficiency.reasons.length === 3 && cp.sufficiency.reasons.every((r) => /cible atteinte/.test(r)), cp.sufficiency.reasons.join(" | ")); });
  await T("PRO-EARLY-10", "budget garde la priorite : plafond atteint pendant la boucle => BUDGET_LIMIT_REACHED (verrou) avant toute decision de suffisance, aucun appel apres, panel jamais un verdict (assertNoTransportFailure)", async () => {
    const w = world(3, 5); let err = null; try { await realPanel(w, supportedFirstN(3), { budget: { costBudgetUsd: 0.05 } }, { usage: { input_tokens: 100000, output_tokens: 100000 } }); } catch (e) { err = e; }
    assert(err && err.code === "BUDGET_LIMIT_REACHED", "code : " + (err && err.code)); const src = fs.readFileSync(path.join(ROOT, "lib", "stage-professionals.js"), "utf8"); const f = src.slice(src.indexOf("async function fetchAuthorWorks"), src.indexOf("async function attributionFor")); assert(f.indexOf("transportFailure()") < f.indexOf("tracker.shouldEvaluate"), "verrou de panne verifie AVANT la suffisance"); });
  await T("PRO-EARLY-11", "couts journalises : le ledger porte exactement une ligne REAL_CALL par evaluation reelle (candidateRef), aucune pour les non evalues ; economie mesurable = 6/15 evaluations evitees", async () => {
    const w = world(3, 5); const o = await realPanel(w, supportedFirstN(3)); const es = o.ledger.entries().filter((e) => e.kind === "REAL_CALL" && e.purpose === "EF-02D2 relevance");
    assert(es.length === 9 && new Set(es.map((e) => e.candidateRef)).size === 9 && es.every((e) => e.cost && e.cost.totalUsd > 0), "ledger : " + es.length); const skipped = w.cands.filter((c) => c.rank > 3).map((c) => c.ref); assert(!es.some((e) => skipped.indexOf(e.candidateRef) !== -1)); assert(o.r.checkpoint.llmCounts.real === 9); });
  await T("PRO-EARLY-12", "lots geles byte-identiques apres le chantier (sceaux, zips MONO-10 / MONO-11 / v1.0.4)", () => {
    const lots = P.verifyFrozenLots(); assert(["MONO-10", "MONO-11", "MONO-09", "MONO-01"].every((k) => lots[k].verified) && lots["MONO-11"].canonicalZipSha256 === "3c44b397dda0997d0fff6ab4c8e8a8b311430e6a5ac7aeee38149f8349296b0b" && lots["MONO-10"].canonicalZipSha256 === "f5a4165414f4aacc32f48f50eb14d59c87a09e3f138e24f8bd14b956972c2e04");
    const crypto = require("crypto"); const z = path.join(V104, "EvidenceForge-MONOLITH-v1.0.4.zip"); if (fs.existsSync(z)) assert(crypto.createHash("sha256").update(fs.readFileSync(z)).digest("hex") === "97b999adcff395ab49f7cd33e8e70bab767c7df22ffdda0967771db5595dd961"); });

  console.log("  --- v1.0.5 : NORMALISATION DES REFERENCES / ROUTAGE ---");
  await T("WORKREF-01", "normalisation typographique : apostrophe / guillemets / casse / espaces => reference canonique du corpus (une seule correspondance) ; ambigue ou absente => inchangee ; statuts et rationales intacts ; journal", () => {
    const corpus = { corpus: { works: [{ title: "Effects of women’s “virtual” exercise", doi: "https://doi.org/10.1/a" }, { title: "Same normalized title", doi: null }, { title: "same-normalized  TITLE", doi: null }] } };
    const text = "```json\n" + JSON.stringify({ professionalRef: "x", judgments: [{ dimensionId: "d1", relevanceStatus: "mission_relevant", epistemicStatus: "documented", rationale: "R", supportingWorkRefs: ["Effects of women's \"virtual\" exercise", "same normalized title", "Titre invente"], limitations: [] }] }) + "\n```";
    const n = WN.normalizeWorkRefs(text, corpus); assert(n.normalized && n.replacements.length === 1 && n.replacements[0].canonical === "Effects of women’s “virtual” exercise", JSON.stringify(n.replacements));
    const d = JSON.parse(n.text); assert(d.judgments[0].supportingWorkRefs[0] === "Effects of women’s “virtual” exercise" && d.judgments[0].supportingWorkRefs[1] === "same normalized title" && d.judgments[0].supportingWorkRefs[2] === "Titre invente" && d.judgments[0].rationale === "R" && d.judgments[0].relevanceStatus === "mission_relevant", "ambigu et absent inchanges, sens intact");
    assert(WN.normalizeWorkRefs("pas un json", corpus).normalized === false && WN.normalizeWorkRefs(JSON.stringify({ decisions: [] }), corpus).normalized === false, "hors EF-02D2 : inchange");
    const dir = tmp(); const ad = WN.createWorkRefAdapter({ journalPath: path.join(dir, "j.jsonl") }); const prompt = "X\nCORPUS DOCUMENTAIRE DU PROFESSIONNEL (métadonnées réelles uniquement)\n" + JSON.stringify({ displayName: "P", works: corpus.corpus.works }) + "\n\nRÈGLES STRICTES"; const r = ad.adapt({ text, callId: "c1" }, prompt, { candidateRef: "A1" });
    assert(r.workRefNormalization.replacements === 1 && ad.count() === 1 && fs.readFileSync(path.join(dir, "j.jsonl"), "utf8").indexOf("women’s") !== -1 && fs.readFileSync(path.join(dir, "j.jsonl"), "utf8").indexOf('"R"') === -1, "journal sans rationale"); assert(ad.adapt({ text }, "prompt quelconque", {}).text === text, "prompt non EF-02D2 : inchange"); });
  await T("WORKREF-02", "le parseur GELE EF-02D2 refuse la reference typographique et accepte la reference normalisee : aucune preuve inventee n'est acceptee (reference absente toujours refusee)", () => {
    const corpus = { professionalRef: "https://openalex.org/A1", corpus: { works: [{ title: "L’étude “A” : résultats", doi: "https://doi.org/10.1/x" }] } }; const ds = dimSet(["d1"]);
    const mk = (ref) => JSON.stringify({ professionalRef: "https://openalex.org/A1", judgments: [{ dimensionId: "d1", relevanceStatus: "mission_relevant", epistemicStatus: "documented", rationale: "r", supportingWorkRefs: [ref], limitations: [] }] });
    let e = null; try { D2.parseRelevanceResponse(mk("L'étude \"A\" : résultats"), ds, corpus); } catch (x) { e = x; } assert(e && /absente du corpus/.test(e.message), "refus gele sur typographie");
    const n = WN.normalizeWorkRefs(mk("L'étude \"A\" : résultats"), corpus); assert(n.normalized); const d = D2.parseRelevanceResponse(n.text, ds, corpus); assert(d.judgments[0].supportingWorkRefs[0] === "L’étude “A” : résultats");
    const n2 = WN.normalizeWorkRefs(mk("Une étude inventée"), corpus); assert(n2.normalized === false); let e2 = null; try { D2.parseRelevanceResponse(mk("Une étude inventée"), ds, corpus); } catch (x) { e2 = x; } assert(e2, "invention toujours refusee"); });
  await T("WORKREF-03", "dans la boucle gelee : une reponse avec apostrophe droite est normalisee AVANT le parseur => 1 seul appel, candidat SUPPORTED (sans normalisation : reparation payante puis UNKNOWN)", async () => {
    const w = world(1, 2); const o = await realPanel(w, supportedFirstN(2), null, { curly: true }); const cp = o.r.checkpoint;
    assert(cp.workRefNormalizations === 2 && cp.panel.counts.AUTO_APPROVED_FOR_DOCUMENTARY_PANEL === 2 && o.seen.llm.filter((x) => !/Reponds uniquement/.test(x.prompt)).length === 2, JSON.stringify([cp.workRefNormalizations, cp.panel.counts, o.seen.llm.length]));
    assert(fs.existsSync(path.join(o.dir, "professionals-workref-normalization.jsonl")) && o.events.filter((e) => e.event === "workref_normalized").length === 2); });
  await T("WORKREF-04", "rejeu lecture seule du run reel (si present) : les premieres reponses EF-02D2 valides passent de 64 a 84 sur 86 avec la normalisation ; le dossier du run n'est pas modifie", () => {
    const run = process.env.EVIDENCEFORGE_REAL_PANEL_RUN || path.join(require("os").homedir(), "evidenceforge-work", "reports", "h1-v105-runs", "efm-20260917-65c805ef"); if (!fs.existsSync(path.join(run, "cost-ledger.jsonl"))) { console.log("       (run reel absent : ignore)"); return; }
    const before = fs.readdirSync(run).sort().join(); const calls = fs.readFileSync(path.join(run, "llm-calls.jsonl"), "utf8").split("\n").filter(Boolean).map(JSON.parse).filter((c) => c.kind === "LLM_CALL" && c.purpose === "EF-02D2 relevance"); const led = fs.readFileSync(path.join(run, "cost-ledger.jsonl"), "utf8").split("\n").filter(Boolean).map(JSON.parse); const cand = {}; led.forEach((e) => { if (e.candidateRef && e.callId) cand[e.callId] = e.candidateRef; });
    const seen = new Set(); let ok0 = 0, ok1 = 0, n = 0; for (const c of calls) { const cid = cand[c.responseSha256]; if (!cid || seen.has(cid)) continue; seen.add(cid); n++; const prompt = JSON.parse(fs.readFileSync(path.join(run, "llm-cache", c.promptSha256 + ".request.json"), "utf8")).prompt; const body = JSON.parse(fs.readFileSync(path.join(run, "llm-cache", c.responseSha256 + ".response.json"), "utf8")); const text = body.content.filter((x) => x.type === "text").map((x) => x.text).join("");
      const corpus = Object.assign({ professionalRef: cid }, WN.corpusFromPrompt(prompt)); const dm = /DIMENSIONS DE MISSION[^\n]*\n([\s\S]*?)\n\nCORPUS/.exec(prompt); const ds = dimSet(dm[1].split("\n").map((l) => (/^\s*-?\s*([A-Za-z0-9_-]+)\s*[:—-]/.exec(l) || [])[1]).filter(Boolean));
      try { D2.parseRelevanceResponse(text, ds, corpus); ok0++; } catch (e) { /* */ } try { D2.parseRelevanceResponse(WN.normalizeWorkRefs(text, corpus).text, ds, corpus); ok1++; } catch (e) { /* */ } }
    assert(n === 86 && ok0 === 64 && ok1 === 84, "n=" + n + " sans=" + ok0 + " avec=" + ok1); assert(fs.readdirSync(run).sort().join() === before, "run reel intact"); });
  await T("ROUTING-01", "routage par finalite : une route posee (opts.routing) envoie la finalite vers ce modele (corps de requete, ledger, llm-calls, registre), les autres finalites restent sur le modele principal ; la reuse compare le modele de la finalite ; sans route : tout au modele principal", async () => {
    const w = world(1, 1); const o = await realPanel(w, supportedFirstN(1), { routing: { "EF-02D2 relevance": "claude-haiku-4-5" } }); const oracle = o.seen.llm.filter((x) => !/Reponds uniquement/.test(x.prompt)); assert(oracle.length === 1 && oracle[0].model === "claude-haiku-4-5" && o.seen.llm.some((x) => /Reponds uniquement/.test(x.prompt) && x.model !== "claude-haiku-4-5"), "route appliquee a la finalite seulement");
    const es = o.ledger.entries().filter((e) => e.purpose === "EF-02D2 relevance"); assert(es.length === 1 && /haiku/.test(es[0].model) && es[0].priced === true); const cp = o.r.checkpoint; const rel = cp.evidence["mono11:relevance:" + w.cands[0].ref].artifact || cp.evidence["mono11:relevance:" + w.cands[0].ref]; assert(JSON.stringify(rel).indexOf("claude-haiku-4-5") !== -1, "modele journalise dans le registre MONO-11");
    const d = tmp(); await h.withFakeProvider([{ status: 200, body: h.okBody("ok") }, { status: 200, body: h.okBody("ok") }], async (seen) => { const l1 = createLlm({ runDir: d, runId: "t", storePath: path.join(d, "s.jsonl"), routing: { p: "claude-haiku-4-5" } }); const r1 = await l1.llmCall("same", { purpose: "p" }); l1.onValidation({ callId: r1.callId, valid: true }); assert(JSON.parse(seen[0].body).model === "claude-haiku-4-5"); const l2 = createLlm({ runDir: d, runId: "t2", storePath: path.join(d, "s.jsonl") }); const r2 = await l2.llmCall("same", { purpose: "p" }); assert(r2.reused === false && seen.length === 2 && JSON.parse(seen[1].body).model !== "claude-haiku-4-5", "modele different => pas de reuse"); }); });
};
