"use strict";
/**
 * EvidenceForge MONOLITH v1.0.5 — test/test-v105.js
 * Tests du chantier correctif post-run reel : COST (ledger, tarif, budget), FORECAST (estimation separee), SCREEN-PORTFOLIO (revue de
 * portefeuille, jamais une decision), PROF-ECON (economie du panel, aucun early-stop), PREFLIGHT (assistant de cadrage), HELP, NONREG.
 * Charge par test/test-monolith.js (memes helpers, memes resultats). Aucun reseau : fournisseur factice. Aucun artefact de run reel modifie.
 */
const fs = require("fs"), path = require("path");
module.exports = async function (h) {
  const { T, assert, assertThrows, tmp, sha, setEnv, K_KEY, K_URL, withFakeProvider, okBody, seedRunAtProfessionals, patchSP, patchSeal, fakeProCheckpoint, fakeDownCheckpoint, fakeLlm, P, RS, PL, ROOT, createLlm } = h;
  const CL = require("../lib/cost-ledger.js"), BG = require("../lib/budget-guard.js"), PR = require("../lib/pricing.js"), CF = require("../lib/cost-forecast.js"), CV = require("../lib/cost-view.js");
  const CPR = require("../lib/corpus-portfolio-review.js"), PE = require("../lib/professionals-economics.js"), PA = require("../lib/preflight-assistant.js"), SR = require("../lib/stage-retrieval.js");
  const { wrapMono04 } = require("../lib/mono04-fence-adapter.js");
  const V104 = path.join(ROOT, "..", "MONOLITH-v1.0.4");
  const testSnapshot = () => PR.canonicalSnapshot({ schema: "EvidenceForge.LlmPricing", version: "test-1", currency: "USD", models: [{ model: "test-model", effectiveFrom: "2020-01-01", inputPerMillion: 1, outputPerMillion: 2, cacheWrite5mPerMillion: 1.25, cacheWrite1hPerMillion: 2, cacheReadPerMillion: 0.1 }] });
  const testPricing = () => PR.createPricing({ snapshot: testSnapshot() });
  const bigBody = (t) => JSON.stringify({ id: "msg_big", model: "claude-opus-4-8", content: [{ type: "text", text: t }], usage: { input_tokens: 100000, output_tokens: 100000, cache_creation_input_tokens: 0, cache_read_input_tokens: 0 }, stop_reason: "end_turn" });   /* 0,5 + 2,5 = 3 USD au tarif Opus 4.8 */
  const mkLedger = (d, extra) => CL.createCostLedger(Object.assign({ runDir: d, runId: "t-" + path.basename(d) }, extra || {}));

  console.log("\n  --- v1.0.5 : COUT / BUDGET ---");
  await T("COST-01", "un appel reel ajoute EXACTEMENT une ligne au ledger (REAL_CALL, usage fournisseur, modele, finalite, candidateRef du meta)", async () => withFakeProvider([{ status: 200, body: okBody("ok") }], async (seen) => {
    const d = tmp(); const ledger = mkLedger(d); const llm = createLlm({ runDir: d, runId: "t", storePath: path.join(d, "s.jsonl"), ledger });
    const r = await llm.llmCall("p1", { purpose: "EF-02D2 relevance", candidateRef: "https://openalex.org/A1" }); assert(r.reused === false && seen.length === 1);
    const es = ledger.entries(); assert(es.length === 1 && es[0].kind === "REAL_CALL" && es[0].purpose === "EF-02D2 relevance" && es[0].candidateRef === "https://openalex.org/A1" && es[0].usage.input === 1 && es[0].usage.output === 1 && es[0].priced === true && es[0].cost.totalUsd > 0, JSON.stringify(es[0]));
    assert(fs.readFileSync(path.join(d, "cost-ledger.jsonl"), "utf8").trim().split("\n").length === 1 && fs.existsSync(path.join(d, "pricing-snapshot.json"))); }));
  await T("COST-02", "une reponse REUTILISEE ajoute une ligne REUSE a cout 0 et n'est JAMAIS comptee comme appel reel", async () => withFakeProvider([{ status: 200, body: okBody("ok") }], async (seen) => {
    const d = tmp(); const ledger = mkLedger(d); const llm = createLlm({ runDir: d, runId: "t", storePath: path.join(d, "s.jsonl"), ledger });
    const r1 = await llm.llmCall("same", { purpose: "x" }); llm.onValidation({ callId: r1.callId, valid: true }); const r2 = await llm.llmCall("same", { purpose: "x" });
    assert(r2.reused === true && seen.length === 1); const t = ledger.totals(); const es = ledger.entries();
    assert(es.length === 2 && es[1].kind === "REUSE" && es[1].reused === true && es[1].cost.totalUsd === 0 && t.calls.real === 1 && t.calls.reuse === 1 && t.totalUsd === es[0].cost.totalUsd, JSON.stringify(t.calls)); }));
  await T("COST-03", "entree / sortie / ecriture cache 5m et 1h / lecture cache comptes exactement (formule par million de tokens, tarif de test)", () => {
    const d = tmp(); const ledger = mkLedger(d, { pricing: testPricing() });
    const line = ledger.record({ kind: "REAL_CALL", model: "test-model", usage: { input_tokens: 1000000, output_tokens: 1000000, cache_creation_input_tokens: 1000000, cache_creation: { ephemeral_5m_input_tokens: 500000, ephemeral_1h_input_tokens: 500000 }, cache_read_input_tokens: 1000000 } });
    assert(line.cost.inputUsd === 1 && line.cost.outputUsd === 2 && line.cost.cacheWriteUsd === 1.625 && line.cost.cacheReadUsd === 0.1 && line.cost.totalUsd === 4.725, JSON.stringify(line.cost));
    const l2 = ledger.record({ kind: "REAL_CALL", model: "test-model", usage: { input_tokens: 10, output_tokens: 0, cache_creation_input_tokens: 1000000 } });   /* sans ventilation : tout en 5 min (hypothese conservatrice documentee) */
    assert(l2.cost.cacheWriteUsd === 1.25 && l2.usage.cacheWrite5m === 1000000 && l2.usage.cacheWrite1h === 0);
    const t = ledger.totals(); assert(t.tokens.input === 1000010 && t.tokens.cacheWrite5m === 1500000 && t.tokens.cacheWrite1h === 500000 && t.tokens.cacheRead === 1000000, JSON.stringify(t.tokens));
    const l3 = ledger.record({ kind: "REAL_CALL", model: "modele-inconnu", usage: { input_tokens: 5, output_tokens: 5 } }); assert(l3.priced === false && l3.cost === null && ledger.totals().calls.unpriced === 1, "modele non tarife => cout null, jamais invente"); });
  await T("COST-04", "le SNAPSHOT de tarification est persiste au premier appel (version + hash) et fait autorite pour le run : un tarif modifie ensuite est signale (derive), jamais applique ; aucun tarif hors config/llm-pricing.json", () => {
    const d = tmp(); const l1 = mkLedger(d, { pricing: testPricing() }); const a = l1.record({ kind: "REAL_CALL", model: "test-model", usage: { input_tokens: 1000000, output_tokens: 0 } });
    const snap = JSON.parse(fs.readFileSync(path.join(d, "pricing-snapshot.json"), "utf8")); assert(snap.version === "test-1" && snap.hash === a.pricingSnapshotHash && a.pricingVersion === "test-1");
    const other = PR.createPricing({ snapshot: PR.canonicalSnapshot({ schema: "EvidenceForge.LlmPricing", version: "test-2", models: [{ model: "test-model", inputPerMillion: 100, outputPerMillion: 100, cacheWrite5mPerMillion: 1, cacheWrite1hPerMillion: 1, cacheReadPerMillion: 1 }] }) });
    const l2 = mkLedger(d, { pricing: other }); const b = l2.record({ kind: "REAL_CALL", model: "test-model", usage: { input_tokens: 1000000, output_tokens: 0 } });
    assert(b.cost.totalUsd === 1 && b.pricingVersion === "test-1" && l2.totals().pricingDrift && l2.totals().pricingDrift.currentVersion === "test-2", "le snapshot du run s'applique, la derive est signalee");
    const real = PR.createPricing(); assert(real.version && real.resolve(P.CONFIG.llm.model), "le modele configure est tarife par l'autorite");
    /* aucun tarif code ailleurs : les nombres par million n'apparaissent que dans config/llm-pricing.json */
    ["lib", "server.js", "index.html"].forEach((rel) => { const list = fs.statSync(path.join(ROOT, rel)).isDirectory() ? fs.readdirSync(path.join(ROOT, rel)).map((f) => path.join(rel, f)) : [rel]; list.forEach((f) => { const src = fs.readFileSync(path.join(ROOT, f), "utf8"); assert(!/PerMillion\s*[:=]\s*\d/.test(src), "tarif code en dur dans " + f); }); }); });
  await T("COST-05", "le budget est controle AVANT l'appel : plafond 0 => aucun appel reseau (BUDGET_LIMIT_REACHED, fatal, verrouille) ; alerte franchie => un seul evenement", async () => withFakeProvider([{ status: 200, body: okBody("ok") }], async (seen) => {
    const d = tmp(); const ledger = mkLedger(d); const events = []; const budget = BG.createBudgetGuard({ runDir: d, runId: "t", ledger, onEvent: (e) => events.push(e) }); ledger.attachBudget(budget);
    budget.set({ costBudgetUsd: 0 }); const llm = createLlm({ runDir: d, runId: "t", storePath: path.join(d, "s.jsonl"), ledger, budget });
    const e = await assertThrows(() => llm.llmCall("p", { purpose: "x" }), "BUDGET_LIMIT_REACHED"); assert(e.fatal === true && /budget maximum/i.test(e.userMessage) && seen.length === 0 && llm.transportFailure().code === "BUDGET_LIMIT_REACHED");
    const e2 = await assertThrows(() => llm.llmCall("p2", { purpose: "x" }), "BUDGET_LIMIT_REACHED"); assert(e2.latched === true && seen.length === 0, "verrou : aucun appel apres le plafond");
    const d2 = tmp(); const l2 = mkLedger(d2); const ev2 = []; const b2 = BG.createBudgetGuard({ runDir: d2, runId: "t2", ledger: l2, onEvent: (e) => ev2.push(e) }); b2.set({ costBudgetUsd: 10, warningThresholdUsd: 0 });
    const llm2 = createLlm({ runDir: d2, runId: "t2", storePath: path.join(d2, "s2.jsonl"), ledger: l2, budget: b2 }); await llm2.llmCall("a", {}); await llm2.llmCall("b", {}); assert(ev2.filter((x) => x.type === "budget_warning").length === 1, "alerte emise une seule fois");
    await assertThrows(() => b2.set({ costBudgetUsd: 5, warningThresholdUsd: 6 }), "BUDGET_INVALID"); await assertThrows(() => b2.set({ costBudgetUsd: -1 }), "BUDGET_INVALID"); }));
  await T("COST-05b", "tarif inconnu + budget pose => PRICING_UNKNOWN_FOR_MODEL fail-closed AVANT l'appel ; sans budget, l'appel part et la ligne est marquee non tarifee", async () => withFakeProvider([{ status: 200, body: okBody("ok") }], async (seen) => {
    const d = tmp(); const ledger = mkLedger(d); const budget = BG.createBudgetGuard({ runDir: d, runId: "t", ledger }); budget.set({ costBudgetUsd: 50 });
    setEnv("EVIDENCEFORGE_LLM_MODEL", "modele-non-tarife-xyz"); try {
      const llm = createLlm({ runDir: d, runId: "t", storePath: path.join(d, "s.jsonl"), ledger, budget }); await assertThrows(() => llm.llmCall("p", {}), "PRICING_UNKNOWN_FOR_MODEL"); assert(seen.length === 0);
      const d2 = tmp(); const l2 = mkLedger(d2); const llm2 = createLlm({ runDir: d2, runId: "t2", storePath: path.join(d2, "s.jsonl"), ledger: l2 }); await llm2.llmCall("p", {}); assert(seen.length === 1 && l2.totals().calls.unpriced === 1 && l2.totals().totalUsd === 0);
    } finally { setEnv("EVIDENCEFORGE_LLM_MODEL", null); } }));
  await T("COST-06", "pipeline : plafond atteint pendant l'evaluation des professionnels => STOPPED / BUDGET_LIMIT_REACHED (jamais FAILED), reprenable, aucun checkpoint, PROFESSIONALS jamais DONE, aucun appel apres le plafond", async () => withFakeProvider([{ status: 200, body: okBody("ok") }, { status: 200, body: bigBody("ok") }, { status: 200, body: bigBody("ok") }], async (seen) => {
    const r = seedRunAtProfessionals("Examinez cette demande de test de budget"); const un = patchSeal(); PL.updateBudget(r.runId, { costBudgetUsd: 1, warningThresholdUsd: 0.5 });
    const restore = patchSP({ runPanel: async (input) => { await input.llm.llmCall("c1", { purpose: "EF-02D2 relevance", candidateRef: "https://openalex.org/A1" }); await input.llm.llmCall("c2", { purpose: "EF-02D2 relevance", candidateRef: "https://openalex.org/A2" }); throw new Error("NE DOIT PAS ARRIVER : le 2e appel devait etre refuse"); } });
    try { const out = await PL.advance(r.runId);
      assert(out.status === "STOPPED" && out.error && out.error.code === "BUDGET_LIMIT_REACHED" && out.resumable === true && out.stages.PROFESSIONALS.status !== "DONE" && !out.checkpoints, JSON.stringify({ s: out.status, e: out.error && out.error.code, st: out.stages.PROFESSIONALS }));
      assert(seen.length === 2, "sonde + 1 appel reel, puis refus sans reseau : " + seen.length); assert(out.cost && out.cost.budget.limitReached === true && out.cost.totalUsd >= 3 && out.cost.totalUsd < 3.01, JSON.stringify(out.cost));
      assert(r.events().some((e) => e.event === "budget_warning") && r.events().some((e) => e.event === "budget_limit") && /budget maximum/i.test(out.error.userMessage));
      const cv = PL.costView(r.runId); assert(cv.budget.limitReached === true && cv.actual.calls.real === 2 && cv.actual.byStage.PROFESSIONALS && cv.actual.byStage.PROFESSIONALS.real === 1, JSON.stringify(cv.actual.byStage));
    } finally { restore(); un(); } }));
  await T("COST-07 / COST-08", "reprise SANS augmentation => a nouveau STOPPED sans aucun appel (aucun depassement silencieux) ; augmentation explicite du budget puis reprise => COMPLETED, checkpoints produits ; le ledger est append-only et le total = somme exacte", async () => withFakeProvider([{ status: 200, body: bigBody("ok") }], async (seen) => {
    const r = seedRunAtProfessionals("Examinez cette demande de test de reprise budget"); const un = patchSeal(); PL.updateBudget(r.runId, { costBudgetUsd: 1 });
    let restore = patchSP({ runPanel: async (input) => { await input.llm.llmCall("c1", { purpose: "EF-02D2 relevance", candidateRef: "https://openalex.org/A1" }); await input.llm.llmCall("c2", { purpose: "EF-02D2 relevance", candidateRef: "https://openalex.org/A2" }); throw new Error("inatteignable"); } });
    try { const o1 = await PL.advance(r.runId); assert(o1.status === "STOPPED" && o1.error.code === "BUDGET_LIMIT_REACHED"); const n1 = seen.length; const linesBefore = fs.readFileSync(path.join(r.dir, "cost-ledger.jsonl"), "utf8");
      const o2 = await PL.advance(r.runId); assert(o2.status === "STOPPED" && o2.error.code === "BUDGET_LIMIT_REACHED" && seen.length === n1, "reprise sans budget : refus AVANT la sonde, aucun appel"); assert(fs.readFileSync(path.join(r.dir, "cost-ledger.jsonl"), "utf8").indexOf(linesBefore) === 0, "append-only");
      restore(); restore = patchSP({ runPanel: async (input) => ({ checkpoint: fakeProCheckpoint(input.runId, input.attemptRunId), stats: { evaluated: 1 }, panelCounts: {} }), runDownstreamFromCheckpoint: async (input) => ({ checkpoint: fakeDownCheckpoint(input.runId, input.attemptRunId), summary: { twins: 1, blocked: 0, reviews: {}, qualification: "QUALIFIED_WITH_RESERVATIONS" } }) });
      const up = PL.updateBudget(r.runId, { costBudgetUsd: 100, warningThresholdUsd: 50 }); assert(up.budget.costBudgetUsd === 100 && up.budget.history.length === 2 && up.budget.limitReachedAt === null);
      const o3 = await PL.advance(r.runId); assert(o3.status === "COMPLETED" && o3.checkpoints.professionals && o3.checkpoints.downstream && seen.length === n1 + 1, JSON.stringify({ s: o3.status, e: o3.error, seen: seen.length }));
      const es = CL.readEntries(r.dir); const t = CL.readTotals(r.dir); const sum = es.reduce((a, e) => a + ((e.cost && e.cost.totalUsd) || 0), 0); assert(Math.abs(t.totalUsd - sum) < 1e-9 && t.calls.real === es.filter((e) => e.kind !== "REUSE").length, "COST-10 : total = somme du ledger");
      const rep = r.loadJson("report.json"); assert(rep.cost && rep.cost.label === "ACTUAL_COST" && Math.abs(rep.cost.totalUsd - t.totalUsd) < 1e-9 && rep.cost.pricingVersion === t.pricingVersion, "rapport : cout reel du run"); assert(fs.existsSync(path.join(r.dir, "professionals-economics.json")));
      const lin = r.loadJson("lineage.json"); assert(lin.artifacts.some((a) => a.path === "budget.json") && lin.artifacts.some((a) => a.path === "pricing-snapshot.json"), "lignee : artefacts de cout inclus");
    } finally { restore(); un(); } }));
  await T("COST-09", "cout par etape = somme EXACTE des appels reels de l'etape ; par modele et par finalite idem ; le reuse n'y contribue pas", () => {
    const d = tmp(); const ledger = mkLedger(d, { pricing: testPricing() }); ledger.setStage("A"); ledger.record({ kind: "REAL_CALL", model: "test-model", purpose: "p1", usage: { input_tokens: 1000000, output_tokens: 0 } }); ledger.record({ kind: "REAL_CALL", model: "test-model", purpose: "p2", usage: { input_tokens: 0, output_tokens: 1000000 } });
    ledger.setStage("B"); ledger.record({ kind: "KIT_CALL", model: "test-model", purpose: "p1", usage: { input_tokens: 500000, output_tokens: 0 } }); ledger.record({ kind: "REUSE", model: "test-model", purpose: "p1" });
    const t = ledger.totals(); assert(t.byStage.A.totalUsd === 3 && t.byStage.A.real === 2 && t.byStage.B.totalUsd === 0.5 && t.byStage.B.real === 1 && t.byStage.B.reuse === 1 && t.totalUsd === 3.5 && t.byPurpose.p1.totalUsd === 1.5 && t.byModel["test-model"].real === 3 && t.calls.kit === 1, JSON.stringify(t.byStage)); });
  await T("COST-11", "chemin KIT (EF-01B/EF-01C1 via MONO-04) : l'adaptateur additif verifie le budget AVANT l'appel et capture usage/modele APRES (ligne KIT_CALL) ; sans opts.cost, comportement v1.0.4", async () => {
    const d = tmp(); const ledger = mkLedger(d); const budget = BG.createBudgetGuard({ runDir: d, runId: "t", ledger }); let calls = 0;
    const fakeGateway = { async executeRequest(req) { calls++; return { status: "SUCCESS", result: { id: "msg_k", model: "claude-opus-4-8", content: [{ type: "text", text: "{\"a\":1}" }], usage: { input_tokens: 1000, output_tokens: 100 } } }; } };
    const m = wrapMono04({ gateway: fakeGateway }, { cost: { ledger, budget, stage: "DISCIPLINES", purpose: "EF-01B resolver" } });
    const r = await m.gateway.executeRequest({ requestId: "q1", payload: { model: "claude-opus-4-8", max_tokens: 10, messages: [] } }); assert(r.status === "SUCCESS" && calls === 1);
    const es = ledger.entries(); assert(es.length === 1 && es[0].kind === "KIT_CALL" && es[0].stage === "DISCIPLINES" && es[0].purpose === "EF-01B resolver" && es[0].model === "claude-opus-4-8" && es[0].usage.input === 1000 && es[0].cost.totalUsd > 0, JSON.stringify(es[0]));
    budget.set({ costBudgetUsd: 0 }); await assertThrows(() => m.gateway.executeRequest({ requestId: "q2", payload: { model: "claude-opus-4-8", max_tokens: 10, messages: [] } }), "BUDGET_LIMIT_REACHED"); assert(calls === 1, "aucun appel du kit au plafond");
    const m0 = wrapMono04({ gateway: fakeGateway }, {}); await m0.gateway.executeRequest({ requestId: "q3", payload: { model: "x" } }); assert(calls === 2 && ledger.entries().length === 1, "sans opts.cost : passthrough"); });
  await T("COST-12", "sonde MONO-10 (transport non injecte) : retrouve le ledger par le registre, verifie le budget AVANT, enregistre PROBE et renseigne costUsd (contrat gele)", async () => withFakeProvider([{ status: 200, body: okBody("ok") }], async (seen) => {
    const d = tmp(); const ledger = mkLedger(d); const budget = BG.createBudgetGuard({ runDir: d, runId: "t", ledger }); ledger.attachBudget(budget); ledger.activate(["run-probe-a1"]);
    const LT = require("../lib/llm-transport.js"); const r = await LT.probe({ modelId: "claude-opus-4-8", prompt: "ok", runId: "run-probe-a1", providerId: "anthropic", workerBindingId: "w" });
    assert(r.httpStatus === 200 && typeof r.costUsd === "number" && r.costUsd > 0 && ledger.entries()[0].kind === "PROBE", JSON.stringify(r)); budget.set({ costBudgetUsd: 0 });
    await assertThrows(() => LT.probe({ modelId: "claude-opus-4-8", prompt: "ok", runId: "run-probe-a1" }), "BUDGET_LIMIT_REACHED"); assert(seen.length === 1); ledger.deactivate(["run-probe-a1"]);
    const r2 = await LT.probe({ modelId: "claude-opus-4-8", prompt: "ok", runId: "inconnu" }); assert(r2.costUsd === null && seen.length === 2, "sans ledger enregistre : sonde inchangee, costUsd null"); }));

  console.log("  --- v1.0.5 : PROJECTION ---");
  const stagesAt = (running, doneList) => { const st = {}; CF.STAGES.forEach((s) => { st[s] = { status: doneList.indexOf(s) !== -1 ? "DONE" : (s === running ? "RUNNING" : "PENDING") }; }); return st; };
  await T("FORECAST-01", "l'estimation distingue ACTUAL (mesure) et ESTIMATE (projection) : champs separes, notGuarantee, libelle explicite, et ne contient aucun tarif", () => {
    const f = CF.forecast({ stages: stagesAt("PROFESSIONALS", ["MISSION", "DISCIPLINES", "PLAN", "RETRIEVAL", "CORPUS"]), status: "RUNNING", totals: { totalUsd: 4.11, byStage: { RETRIEVAL: { totalUsd: 0.6 }, PROFESSIONALS: { totalUsd: 3.35 } } }, progress: { professionals: { selected: 123, evaluated: 35, perCandidateUsd: Array(35).fill(0.095) } } });
    assert(f.notGuarantee === true && /NOT GUARANTEE/.test(f.label) && f.actualUsd === 4.11 && f.forecast && f.perStage.find((r) => r.stage === "RETRIEVAL").kind === "MEASURED" && f.perStage.find((r) => r.stage === "PROFESSIONALS").kind === "PROJECTED");
    assert(!/PerMillion|\b(3|15|5|25) ?USD/.test(fs.readFileSync(path.join(ROOT, "lib", "cost-forecast.js"), "utf8")), "aucun tarif dans l'estimateur"); });
  await T("FORECAST-02", "la projection evolue avec les unites reellement traitees : 3/10 puis 5/10 candidats (cout par candidat mesure) ; p25/moyenne/p75 sur les mesures du run", () => {
    const st = stagesAt("PROFESSIONALS", ["MISSION", "DISCIPLINES", "PLAN", "RETRIEVAL", "CORPUS"]); const hist = null;
    const a = CF.forecast({ stages: st, status: "RUNNING", totals: { totalUsd: 0.3, byStage: { PROFESSIONALS: { totalUsd: 0.3 } } }, progress: { professionals: { selected: 10, evaluated: 3, perCandidateUsd: [0.1, 0.1, 0.1] } }, history: hist });
    const pa = a.perStage.find((r) => r.stage === "PROFESSIONALS"); assert(pa.kind === "PROJECTED" && pa.units === 7 && Math.abs(pa.remaining.central - 0.7) < 1e-9 && pa.basis === "IN_RUN", JSON.stringify(pa));
    const b = CF.forecast({ stages: st, status: "RUNNING", totals: { totalUsd: 0.5, byStage: { PROFESSIONALS: { totalUsd: 0.5 } } }, progress: { professionals: { selected: 10, evaluated: 5, perCandidateUsd: [0.05, 0.1, 0.1, 0.1, 0.15] } }, history: hist });
    const pb = b.perStage.find((r) => r.stage === "PROFESSIONALS"); assert(pb.units === 5 && Math.abs(pb.remaining.central - 0.5) < 1e-9 && pb.remaining.low <= pb.remaining.central && pb.remaining.central <= pb.remaining.high, JSON.stringify(pb));
    /* TWINS_REVIEWS non commence, sans historique => UNKNOWN => statut PARTIAL avec borne basse, jamais un central invente */
    assert(a.forecast.status === "PARTIAL" && a.forecast.central === null && a.forecast.lowerBound >= 0.3 + 0.7 - 1e-9 && a.forecast.unknownStages.indexOf("TWINS_REVIEWS") !== -1, JSON.stringify(a.forecast)); });
  await T("FORECAST-03", "projection impossible => UNKNOWN (statut PARTIAL, valeurs nulles, etapes listees), jamais une valeur inventee ; avec historique mesure => PROJECTED ; run COMPLETED => COMPLETE = reel", () => {
    const st = stagesAt("MISSION", []); const f = CF.forecast({ stages: st, status: "RUNNING", totals: { totalUsd: 0, byStage: {} }, progress: {} });
    assert(f.forecast.status === "PARTIAL" && f.forecast.low === null && f.forecast.central === null && f.forecast.high === null && f.forecast.unknownStages.length >= 5 && f.perStage.every((r) => r.kind !== "PROJECTED" || r.basis), JSON.stringify(f.forecast));
    const hist = CF.buildHistoryReference([{ totals: { byStage: { MISSION: { totalUsd: 0.02 }, DISCIPLINES: { totalUsd: 0.1 }, PLAN: { totalUsd: 0.1 }, RETRIEVAL: { totalUsd: 0.5 }, PROFESSIONALS: { totalUsd: 9 }, TWINS_REVIEWS: { totalUsd: 2.7 } } }, stages: { PROFESSIONALS: { stats: { evaluated: 150 } }, TWINS_REVIEWS: { reviews: { reviewsExpected: 13 } }, RETRIEVAL: { sources: 100 } } }]);
    assert(hist.runs === 1 && Math.abs(hist.perUnit.professionalUsd.central - 0.06) < 1e-9, JSON.stringify(hist.perUnit));
    const g = CF.forecast({ stages: st, status: "RUNNING", totals: { totalUsd: 0, byStage: {} }, progress: {}, history: hist }); assert(g.forecast.status === "PROJECTED" && g.forecast.central > 12 && g.perStage.find((r) => r.stage === "PROFESSIONALS").basis === "HISTORY_STAGE_TOTAL", JSON.stringify(g.forecast));
    const c = CF.forecast({ stages: stagesAt(null, CF.STAGES), status: "COMPLETED", totals: { totalUsd: 12.49, byStage: {} }, progress: {} }); assert(c.forecast.status === "COMPLETE" && c.forecast.central === 12.49); });
  await T("FORECAST-04", "cost-view : run sans ledger (anterieur) => ledgerPresent false, budget vide, projection PARTIAL ; progression 64/123 lue depuis les evenements reels et la selection", () => {
    const r = seedRunAtProfessionals("Examinez cette demande de test de vue de cout"); const v0 = CV.buildCostView(r); assert(v0 && v0.ledgerPresent === false && v0.actual === null && v0.budget.costBudgetUsd === null && v0.forecast.forecast.status === "PARTIAL");
    r.saveJson("professionals-selection.json", { selectedCount: 123, poolCount: 123, cap: 150, capApplied: false, selectionOrder: [] }); for (let i = 0; i < 64; i++) r.event({ level: "tech", event: "candidate_evidence", candidateId: "https://openalex.org/A" + i, corpus: "SUFFICIENT", relevance: "PARTIAL", oracleCalls: 1 });
    const ledger = mkLedger(r.dir); ledger.setStage("PROFESSIONALS"); for (let i = 0; i < 64; i++) ledger.record({ kind: "REAL_CALL", model: "claude-sonnet-4-6", purpose: "EF-02D2 relevance", candidateRef: "https://openalex.org/A" + i, usage: { input_tokens: 5000, output_tokens: 3000 } });
    const v1 = CV.buildCostView(r); assert(v1.ledgerPresent && v1.progress.professionals.evaluated === 64 && v1.progress.professionals.selected === 123 && v1.progress.professionals.perCandidateUsd.length === 64 && v1.forecast.perStage.find((x) => x.stage === "PROFESSIONALS").units === 59 && v1.actual.currentStageUsd > 0, JSON.stringify(v1.progress)); });

  console.log("  --- v1.0.5 : REVUE DE PORTEFEUILLE ---");
  const mkSources = () => [
    { sourceId: "s1", titre: "Mesure des proprietes psychometriques d'un questionnaire de marche chez l'adulte", resume: "Etude des proprietes psychometriques fiabilite validite questionnaire de marche adulte reproductibilite", discipline: "d1", type: "article" },
    { sourceId: "s2", titre: "Proprietes psychometriques d'un questionnaire de marche : fiabilite et validite", resume: "Proprietes psychometriques fiabilite validite questionnaire marche reproductibilite coherence interne", discipline: "d1", type: "article" },
    { sourceId: "s3", titre: "Validite et fiabilite psychometriques d'un questionnaire de marche", resume: "Questionnaire marche proprietes psychometriques validite fiabilite coherence interne reproductibilite", discipline: "d1", type: "article" },
    { sourceId: "s4", titre: "Architecture logicielle locale pour applications de terrain", resume: "Conception architecture logicielle locale synchronisation hors ligne applications terrain", discipline: "d2", type: "article" },
    { sourceId: "s5", titre: "Gouvernance des donnees et consentement", resume: "Cadre de gouvernance des donnees consentement responsabilite", discipline: "d3", type: "review" },
    { sourceId: "s6", titre: "Cadre generique de modelisation des relations entre entites", resume: "Methode de modelisation ontologique des entites et relations avec extension incrementale appliquee a une chaine de production", discipline: "d2", type: "article" },
    { sourceId: "s7", titre: "Autre sujet sans rapport", resume: "Texte sans lien", discipline: "d1", type: "article" },
    { sourceId: "s8", titre: "Encore un questionnaire psychometrique de marche", resume: "Questionnaire marche proprietes psychometriques validite fiabilite", discipline: "d1", type: "article" },
  ];
  const dims = [{ id: "d1", label: "d1", definition: "angle 1" }, { id: "d2", label: "d2", definition: "angle 2" }, { id: "d3", label: "d3", definition: "angle 3" }, { id: "d4", label: "d4", definition: "angle 4 (aucune source)" }];
  const mkEvidence = (inc) => ({ schema: "EvidenceForge.MachineScreeningEvidence", proposals: mkSources().map((s) => ({ sourceId: s.sourceId, proposed: inc.indexOf(s.sourceId) !== -1 ? "inclus" : "exclu", justification: "j", evidence: [], confiance: "haute" })), failedSourceIds: [], notADecision: "x" });
  await T("SCREEN-PORTFOLIO-01", "plusieurs sources fortement redondantes (titre/resume) parmi les incluses proposees => un groupe de redondance (TF-IDF cosinus, composante connexe) ; une source distincte reste hors groupe", async () => {
    const rv = await CPR.buildCorpusPortfolioReview({ llm: null, mission: "m", dimensions: dims, sources: mkSources(), evidence: mkEvidence(["s1", "s2", "s3", "s4", "s5", "s8"]) });
    assert(rv.redundancyGroups.length === 1 && rv.redundancyGroups[0].sourceIds.length === 4 && ["s1", "s2", "s3", "s8"].every((id) => rv.redundancyGroups[0].sourceIds.indexOf(id) !== -1) && rv.redundancyGroups[0].sourceIds.indexOf("s4") === -1, JSON.stringify(rv.redundancyGroups));
    assert(rv.warnings.some((w) => w.code === "POSSIBLE_REDUNDANCY") && rv.marginalValue.find((m) => m.sourceId === "s4").lexicalNovelty > rv.marginalValue.find((m) => m.sourceId === "s2").lexicalNovelty); });
  await T("SCREEN-PORTFOLIO-02", "la revue NE DECIDE PAS : notADecision, aucune decision par source, la preuve de screening est intacte (hash) et buildAuditDecisions s'appuie toujours sur les propositions d'origine + l'acte humain", async () => {
    const ev = mkEvidence(["s1", "s2", "s3"]); const before = sha(JSON.stringify(ev)); const rv = await CPR.buildCorpusPortfolioReview({ llm: null, mission: "m", dimensions: dims, sources: mkSources(), evidence: ev });
    assert(rv.notADecision === true && sha(JSON.stringify(ev)) === before && !JSON.stringify(rv).match(/"decision"\s*:\s*"(inclus|exclu)"/) && rv.suggestedReview.every((s) => Array.isArray(s.reasons)), "aucune decision produite");
    const snap = { sources: mkSources().map((s) => ({ sourceId: s.sourceId, titre: s.titre, reference: "r" })), snapshotId: "sn", snapshotHash: "sh", missionId: "m" };
    const ad = SR.buildAuditDecisions(snap, ev, {}, "Utilisateur Test"); assert(ad.decisions.every((d) => d.acteur === "human") && ad.decisions.find((d) => d.sourceId === "s1").decision === "inclus" && ad.decisions.find((d) => d.sourceId === "s4").decision === "exclu"); });
  await T("SCREEN-PORTFOLIO-03", "discipline sous-couverte detectee : angle avec des sources trouvees mais 0 ou 1 incluse ; angle sans aucune source trouvee signale ; les exclues de l'angle sont suggerees a relecture", async () => {
    const rv = await CPR.buildCorpusPortfolioReview({ llm: null, mission: "m", dimensions: dims, sources: mkSources(), evidence: mkEvidence(["s1", "s2", "s3", "s4"]) });
    const u = rv.possibleUndercoverage; assert(u.some((x) => x.dimensionId === "d3" && x.reason === "NONE_PROPOSED_INCLUDED") && u.some((x) => x.dimensionId === "d2" && x.reason === "SINGLE_PROPOSED_INCLUDED") && u.some((x) => x.dimensionId === "d4" && x.reason === "NO_SOURCE_FOUND") && !u.some((x) => x.dimensionId === "d1"), JSON.stringify(u));
    assert(rv.suggestedReview.some((s) => s.sourceId === "s5" && s.reasons.some((r) => r.code === "UNDERCOVERED_DIMENSION_EXCLUDED_SOURCE")) && rv.coverageMap.d1.proposedIncluded === 3 && rv.coverageMap.d1.found === 5); });
  await T("SCREEN-PORTFOLIO-04", "discipline surrepresentee detectee (part > facteur x part uniforme, >= minSources) ; parametres generiques lus de la config (aucun seuil de cas)", async () => {
    const rv = await CPR.buildCorpusPortfolioReview({ llm: null, mission: "m", dimensions: dims, sources: mkSources(), evidence: mkEvidence(["s1", "s2", "s3", "s8", "s4"]), config: P.CONFIG.portfolio });
    assert(rv.possibleOvercoverage.some((o) => o.dimensionId === "d1" && o.proposedIncluded === 4) && !rv.possibleOvercoverage.some((o) => o.dimensionId === "d2") && rv.parameters.overRepresentationFactor === P.CONFIG.portfolio.overRepresentationFactor, JSON.stringify(rv.possibleOvercoverage)); });
  await T("SCREEN-PORTFOLIO-05", "une methodologie generique hors domaine (proposee exclue) peut etre signalee comme pertinente : domainRelevance != haute et methodologicalRelevance != basse, preuves litterales verifiees ; une preuve inventee est refusee puis reprise informee", async () => {
    const good = (batch) => JSON.stringify({ assessments: batch.map((s) => ({ sourceId: s.sourceId, domainRelevance: s.sourceId === "s6" ? "basse" : "basse", methodologicalRelevance: s.sourceId === "s6" ? "haute" : "basse", methodologicalInterest: s.sourceId === "s6" ? "modelisation ontologique des entites et relations" : "", anglesConcernes: s.sourceId === "s6" ? ["d2"] : [], evidence: s.sourceId === "s6" ? ["modelisation ontologique des entites et relations"] : [] })) });
    const bad = (batch) => JSON.stringify({ assessments: batch.map((s) => ({ sourceId: s.sourceId, domainRelevance: "basse", methodologicalRelevance: "haute", methodologicalInterest: "x", anglesConcernes: [], evidence: ["phrase inventee absente du resume"] })) });
    const excl = mkSources().filter((s) => ["s5", "s6", "s7"].indexOf(s.sourceId) !== -1); let n = 0;
    const llm = fakeLlm([() => { n++; return bad(excl); }, () => { n++; return good(excl); }]);
    const rv = await CPR.buildCorpusPortfolioReview({ llm, mission: "m", dimensions: dims, sources: mkSources(), evidence: mkEvidence(["s1", "s2", "s3", "s4", "s8"]) });
    assert(n === 2 && rv.llmStatus === "DONE" && rv.calls[0].valid === false && rv.calls[1].valid === true && /REPRISE/.test(llm.calls[1].prompt), "preuve inventee refusee puis reprise");
    const c = rv.methodologicalCrossDomainCandidates; assert(c.length === 1 && c[0].sourceId === "s6" && c[0].methodologicalRelevance === "haute" && c[0].domainRelevance === "basse" && rv.warnings.some((w) => w.code === "GENERIC_METHOD_OUTSIDE_DOMAIN" && w.sourceId === "s6"), JSON.stringify(c));
    assert(rv.suggestedReview.some((s) => s.sourceId === "s6" && s.reasons.some((r) => r.code === "METHODOLOGICAL_RELEVANCE_DESPITE_DOMAIN")) && rv.domainVsMethod.length === 3 && !/domaine autoris|domaines interdits|allowedDomains/i.test(fs.readFileSync(path.join(ROOT, "lib", "corpus-portfolio-review.js"), "utf8")), "aucune liste de domaines");
    /* indisponibilite fournisseur : la partie deterministe reste produite, l'etat est declare */
    const llmDown = { async llmCall() { const e = new Error("NETWORK_UNAVAILABLE"); e.code = "NETWORK_UNAVAILABLE"; e.fatal = true; throw e; }, onValidation() {} };
    const rv2 = await CPR.buildCorpusPortfolioReview({ llm: llmDown, mission: "m", dimensions: dims, sources: mkSources(), evidence: mkEvidence(["s1", "s2", "s3"]) }); assert(rv2.llmStatus === "UNAVAILABLE" && rv2.redundancyGroups.length === 1 && rv2.warnings.some((w) => w.code === "PORTFOLIO_LLM_UNAVAILABLE")); });
  await T("SCREEN-PORTFOLIO-06", "aucun hardcoding de cas : les modules de revue/economie/cout ne contiennent ni nom de cas ni jeton du run reel ; le scanner refuse COSMIN / framework d'ingenierie ontologique / Responsible AI (mutation)", () => {
    const AH = require("../tools/anti-hardcoding-scan.js"); const files = AH.SCAN.flatMap(AH.listFiles); const hits = AH.scan(files, AH.caseTokens()); assert(hits.length === 0, JSON.stringify(hits));
    ["corpus-portfolio-review.js", "professionals-economics.js", "cost-forecast.js", "budget-guard.js", "cost-ledger.js", "preflight-assistant.js"].forEach((f) => { const src = fs.readFileSync(path.join(ROOT, "lib", f), "utf8"); assert(!/COSMIN|JMJS|D103|industr|psychometr|RGPD|GDPR|sant[eé]\b/i.test(src), "jeton de cas dans " + f); });
    const d = tmp(); fs.writeFileSync(path.join(d, "x.js"), "if (title.indexOf('COSMIN') !== -1) exclude();"); assert(AH.scan([path.join(d, "x.js")], []).length > 0); fs.writeFileSync(path.join(d, "y.js"), "// An industrial oriented ontology engineering framework"); assert(AH.scan([path.join(d, "y.js")], []).length > 0);
    fs.writeFileSync(path.join(d, "z.json"), JSON.stringify({ proposals: [{ sourceId: "https://openalex.org/W123456789", titre: "Un titre de source reelle assez long" }] })); process.env.EVIDENCEFORGE_CASE_ARTIFACTS = path.join(d, "z.json"); const toks = AH.caseTokens(); delete process.env.EVIDENCEFORGE_CASE_ARTIFACTS;
    assert(toks.indexOf("Un titre de source reelle assez long") !== -1 && toks.indexOf("https://openalex.org/W123456789") !== -1, "titres/identifiants de sources = jetons de cas"); });
  await T("SCREEN-PORTFOLIO-07", "la Porte 2 exige toujours l'acte humain reel : ratification sans identite refusee ; la revue est exposee dans la vue de porte mais l'acte enregistre reste lie a la preuve de screening ; aucun 'optimiser le corpus' dans l'interface", async () => {
    const r = seedRunAtProfessionals("Examinez cette demande de test de porte 2"); const s0 = r.read(); s0.status = "WAITING_USER"; s0.gate = { id: RS.GATES.RATIFY_SOURCES, since: "now" }; s0.stages.CORPUS.status = "PENDING"; r.write(s0);
    const ev = mkEvidence(["s1"]); ev.sourcesCount = 8; ev.judged = 8; ev.duplicates = 0; r.saveJson("screening-evidence.json", ev); r.saveJson("sources-enriched.json", { enriched: mkSources() }); r.saveJson("retrieval-snapshot.json", { sources: mkSources().map((s) => ({ sourceId: s.sourceId, titre: s.titre })), snapshotId: "sn", snapshotHash: "sh", missionId: "m" });
    const rv = await CPR.buildCorpusPortfolioReview({ llm: null, mission: "m", dimensions: dims, sources: mkSources(), evidence: ev }); r.saveJson("corpus-portfolio-review.json", rv); fs.unlinkSync(path.join(r.dir, "sources-ratification.json"));
    const g = PL.gateView(r.runId); assert(g.portfolio && g.portfolio.notADecision === true && g.proposals.length === 8, "vue de porte avec revue");
    await assertThrows(() => PL.ratifySources(r.runId, { ratifiedBy: "", overrides: {} }), "HUMAN_IDENTITY_REQUIRED"); assert(!fs.existsSync(path.join(r.dir, "sources-ratification.json")));
    const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8"); assert(!/optimiser le corpus/i.test(html) && /id="gsName"/.test(html) && /id="gsPortfolio"/.test(html) && /signaux, pas une décision/.test(html)); });

  console.log("  --- v1.0.5 : ECONOMIE DU PANEL ---");
  function seedEconomics() {
    const r = seedRunAtProfessionals("Examinez cette demande de test d'economie du panel"); const ids = ["https://openalex.org/A1", "https://openalex.org/A2", "https://openalex.org/A3", "https://openalex.org/A4"];
    r.saveJson("professionals-selection.json", { schema: "EvidenceForge.ProfessionalEvaluationSelection", algorithm: "PROFESSIONAL-SELECTION-v1", cap: 150, poolCount: 4, selectedCount: 4, capApplied: false, selectionOrder: ids, selectedIds: ids, perDimension: { d1: { pool: 2, selected: 2 }, d2: { pool: 2, selected: 2 } }, selectionHash: "h", poolHash: "p", complete: true });
    r.saveJson("professionals-discovery.json", { discovery: { candidates: ids.map((id, i) => ({ candidateRef: id, dimensionRef: i % 2 ? "d2" : "d1", candidateStatus: "SEED_CANDIDATE" })) }, verification: { verified: [] } });
    ids.slice(0, 3).forEach((id, i) => r.event({ level: "tech", event: "candidate_evidence", candidateId: id, corpus: "SUFFICIENT", relevance: i === 2 ? "UNKNOWN" : "SUPPORTED", oracleCalls: 1 }));
    const ledger = mkLedger(r.dir, { pricing: testPricing() }); ledger.setStage("PROFESSIONALS"); [1000000, 2000000, 500000].forEach((n, i) => ledger.record({ kind: "REAL_CALL", model: "test-model", purpose: "EF-02D2 relevance", candidateRef: ids[i], usage: { input_tokens: n, output_tokens: 0 } })); ledger.record({ kind: "REUSE", model: "test-model", purpose: "EF-02D2 relevance", candidateRef: ids[0] });
    const cp = Object.assign(fakeProCheckpoint(r.runId, r.runId + "-a1"), { assessment: { schema: "EvidenceForge.ProfessionalCandidateAssessment", assessments: ids.map((id) => ({ candidateId: id, identityConfidence: "STRONG", assessmentStatus: "PRESENT_FOR_HUMAN_REVIEW", discoveryOrigin: "SEED_CANDIDATE" })) },
      panel: { counts: {}, panelHash: "ph", reservations: [], decisions: ids.map((id, i) => ({ candidateId: id, state: i < 2 ? "AUTO_APPROVED_FOR_DOCUMENTARY_PANEL" : "AUTO_DEFERRED", reasonCodes: [] })) },
      evidence: { "mono11:relevance:https://openalex.org/A1": { kind: "relevance-evidence", artifact: { relevanceClass: "SUPPORTED", supportingDimensions: ["d1"], partialDimensions: [] } }, "mono11:relevance:https://openalex.org/A2": { kind: "relevance-evidence", artifact: { relevanceClass: "SUPPORTED", supportingDimensions: ["d1", "d2"], partialDimensions: [] } }, "mono11:relevance:https://openalex.org/A3": { kind: "relevance-evidence", artifact: { relevanceClass: "UNKNOWN", supportingDimensions: [], partialDimensions: [] } } } });
    r.saveCheckpoint("checkpoint-professionals.json", cp); r.saveJson("twins.json", { twins: [{ twinId: "twin-" + ids[0], professionalRef: ids[0] }], blocked: [] }); r.saveJson("reviews.json", { reviews: [{ twinId: "twin-" + ids[0], professionalRef: ids[0], targetId: "target-01", reviewStatus: "complete" }] });
    return { r, ids };
  }
  await T("PROF-ECON-01", "cout par professionnel persiste : evaluationCost (appels reels a son candidateRef), reusedCalls, cumulativeCost dans l'ordre de selection ; rang, discipline, identityConfidence, eligibilityStatus, twinProduced, finalUse presents", () => {
    const { r, ids } = seedEconomics(); const e = PE.buildProfessionalsEconomics(r); r.saveJson("professionals-economics.json", e); const j = r.loadJson("professionals-economics.json");
    assert(j.schema === "EvidenceForge.ProfessionalsEconomics" && j.professionals.length === 4 && j.status === "FROM_CHECKPOINT" && j.ledgerPresent === true);
    const p1 = j.professionals[0], p2 = j.professionals[1], p3 = j.professionals[2], p4 = j.professionals[3];
    assert(p1.rank === 1 && p1.candidateRef === ids[0] && p1.discipline === "d1" && p1.identityConfidence === "STRONG" && p1.evaluationCostUsd === 1 && p1.reusedCalls === 1 && p1.realCalls === 1 && p1.cumulativeCostUsd === 1 && p1.eligibilityStatus === "AUTO_APPROVED_FOR_DOCUMENTARY_PANEL" && p1.panelContribution === "ADMITTED" && p1.twinProduced === true && p1.finalUse.reviewsComplete === 1, JSON.stringify(p1));
    assert(p2.evaluationCostUsd === 2 && p2.cumulativeCostUsd === 3 && p3.evaluationCostUsd === 0.5 && p3.cumulativeCostUsd === 3.5 && p3.relevanceClass === "UNKNOWN" && p3.panelContribution === "NOT_ADMITTED" && p4.evaluated === false && p4.evaluationCostUsd === 0 && p4.cumulativeCostUsd === 3.5, JSON.stringify([p2, p3, p4]));
    assert(j.totals.evaluationCostUsd === 3.5 && j.rates.evaluated === 3 && j.rates.admitted === 2 && j.rates.twins === 1 && Math.abs(j.rates.costPerAdmittedUsd - 1.75) < 1e-9 && j.perDimension.d1.admitted === 1 && j.perDimension.d2.admitted === 1, JSON.stringify(j.rates)); });
  await T("PROF-ECON-02", "gain marginal mesurable : newCoverage / duplicateCoverage par rang (dimensions soutenues, preuves MONO-11), courbe cumulee monotone (cout, admis, couverture nouvelle, jumeaux), rang de la derniere couverture nouvelle et du dernier admis", () => {
    const { r } = seedEconomics(); const j = PE.buildProfessionalsEconomics(r); const c = j.marginalCurve;
    assert(j.professionals[0].newCoverage.join() === "d1" && j.professionals[1].newCoverage.join() === "d2" && j.professionals[1].duplicateCoverage.join() === "d1" && j.professionals[2].newCoverage.length === 0, JSON.stringify(j.professionals.map((p) => [p.newCoverage, p.duplicateCoverage])));
    for (let i = 1; i < c.length; i++) assert(c[i].cumulativeCostUsd >= c[i - 1].cumulativeCostUsd && c[i].cumulativeAdmitted >= c[i - 1].cumulativeAdmitted && c[i].cumulativeNewCoverage >= c[i - 1].cumulativeNewCoverage && c[i].cumulativeTwins >= c[i - 1].cumulativeTwins, "courbe monotone");
    assert(c[3].cumulativeCostUsd === 3.5 && c[3].cumulativeAdmitted === 2 && c[3].cumulativeNewCoverage === 2 && c[3].cumulativeTwins === 1 && j.rates.rankOfLastNewCoverage === 2 && j.rates.rankOfLastAdmitted === 2 && j.rates.distinctDimensionsCovered === 2, JSON.stringify(j.rates));
    const r2 = seedRunAtProfessionals("Examinez cette demande de test d'economie partielle"); const e2 = PE.buildProfessionalsEconomics(r2); assert(e2.status === "NOT_AVAILABLE" && e2.earlyStop.policy === "NONE", "sans selection : non disponible, jamais invente"); });
  await T("PROF-ECON-03", "le plafond 150 reste une LIMITE HAUTE, pas une cible : config inchangee (150), capIsGuardNotTarget, 151 candidats => 150 evalues, 123 => 123 ; aucune constante de panel dans lib/", () => {
    assert(P.CONFIG.professionals.maxCandidatesToEvaluate === 150 && /GARDE, pas une cible/.test(P.CONFIG.professionals.$comment)); const PSEL = require("../lib/professional-selection.js");
    const pool = (n) => ({ assessment: { assessments: Array.from({ length: n }, (_, i) => ({ candidateId: "c" + String(i).padStart(4, "0"), assessmentStatus: "PRESENT_FOR_HUMAN_REVIEW", relevance: "PLAUSIBLE", identityConfidence: "STRONG", missionEvidenceRefs: [] })) }, discovery: { candidates: Array.from({ length: n }, (_, i) => ({ candidateRef: "c" + String(i).padStart(4, "0"), dimensionRef: "d" + (i % 3) })) } });
    assert(PSEL.selectCandidates(Object.assign(pool(151), { cap: 150 })).selectedCount === 150 && PSEL.selectCandidates(Object.assign(pool(123), { cap: 150 })).selectedCount === 123 && PSEL.selectCandidates(Object.assign(pool(123), { cap: 150 })).capApplied === false);
    const { r } = seedEconomics(); assert(PE.buildProfessionalsEconomics(r).capStatus.capIsGuardNotTarget === true);
    assert(fs.readFileSync(path.join(ROOT, "lib", "professional-selection.js"), "utf8") === fs.readFileSync(path.join(V104, "lib", "professional-selection.js"), "utf8"), "selection byte-identique a v1.0.4"); });
  await T("PROF-ECON-04", "aucun early-stop arbitraire : earlyStop.policy = NONE, aucun seuil de rang/cout d'arret dans lib/, runPanel (source) inchange par rapport a v1.0.4, MONO-11 recoit toujours l'assessment plafonne entier", () => {
    const { r } = seedEconomics(); assert(PE.buildProfessionalsEconomics(r).earlyStop.policy === "NONE");
    fs.readdirSync(path.join(ROOT, "lib")).forEach((f) => { const src = fs.readFileSync(path.join(ROOT, "lib", f), "utf8"); assert(!/earlyStop(Threshold|Rank|At)\s*[:=]\s*\d|stopAfter\s*[:=]\s*\d|maxAdmitted\s*[:=]\s*\d/.test(src), "seuil d'arret dans " + f); });
    assert(fs.readFileSync(path.join(ROOT, "lib", "stage-professionals.js"), "utf8") === fs.readFileSync(path.join(V104, "lib", "stage-professionals.js"), "utf8"), "stage-professionals.js byte-identique a v1.0.4 (runPanel, garde dure, checkpoints)"); });

  console.log("  --- v1.0.5 : ASSISTANT DE CADRAGE / AIDE ---");
  const goodPre = (q) => JSON.stringify({ clarte: "moyenne", neutralite: "basse", problemes: [{ type: "TERME_ORIENTANT", detail: "un terme oriente la reponse", extrait: q.slice(0, 12) }], propositionReformulee: "Examiner de facon neutre le document fourni.", questionsAPoser: ["Quel perimetre ?"] });
  await T("PREFLIGHT-01", "l'assistant ne modifie JAMAIS silencieusement la demande : original rendu tel quel (hash), proposition dans un champ distinct, notADecision ; aucun run cree", async () => {
    const q = "Prouver que ce dispositif est excellent pour tous les usagers"; const before = RS.listRuns().length; const llm = fakeLlm([goodPre(q)]);
    const r = await PA.reviewRequest({ llm, question: q, documents: [] }); assert(r.notADecision === true && r.original.question === q && r.original.questionSha256 === sha(q) && r.proposalDiffers === true && r.review.propositionReformulee !== q && r.review.problemes[0].type === "TERME_ORIENTANT", JSON.stringify(r.review));
    assert(RS.listRuns().length === before && llm.calls.length === 1 && llm.calls[0].meta.purpose === "request preflight"); });
  await T("PREFLIGHT-02", "l'assistant ne confirme jamais la Porte 1 : le module n'expose ni confirmation ni creation de run ; la route /api/preflight n'appelle ni startRun ni confirmPlan ni advance ; confirmPlan exige toujours un acte humain identifie", async () => {
    assert(!PA.confirm && !PA.confirmPlan && !PA.startRun && Object.keys(PA).join() === "reviewRequest,validate,PROMPT,PROBLEM_TYPES,LEVELS");
    const src = fs.readFileSync(path.join(ROOT, "server.js"), "utf8"); const route = src.slice(src.indexOf('p === "/api/preflight"'), src.indexOf('const mr = /^')); assert(route.length > 50 && !/startRun|confirmPlan|advance\(|ratifySources/.test(route), "route de cadrage isolee");
    const r = seedRunAtProfessionals("Examinez cette demande de test de porte 1"); const s0 = r.read(); s0.status = "WAITING_USER"; s0.gate = { id: RS.GATES.CONFIRM_PLAN, since: "now" }; r.write(s0);
    await assertThrows(() => PL.confirmPlan(r.runId, { validatedBy: "" }), "HUMAN_IDENTITY_REQUIRED"); });
  await T("PREFLIGHT-03", "refus utilisateur = demande d'origine conservee (interface : la zone n'est modifiee que par « Utiliser cette reformulation », « Revenir » restaure l'original) ; un extrait invente est refuse puis reprise informee ; deux refus => PREFLIGHT_INVALID, demande inchangee", async () => {
    const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8"); const js = html.slice(html.indexOf("btnPreflight"), html.indexOf("importReport"));
    assert(/id="preUse"/.test(js) && /id="preKeep"/.test(js) && /PRE_ORIGINAL/.test(js) && (js.match(/\$\("#q"\)\.value=/g) || []).length === 2 && /preRevert/.test(js), "la zone n'est ecrite que sur clic explicite (utiliser / revenir)");
    const q = "Examiner ce cahier des charges et dire ce qui est etaye"; const bad = JSON.stringify({ clarte: "haute", neutralite: "haute", problemes: [{ type: "AMBIGUITE", detail: "x", extrait: "phrase inventee" }], propositionReformulee: "", questionsAPoser: [] });
    const llm = fakeLlm([bad, goodPre(q)]); const r = await PA.reviewRequest({ llm, question: q, documents: [] }); assert(llm.calls.length === 2 && /REPRISE/.test(llm.calls[1].prompt) && r.provenance.calls[0].valid === false && r.provenance.calls[1].valid === true && r.original.question === q);
    await assertThrows(() => PA.reviewRequest({ llm: fakeLlm([bad, bad]), question: q, documents: [] }), "PREFLIGHT_INVALID"); await assertThrows(() => PA.reviewRequest({ llm: fakeLlm([goodPre("x")]), question: "court", documents: [] }), "MISSION_INVALID"); });
  await T("HELP-01", "aide accessible sans bloquer le parcours : bouton Aide, panneau masque par defaut, fermable, sans code EF-*/MONO-* ; couvre etapes, portes, jumeaux, lecture du rapport, cout, cadrage, limites", () => {
    const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8"); const help = html.slice(html.indexOf('id="helpCard"'), html.indexOf("<!-- ================= MODE SIMPLE"));
    assert(/id="btnHelp"/.test(html) && /id="helpCard" hidden/.test(html) && /id="btnHelpClose"/.test(html) && !/required/.test(help) && !/EF-0|MONO-1|MONO-0/.test(help));
    ["Porte 1", "Porte 2", "jumeaux documentaires", "établi", "convergent", "divergent", "provisoire", "non établi", "Pourquoi EvidenceForge dit cela", "Coût du run", "budget", "Vérifier ma demande avec l'IA", "Reprendre le run"].forEach((k) => assert(help.indexOf(k) !== -1, "aide : " + k));
    const simple = html.slice(html.indexOf('<section id="simple">'), html.indexOf('<section id="expert"')); assert(!/EF-0[0-9]|MONO-[01][0-9]/.test(simple.replace(/<!--[\s\S]*?-->/g, "")), "mode simple sans code technique"); });

  console.log("  --- v1.0.5 : NON-REGRESSION ---");
  await T("NONREG-01", "lots geles byte-identiques : sceaux verifies (4 lots), zips canoniques MONO-10 / MONO-11 aux SHA declares, MONO-11 = 52 fichiers", () => {
    const lots = P.verifyFrozenLots(); assert(lots["MONO-11"].verified && lots["MONO-11"].files === 52 && lots["MONO-10"].verified && lots["MONO-09"].verified && lots["MONO-01"].verified);
    assert(lots["MONO-11"].canonicalZipSha256 === "3c44b397dda0997d0fff6ab4c8e8a8b311430e6a5ac7aeee38149f8349296b0b" && lots["MONO-10"].canonicalZipSha256 === "f5a4165414f4aacc32f48f50eb14d59c87a09e3f138e24f8bd14b956972c2e04");
    const kits = [P.EF01B, P.EF01C1]; kits.forEach((k) => assert(fs.existsSync(path.join(k, "lib", "real-llm-call.js")), "kit present : " + k)); });
  await T("NONREG-02", "hashes geles identiques avant/apres : le paquet v1.0.4 (predecesseur, GELE) verifie toujours son SHA256SUMS et son zip canonique 97b999ad… ; les lots referencent la meme config gelee", () => {
    if (!fs.existsSync(V104)) { console.log("       (v1.0.4 absent a cote : verification du zip ignoree)"); return; }
    const lines = fs.readFileSync(path.join(V104, "SHA256SUMS.txt"), "utf8").trim().split("\n"); const crypto = require("crypto"); lines.forEach((l) => { const [hsh, rel] = l.split(/\s+/); assert(crypto.createHash("sha256").update(fs.readFileSync(path.join(V104, rel))).digest("hex") === hsh, "v1.0.4 modifie : " + rel); });
    const z = path.join(V104, "EvidenceForge-MONOLITH-v1.0.4.zip"); if (fs.existsSync(z)) assert(crypto.createHash("sha256").update(fs.readFileSync(z)).digest("hex") === "97b999adcff395ab49f7cd33e8e70bab767c7df22ffdda0967771db5595dd961");
    const c4 = JSON.parse(fs.readFileSync(path.join(V104, "config", "monolith.config.json"), "utf8")); assert(JSON.stringify(c4.frozenLots) === JSON.stringify(P.CONFIG.frozenLots) && c4.professionals.maxCandidatesToEvaluate === P.CONFIG.professionals.maxCandidatesToEvaluate && c4.llm.model === P.CONFIG.llm.model); });
  await T("NONREG-03", "reprise / checkpoints inchanges : run-store (checkpointHash, saveCheckpoint, loadCheckpoint, writeAtomic) et stage-professionals byte-identiques a v1.0.4 hors etat public ; le ledger n'entre dans aucun checkpoint", () => {
    const fn = (src, name) => { const i = src.indexOf("function " + name + "("); const j = src.indexOf("\n  function ", i + 10); return src.slice(i, j > 0 ? j : undefined); };
    const a = fs.readFileSync(path.join(ROOT, "lib", "run-store.js"), "utf8"), b = fs.readFileSync(path.join(V104, "lib", "run-store.js"), "utf8");
    ["saveCheckpoint", "loadCheckpoint", "checkpointHash", "writeAtomic", "markInterruptedRuns"].forEach((n) => assert(fn(a, n) === fn(b, n), "run-store." + n + " modifie"));
    ["stage-professionals.js", "professional-selection.js", "stage-retrieval.js", "screening-evidence.js", "stage-mission.js", "paths.js"].forEach((f) => assert(fs.readFileSync(path.join(ROOT, "lib", f), "utf8") === fs.readFileSync(path.join(V104, "lib", f), "utf8"), f + " modifie"));
    fs.readdirSync(path.join(ROOT, "vendor", "operator-kit-r1.3")).forEach((f) => assert(fs.readFileSync(path.join(ROOT, "vendor", "operator-kit-r1.3", f)).equals(fs.readFileSync(path.join(V104, "vendor", "operator-kit-r1.3", f))), "vendor modifie : " + f));
    const sp = fs.readFileSync(path.join(ROOT, "lib", "stage-professionals.js"), "utf8"); assert(!/cost|ledger\.record|budget/.test(sp.replace(/ledger\.(record|ref|export|verifyChain|exportArtifacts|rootHash)|mono11-ledger|ledgerExport|ledgerRoot|Ledger/g, "")), "aucun cout dans les checkpoints"); });
  await T("NONREG-04", "Porte 1 inchangee : confirmPlan (pipeline) et S1.confirmPlan byte-identiques a v1.0.4 ; la reformulation (stage-mission) inchangee", () => {
    const fn = (src, name) => { const i = src.indexOf("async function " + name + "("); const j = src.indexOf("\n}\n", i); return src.slice(i, j + 3); };
    const a = fs.readFileSync(path.join(ROOT, "lib", "pipeline.js"), "utf8"), b = fs.readFileSync(path.join(V104, "lib", "pipeline.js"), "utf8"); assert(fn(a, "confirmPlan") === fn(b, "confirmPlan") && fn(a, "confirmPlan").length > 200, "confirmPlan modifie");
    const c = fs.readFileSync(path.join(ROOT, "lib", "stage-ef01.js"), "utf8"), d = fs.readFileSync(path.join(V104, "lib", "stage-ef01.js"), "utf8"); assert(fn(c, "confirmPlan") === fn(d, "confirmPlan") && fn(c, "confirmPlan").length > 200, "S1.confirmPlan modifie"); });
  await T("NONREG-05", "Porte 2 humaine inchangee : ratifySources (pipeline) et buildAuditDecisions byte-identiques a v1.0.4 ; la ratification enregistre le hash de la preuve de screening (jamais celui de la revue)", () => {
    const fn = (src, name) => { const i = src.indexOf("function " + name + "("); const j = src.indexOf("\n}\n", i); return src.slice(i, j + 3); };
    const a = fs.readFileSync(path.join(ROOT, "lib", "pipeline.js"), "utf8"), b = fs.readFileSync(path.join(V104, "lib", "pipeline.js"), "utf8"); assert(fn(a, "ratifySources") === fn(b, "ratifySources") && /evidenceSha256: sha\(JSON\.stringify\(store\.loadJson\("screening-evidence\.json"\)\)\)/.test(fn(a, "ratifySources")));
    const c = fs.readFileSync(path.join(ROOT, "lib", "stage-retrieval.js"), "utf8"), d = fs.readFileSync(path.join(V104, "lib", "stage-retrieval.js"), "utf8"); assert(fn(c, "buildAuditDecisions") === fn(d, "buildAuditDecisions")); });
  await T("NONREG-06", "runs anterieurs (v1.0.4, sans ledger ni budget) restent lisibles : etat public avec cost.ledgerPresent=false, vue de cout PARTIAL, economie NOT_AVAILABLE, aucune ecriture dans le dossier du run", () => {
    const r = seedRunAtProfessionals("Examinez cette demande de test d'ancien run"); const files = fs.readdirSync(r.dir).sort();
    const ps = r.publicState(r.read()); assert(ps.cost && ps.cost.ledgerPresent === false && ps.cost.totalUsd === null && ps.cost.budget.costBudgetUsd === null); const cv = PL.costView(r.runId); assert(cv.ledgerPresent === false && cv.forecast.forecast.status === "PARTIAL"); assert(PL.economicsView(r.runId).status === "NOT_AVAILABLE");
    assert(JSON.stringify(fs.readdirSync(r.dir).sort()) === JSON.stringify(files), "lecture seule"); });
};
