#!/usr/bin/env node
"use strict";
/**
 * MONOLITH v1.0.10 — tools/ef03b-autopsy.js : AUTOPSIE + TAXONOMIE + ANALYSE DE COUT + REPLAY HORS LIGNE des revues EF-03B d'un run
 * reel, en LECTURE SEULE (aucun appel fournisseur, aucun reseau). Sources : llm-calls.jsonl, cost-ledger.jsonl, enforcement-traces.json,
 * reviews.json, twins.json, target-document-set.json, review-schema.json, llm-cache/*.response.json, magasin de reuse partage
 * (validationStatus par reponse). Les modules GELES (MONO-11 review-enforcer : validateReviewCandidate / parseRepair / recompose ;
 * MONO-01 EF-03B parseReviewResponse) sont UTILISES tels quels pour re-valider hors ligne des candidats historiques — jamais modifies.
 * Usage : node tools/ef03b-autopsy.js <runDir> --out <dossier>   => EF03B-REAL-RUN-AUTOPSY-v1.md, EF03B-FAILURE-TAXONOMY-v1.{json,md},
 *         EF03B-COST-ANALYSIS-v1.{json,md}, EF03B-REPLAY-v1.{json,md}
 * Aucun prompt, aucune reponse complete, aucun secret dans la sortie ; identifiants publics de professionnels (references) seulement.
 */
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const ROOT = path.resolve(__dirname, ".."); const P = require(path.join(ROOT, "lib", "paths.js")); const SP = require(path.join(ROOT, "lib", "stage-professionals.js"));
const RE = require(path.join(P.MONO11, "core", "review-enforcer.js")); const EF3 = require(path.join(ROOT, "lib", "ef03b-resilience.js"));
const sha = (s) => crypto.createHash("sha256").update(String(s), "utf8").digest("hex"); const r4 = (x) => Math.round(Number(x || 0) * 1e4) / 1e4;
const lines = (f) => fs.existsSync(f) ? fs.readFileSync(f, "utf8").split("\n").filter(Boolean).map((l) => { try { return JSON.parse(l); } catch (e) { return null; } }).filter(Boolean) : [];
const json = (f) => JSON.parse(fs.readFileSync(f, "utf8"));
const CATS = { A: "MAX_TOKENS_TRUNCATED", B: "JSON_INCOMPLETE", C: "SCHEMA_DRIFT", D: "CARDINALITY", E: "DIMENSION_MISSING", F: "DIMENSION_DUPLICATE", G: "TARGET_REF_NOT_LITERAL", H: "PROVENANCE_INVALID", I: "MISSING_KEY", J: "ENUM_INVALID", K: "EXCESSIVE_BUT_VALID", L: "REPAIR_MISTARGETED", M: "OTHER" };
const codeToCat = (code) => ({ JSON_INVALID: "B", EXTRA_KEY: "C", ROOT_NOT_OBJECT: "C", FINDINGS_MISSING: "C", FINDING_NOT_OBJECT: "C", CARDINALITY: "D", DIMENSION_MISSING: "E", DIMENSION_DUPLICATE: "F", DIMENSION_UNKNOWN: "C", DIMENSION_ORDER: "C", TARGET_REF_NOT_LITERAL: "G", TWIN_REF_UNKNOWN: "H", DOCUMENTED_WITHOUT_TWIN_REF: "H", MISSING_KEY: "I", ENUM_DISPOSITION: "J", ENUM_EPISTEMIC: "J", ENUM_CONFIDENCE: "J", FINDING_EMPTY: "I", RATIONALE_MISSING: "I", TARGET_REFS_NOT_ARRAY: "I", TWIN_REFS_NOT_ARRAY: "I", LIMITATIONS_NOT_ARRAY: "I", REPAIR_JSON_INVALID: "L", REPAIR_SCHEMA_INVALID: "L", REPAIR_INCOMPLETE: "L" })[code] || "M";

function analyse(runDir) {
  const { F } = SP.loadSealedMono11();
  const calls = lines(path.join(runDir, "llm-calls.jsonl")).filter((c) => c.kind === "LLM_CALL" && /^EF-03B/.test(c.purpose || ""));
  const led = {}; lines(path.join(runDir, "cost-ledger.jsonl")).forEach((e) => { if (e.callId && !led[e.callId]) led[e.callId] = e; });
  const store = {}; lines(path.join(P.RUNS, "llm-reuse-store.jsonl")).forEach((e) => { if (e.responseSha256) store[e.responseSha256] = e; });
  const traces = json(path.join(runDir, "enforcement-traces.json")).reviews; const reviews = json(path.join(runDir, "reviews.json")); const twins = json(path.join(runDir, "twins.json")).twins;
  const tds = json(path.join(runDir, "target-document-set.json")); const schema = json(path.join(runDir, "review-schema.json")); const state = json(path.join(runDir, "state.json"));
  const dims = schema.dimensions.map((d) => d.id); const twinById = {}; twins.forEach((t) => { twinById[t.twinId] = t; });
  const textOf = (id) => { try { const j = json(path.join(runDir, "llm-cache", id + ".response.json")); return j.content.filter((c) => c.type === "text").map((c) => c.text).join(""); } catch (e) { return null; } };
  const dur = (c) => (Date.parse(c.completedAt) - Date.parse(c.startedAt)) / 1000;
  const finalAttempt = Math.max.apply(null, Object.values(led).map((e) => e.attemptId || 0));
  /* ---- 1. par revue : passes de la tentative finale (traces) + historique des tentatives precedentes (magasin de reuse) ---- */
  const perReview = [], taxonomy = {}, catCost = {}, fieldStats = { complete: [], truncated: [] }; const trnl = { classes: {}, examples: {} }; let cumulative = 0;
  const tx = (cat, cost, pass, recovered) => { const t = taxonomy[cat] = taxonomy[cat] || { category: cat, name: CATS[cat], cases: 0, costUsd: 0, passes: {}, recoveredAtNextPass: 0, terminal: 0 }; t.cases++; t.costUsd = r4(t.costUsd + cost); t.passes[pass] = (t.passes[pass] || 0) + 1; if (recovered === true) t.recoveredAtNextPass++; if (recovered === "terminal") t.terminal++; };
  for (const t of traces) {
    const twin = twinById[t.twinId]; const doc = F.M01.TDS.getDocumentForTarget(tds, t.targetId); const rv = reviews.reviews.find((r) => r.twinId === t.twinId && r.targetId === t.targetId) || {};
    const row = { twinId: t.twinId, professionalRef: twin && twin.professionalRef, targetId: t.targetId, finalStatus: rv.reviewStatus, finalError: rv.error ? String(rv.error).slice(0, 200) : null, acceptedPass: t.acceptedPass, passes: [], costUsd: 0, worksUsed: twin && twin.documentaryBasis ? twin.documentaryBasis.worksUsed.length : null };
    t.passes.forEach((p, i) => {
      const c = calls.find((x) => x.responseSha256 === p.callId) || {}; const e = led[p.callId] || {}; const cost = (e.cost && e.cost.totalUsd) || 0; row.costUsd = r4(row.costUsd + cost); cumulative = r4(cumulative + cost);
      const next = t.passes[i + 1]; const codes = Array.from(new Set((p.errors || []).map((x) => x.code))); const text = p.strategy === "BASE_EF03B" || p.strategy === "INFORMED_REPAIR_V02" ? textOf(p.callId) : null;
      const pr = { pass: p.pass, strategy: p.strategy, promptChars: (() => { try { return json(path.join(runDir, "llm-cache", p.promptSha256 + ".request.json")).prompt.length; } catch (x) { return null; } })(), inputTokens: c.usage && c.usage.input_tokens, outputTokens: c.usage && c.usage.output_tokens, stopReason: c.stopReason || null, durationSec: c.startedAt ? Math.round(dur(c) * 10) / 10 : null, costUsd: r4(cost), valid: p.valid, errorsCount: (p.errors || []).length, errorCodes: codes, errorDimensions: Array.from(new Set((p.errors || []).map((x) => x.dimensionId).filter(Boolean))), targetedDimensions: p.targetedDimensions || [], exactRepeat: p.exactRepeat === true, attemptId: e.attemptId || null };
      /* taxonomie : une passe = une categorie principale */
      let cat = null; if (c.stopReason === "max_tokens") cat = "A"; else if (codes.length) cat = codeToCat(codes[0]); else if (p.valid && (c.usage && c.usage.output_tokens >= 7500)) cat = "K";
      if (cat) { pr.category = cat + ":" + CATS[cat]; tx(cat, cost, p.pass, next ? next.valid === true : (p.valid ? null : "terminal")); }
      /* verbosite / troncature : mesure sur la reponse brute (jamais copiee) */
      if (text) { const s = text.trim(); if (c.stopReason === "max_tokens") { const started = (s.match(/"dimensionId"\s*:\s*"/g) || []).length; const complete = (s.match(/"limitations"\s*:\s*\[[^\]]*\]\s*\}/g) || []).length; fieldStats.truncated.push({ twinId: t.twinId, pass: p.pass, chars: s.length, outputTokens: pr.outputTokens, findingsStarted: started, findingsComplete: complete }); pr.truncation = { findingsStarted: started, findingsComplete: complete, chars: s.length }; }
        else { const j = RE.extractJson(s); if (j.ok && Array.isArray(j.value.findings)) { const fs2 = j.value.findings; const L = (k, f) => typeof f[k] === "string" ? f[k].length : Array.isArray(f[k]) ? f[k].reduce((n, x) => n + String(x).length, 0) : 0; const avg = (k) => Math.round(fs2.reduce((n, f) => n + L(k, f), 0) / Math.max(1, fs2.length));
          fieldStats.complete.push({ twinId: t.twinId, pass: p.pass, valid: p.valid, chars: s.length, outputTokens: pr.outputTokens, findings: fs2.length, avgFinding: avg("finding"), avgRationale: avg("rationale"), avgRefsChars: avg("targetEvidenceRefs"), avgRefs: Math.round(10 * fs2.reduce((n, f) => n + (Array.isArray(f.targetEvidenceRefs) ? f.targetEvidenceRefs.length : 0), 0) / Math.max(1, fs2.length)) / 10, maxRefLen: Math.max.apply(null, fs2.map((f) => Math.max.apply(null, (Array.isArray(f.targetEvidenceRefs) ? f.targetEvidenceRefs : []).map((x) => String(x).length).concat([0])))), avgLimitations: avg("limitations") });
          /* sous-classes TARGET_REF_NOT_LITERAL (deterministe) */
          if (doc) fs2.forEach((f) => (Array.isArray(f.targetEvidenceRefs) ? f.targetEvidenceRefs : []).forEach((ref) => { if (typeof ref !== "string" || doc.content.indexOf(ref) !== -1) return; const cl = EF3.classifyNonLiteralRef(ref, doc.content); trnl.classes[cl.klass] = (trnl.classes[cl.klass] || 0) + 1; if (!trnl.examples[cl.klass]) trnl.examples[cl.klass] = { twinId: t.twinId, pass: p.pass, dimensionId: f.dimensionId, refPrefix: ref.slice(0, 100), exactSpanFound: cl.exactSpan ? cl.exactSpan.slice(0, 100) : null }; })); } } }
      row.passes.push(pr);
    });
    /* historique : reponses des tentatives precedentes (memes twin/target), statut de validation du magasin ; reconstruction du candidat accepte le cas echeant */
    const hist = calls.filter((x) => x.twinId === t.twinId && x.httpStatus === 200 && led[x.responseSha256] && led[x.responseSha256].attemptId < finalAttempt).sort((a, b) => (led[a.responseSha256].attemptId - led[b.responseSha256].attemptId) || (a.pass - b.pass));
    row.previousAttempts = hist.map((x) => ({ attemptId: led[x.responseSha256].attemptId, pass: x.pass, outputTokens: x.usage && x.usage.output_tokens, stopReason: x.stopReason || null, validationStatus: (store[x.responseSha256] || {}).validationStatus || null, costUsd: r4(led[x.responseSha256].cost.totalUsd), samePromptAsFinalPass1: x.pass === 1 ? (t.passes[0] && t.passes[0].promptSha256 === x.promptSha256) : null }));
    row.previousAttemptsCostUsd = r4(hist.reduce((n, x) => n + led[x.responseSha256].cost.totalUsd, 0));
    /* candidat VALID historique : re-validation HORS LIGNE avec le validateur gele + le parseur EF-03B gele (0 appel) */
    let parsed = null, cand = null;
    for (const x of hist) { const text = textOf(x.responseSha256); if (text == null) continue; let candidate = text; const j0 = RE.extractJson(text); const looksRepair = j0.ok && j0.value && Array.isArray(j0.value.repairs);   /* reponse de reparation ciblee (le JSON peut etre precede de prose) */
      if (looksRepair && parsed) { const rp = RE.parseRepair(text, parsed.findings.map((f) => f.dimensionId)); candidate = JSON.stringify(RE.recompose(parsed, rp.repairs || {})); }
      const v = twin && doc ? RE.validateReviewCandidate(candidate, twin, doc, schema) : { ok: false, errors: [] }; if (v.parsed && Array.isArray(v.parsed.findings)) parsed = v.parsed;
      if ((store[x.responseSha256] || {}).validationStatus === "VALID") { let frozenOk = null; if (v.ok) { try { F.M01.RR.parseReviewResponse(candidate, twin, doc, schema); frozenOk = true; } catch (e) { frozenOk = false; } } cand = { attemptId: led[x.responseSha256].attemptId, pass: x.pass, candidateSha256: sha(candidate), localValidNow: v.ok, localErrorsNow: v.errors.slice(0, 3).map((e) => e.code), frozenParserOkNow: frozenOk }; } }
    row.historicalValidCandidate = cand; row.reusableWithoutCall = rv.reviewStatus === "complete" ? "YES_FINAL_VALID" : (cand && cand.localValidNow && cand.frozenParserOkNow ? "YES_HISTORICAL_VALID_REVALIDATED_OFFLINE" : (cand ? "NO_EVIDENCE_CHANGED (" + cand.localErrorsNow.join(",") + ")" : "NO_NEVER_VALID"));
    row.basePromptSha256 = t.passes[0] && t.passes[0].promptSha256; perReview.push(row);
  }
  /* ---- 3. cout ---- */
  const byStrategy = {}; perReview.forEach((r) => r.passes.forEach((p) => { const s = byStrategy[p.strategy] = byStrategy[p.strategy] || { passes: 0, usd: 0, valid: 0, maxTokens: 0 }; s.passes++; s.usd = r4(s.usd + p.costUsd); if (p.valid) s.valid++; if (p.stopReason === "max_tokens") s.maxTokens++; }));
  const validR = perReview.filter((r) => r.finalStatus === "complete"), errR = perReview.filter((r) => r.finalStatus !== "complete");
  const avg = (a) => (a.length ? r4(a.reduce((n, x) => n + x, 0) / a.length) : null);
  const maxTokPasses = perReview.flatMap((r) => r.passes.filter((p) => p.stopReason === "max_tokens")); const fullRetries = perReview.flatMap((r) => r.passes.filter((p) => p.strategy === "INFORMED_REPAIR_V02")); const targeted = perReview.flatMap((r) => r.passes.filter((p) => /TARGETED/.test(p.strategy)));
  const cost = { finalAttempt, reviewsExpected: reviews.summary.reviewsExpected, reviewsValid: validR.length, reviewsError: errR.length, finalAttemptReviewCostUsd: r4(perReview.reduce((n, r) => n + r.costUsd, 0)), previousAttemptsReviewCostUsd: r4(perReview.reduce((n, r) => n + r.previousAttemptsCostUsd, 0)),
    avgCostValidReviewUsd: avg(validR.map((r) => r.costUsd)), avgCostErrorReviewUsd: avg(errR.map((r) => r.costUsd)), avgCostPerPassUsd: avg(perReview.flatMap((r) => r.passes.map((p) => p.costUsd))), byStrategy,
    maxTokensOutputs: { passes: maxTokPasses.length, usd: r4(maxTokPasses.reduce((n, p) => n + p.costUsd, 0)), avgDurationSec: avg(maxTokPasses.map((p) => p.durationSec)) }, fullRegenerations: { passes: fullRetries.length, usd: r4(fullRetries.reduce((n, p) => n + p.costUsd, 0)), validDirectly: fullRetries.filter((p) => p.valid).length, truncatedAgain: fullRetries.filter((p) => p.stopReason === "max_tokens").length },
    targetedRepairs: { passes: targeted.length, usd: r4(targeted.reduce((n, p) => n + p.costUsd, 0)), valid: targeted.filter((p) => p.valid).length, avgUsd: avg(targeted.map((p) => p.costUsd)), avgOutputTokens: avg(targeted.map((p) => p.outputTokens)) },
    previousAttemptsValidReviewsRecomputed: perReview.filter((r) => r.historicalValidCandidate).length, previousAttemptsValidRecomputationUsd: r4(perReview.filter((r) => r.historicalValidCandidate).reduce((n, r) => n + r.costUsd, 0)) };
  /* ---- 4. replay hors ligne ---- */
  const offlineRecoverable = errR.filter((r) => r.reusableWithoutCall === "YES_HISTORICAL_VALID_REVALIDATED_OFFLINE"); const remaining = errR.filter((r) => r.reusableWithoutCall !== "YES_HISTORICAL_VALID_REVALIDATED_OFFLINE");
  const unit = { pass1FullUsd: avg(perReview.flatMap((r) => r.passes.filter((p) => p.pass === 1).map((p) => p.costUsd))), completionUsd: cost.targetedRepairs.avgUsd, literalizationExcerptUsd: r4((3000 / 1e6) * 3 + (600 / 1e6) * 15), fullRegenUsd: avg(fullRetries.map((p) => p.costUsd)) };
  const lastCode = (r) => { const l = r.passes[r.passes.length - 1]; return l ? (l.stopReason === "max_tokens" ? "max_tokens" : (l.errorCodes[0] || "?")) : "?"; }; const remainingTrunc = remaining.filter((r) => lastCode(r) === "max_tokens"); const remainingTrnl = remaining.filter((r) => lastCode(r) === "TARGET_REF_NOT_LITERAL");   /* famille = cause TERMINALE de la revue */
  const replay = { schema: "EvidenceForge.EF03BReplay", schemaVersion: "MONOLITH-v1.0.13", runId: state.runId, generatedAt: new Date().toISOString(), providerCallsDuringReplay: 0,
    OLD: { reviewsExpected: cost.reviewsExpected, valid: cost.reviewsValid, error: cost.reviewsError, finalAttemptReviewCostUsd: cost.finalAttemptReviewCostUsd, allAttemptsReviewCostUsd: r4(cost.finalAttemptReviewCostUsd + cost.previousAttemptsReviewCostUsd), realCallsFinalAttempt: perReview.reduce((n, r) => n + r.passes.length, 0) },
    ACTUALLY_PROVEN: { validReviewsReusedAtZeroCost: validR.length, validReviewsReuseProof: "registre : cle = sha256 du prompt EF-03B de passe 1 (jumeau + preuves + document + schema) + sceau + contrat ; candidat accepte re-valide par le validateur gele et le parseur EF-03B gele (T-EF03B-11)",
      errorReviewsRecoverableOfflineFromHistoricalValid: offlineRecoverable.map((r) => ({ twinId: r.twinId, attemptId: r.historicalValidCandidate.attemptId, pass: r.historicalValidCandidate.pass, candidateSha256: r.historicalValidCandidate.candidateSha256 })), errorReviewsHistoricalValidButEvidenceChanged: errR.filter((r) => /NO_EVIDENCE_CHANGED/.test(r.reusableWithoutCall)).map((r) => ({ twinId: r.twinId, reason: r.reusableWithoutCall })),
      truncatedOutputsHadCompleteFindings: fieldStats.truncated.map((x) => x.findingsComplete), nonLiteralRefsDeterministicMapping: trnl.classes },
    SIMULATED: { candidatesForReplay: remaining.length, ofWhichTruncationFamily: remainingTrunc.length, ofWhichLiteralityFamily: remainingTrnl.length, terminalCauses: remaining.map((r) => ({ twinId: r.twinId, terminal: lastCode(r), historicalValid: !!r.historicalValidCandidate })), unitCostsUsd: unit,
      newMechanism: { pass1WithOutputBudget: "1 appel complet (max_tokens dimensionne au contrat)", truncationPath: "REVIEW_OUTPUT_TRUNCATED -> sauvetage structurel des findings complets + 1 appel de completion cible (dimensions manquantes seulement)", literalityPath: "1 appel de litteralisation sur EXTRAITS (spans exacts proposes de facon deterministe, choix du modele) ; sinon reparation ciblee gelee" },
      estimatedCallsRange: [remaining.length, remaining.length * 3], estimatedCostUsdRange: [r4(remaining.length * unit.pass1FullUsd), r4(remaining.length * (unit.pass1FullUsd + unit.completionUsd + unit.literalizationExcerptUsd))],
      oldCostForSameReviewsUsd: r4(remaining.reduce((n, r) => n + r.costUsd, 0)), fullRegenerationsAvoided: fullRetries.length, note: "estimation par unites MESUREES (passe 1, reparation ciblee) ; le taux de reussite des 8 revues n'est PAS invente : EXPECTED_NOT_YET_PROVEN" },
    EXPECTED_NOT_YET_PROVEN: { reviewsRequiringRealCalls: remaining.map((r) => r.twinId), theoreticalRecovery: "troncature : 8 a 9 findings sur 10 deja complets dans chaque sortie tronquee (completion de 1 a 2 dimensions) ; litteralite : " + r4(100 * ((trnl.classes.MARKDOWN_MARKERS_STRIPPED || 0) + (trnl.classes.WHITESPACE_LINEBREAK_ONLY || 0) + (trnl.classes.JOINED_LIST_ITEMS || 0)) / Math.max(1, Object.values(trnl.classes).reduce((a, b) => a + b, 0))) + " % des citations rejetees ont une correspondance exacte deterministe dans le document", realRunRequired: true } };
  return { perReview, taxonomy, fieldStats, trnl, cost, replay, dims, state: { status: state.status, attempts: state.attempts, counters: state.counters } };
}

function md(a) {
  const L = []; const R = a.perReview;
  L.push("# EF-03B REAL RUN AUTOPSY v1 — run `" + a.replay.runId + "` (lecture seule, 0 appel fournisseur)"); L.push(""); L.push("Généré le " + a.replay.generatedAt + " par `tools/ef03b-autopsy.js` (MONOLITH-v1.0.10). Tentative finale : " + a.cost.finalAttempt + " ; run " + a.state.status + " (" + a.state.attempts + " tentatives). Revues attendues " + a.cost.reviewsExpected + " · VALID " + a.cost.reviewsValid + " · ERROR " + a.cost.reviewsError + ". Aucun prompt ni réponse reproduits ; références publiques des professionnels seulement."); L.push("");
  L.push("## 1. Les 18 revues — passes de la tentative finale"); L.push(""); L.push("| # | twinId | professionnel | passe | stratégie | prompt (car.) | in | out | stop | durée (s) | USD | valid | erreurs (codes × n) | dimensions | cible réparation | résultat | réutilisable sans appel |"); L.push("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
  R.forEach((r, i) => r.passes.forEach((p, k) => L.push("| " + (k === 0 ? i + 1 : "") + " | " + (k === 0 ? r.twinId.replace("twin-", "") : "") + " | " + (k === 0 ? r.professionalRef : "") + " | " + p.pass + " | " + p.strategy + " | " + (p.promptChars || "?") + " | " + (p.inputTokens || "?") + " | " + (p.outputTokens || "?") + " | " + (p.stopReason || "—") + " | " + (p.durationSec != null ? p.durationSec : "—") + " | " + p.costUsd + " | " + (p.valid ? "VALID" : "INVALID") + " | " + (p.errorCodes.length ? p.errorCodes.join("+") + " × " + p.errorsCount : "—") + " | " + (p.errorDimensions.join(",") || "—") + " | " + (p.targetedDimensions.length ? p.targetedDimensions.join(",") : "—") + " | " + (k === r.passes.length - 1 ? (r.finalStatus === "complete" ? "**VALID** (passe " + r.acceptedPass + ", " + r.costUsd + " USD)" : "**ERROR** (" + r.costUsd + " USD)") : "") + " | " + (k === r.passes.length - 1 ? r.reusableWithoutCall : "") + " |")));
  L.push(""); L.push("## 2. Tentatives précédentes (mêmes jumeaux) — ce qui avait déjà été validé"); L.push(""); L.push("| twinId | tentatives précédentes (tentative/passe/out/stop/statut magasin) | USD précédents | candidat VALID historique | re-validation hors ligne (validateur gelé + parseur EF-03B gelé) | même prompt de passe 1 ? |"); L.push("|---|---|---|---|---|---|");
  R.forEach((r) => L.push("| " + r.twinId.replace("twin-", "") + " | " + (r.previousAttempts.map((x) => "t" + x.attemptId + "/p" + x.pass + "/" + x.outputTokens + "/" + (x.stopReason || "?") + "/" + (x.validationStatus || "?")).join(" ; ") || "—") + " | " + r.previousAttemptsCostUsd + " | " + (r.historicalValidCandidate ? "t" + r.historicalValidCandidate.attemptId + " p" + r.historicalValidCandidate.pass : "—") + " | " + (r.historicalValidCandidate ? (r.historicalValidCandidate.localValidNow && r.historicalValidCandidate.frozenParserOkNow ? "VALIDE aujourd'hui" : "REFUSÉ : " + r.historicalValidCandidate.localErrorsNow.join(",")) : "—") + " | " + (r.previousAttempts.some((x) => x.samePromptAsFinalPass1 === true) ? "oui" : (r.previousAttempts.some((x) => x.samePromptAsFinalPass1 === false) ? "NON (preuves du jumeau changées)" : "—")) + " |"));
  L.push(""); L.push("## 3. Volume des sorties (mesuré)"); L.push(""); L.push("Sorties TRONQUÉES (stop_reason=max_tokens) : " + a.fieldStats.truncated.length + " — findings commencés / complets : " + a.fieldStats.truncated.map((x) => x.findingsStarted + "/" + x.findingsComplete).join(", ") + " ; caractères " + Math.min.apply(null, a.fieldStats.truncated.map((x) => x.chars)) + "–" + Math.max.apply(null, a.fieldStats.truncated.map((x) => x.chars)) + "."); L.push("");
  L.push("| réponse complète (twin/passe) | valid | car. | jetons sortie | finding (car. moy.) | rationale | refs (car. moy. / nb moy. / max) | limitations |"); L.push("|---|---|---|---|---|---|---|---|"); a.fieldStats.complete.forEach((x) => L.push("| " + x.twinId.replace("twin-https://openalex.org/", "") + " p" + x.pass + " | " + (x.valid ? "VALID" : "INVALID") + " | " + x.chars + " | " + x.outputTokens + " | " + x.avgFinding + " | " + x.avgRationale + " | " + x.avgRefsChars + " / " + x.avgRefs + " / " + x.maxRefLen + " | " + x.avgLimitations + " |"));
  L.push(""); L.push("## 4. Citations rejetées (TARGET_REF_NOT_LITERAL) — sous-classes déterministes"); L.push(""); L.push("| classe | n | exemple (préfixe de citation → span exact trouvé) |"); L.push("|---|---|---|"); Object.keys(a.trnl.classes).sort((x, y) => a.trnl.classes[y] - a.trnl.classes[x]).forEach((k) => { const e = a.trnl.examples[k]; L.push("| " + k + " | " + a.trnl.classes[k] + " | " + (e ? "`" + e.refPrefix.replace(/\|/g, "¦") + "…` → " + (e.exactSpanFound ? "`" + e.exactSpanFound.replace(/\|/g, "¦") + "…`" : "aucun span unique") : "") + " |"); });
  return L.join("\n") + "\n";
}
function taxonomyMd(a) {
  const L = ["# EF-03B FAILURE TAXONOMY v1 — run `" + a.replay.runId + "`", "", "Une passe = une catégorie principale (première erreur ; `max_tokens` prime). « Récupérée à la passe suivante » = la passe suivante de la même revue a été VALID ; « terminale » = dernière passe de la revue, revue en ERROR.", "", "| Cat. | Nom | Cas (passes) | USD | Passes concernées | Récupérées à la passe suivante | Terminales | Correction déterministe possible ? | Correction par prompt ? | Impact scientifique |", "|---|---|---|---|---|---|---|---|---|---|"];
  const notes = { A: ["sauvetage STRUCTUREL des findings complets (framing JSON) + complétion des dimensions manquantes par le modèle ; max_tokens dimensionné au contrat", "budget de sortie explicite (longueurs par champ, ≤ 3 citations courtes, aucune prose)", "aucun (contenu manquant régénéré, findings complets conservés byte-identiques)"], B: ["idem A (même événement : troncature ⇒ JSON coupé)", "idem A", "aucun"], G: ["NON (jamais réparer une citation) ; DÉTECTION déterministe du span exact (Markdown/espaces) proposé comme feedback", "OUI : citer les octets bruts (marqueurs Markdown, puces, sauts de ligne inclus), une ligne, ≤ 200 caractères, jamais joindre des items", "aucun : le validateur reste byte-exact ; seule la forme de la citation change"], K: ["—", "budget de sortie", "aucun"], L: ["—", "—", "—"] };
  Object.keys(a.taxonomy).sort().forEach((k) => { const t = a.taxonomy[k]; const n = notes[k] || ["—", "—", "—"]; L.push("| " + k + " | " + t.name + " | " + t.cases + " | " + t.costUsd + " | " + Object.keys(t.passes).map((p) => "p" + p + ":" + t.passes[p]).join(" ") + " | " + t.recoveredAtNextPass + " | " + t.terminal + " | " + n[0] + " | " + n[1] + " | " + n[2] + " |"); });
  Object.keys(CATS).forEach((k) => { if (!a.taxonomy[k]) L.push("| " + k + " | " + CATS[k] + " | 0 | 0 | — | — | — | — | — | non observé |"); });
  L.push(""); L.push("Sous-classes de G (citations rejetées, déterministe) : " + Object.keys(a.trnl.classes).map((k) => k + " " + a.trnl.classes[k]).join(" · ")); return L.join("\n") + "\n";
}
function costMd(a) { const c = a.cost; const L = ["# EF-03B COST ANALYSIS v1 — run `" + a.replay.runId + "`", "", "| Mesure | Valeur |", "|---|---|"];
  [["revues attendues / VALID / ERROR", c.reviewsExpected + " / " + c.reviewsValid + " / " + c.reviewsError], ["coût EF-03B tentative finale (" + c.finalAttempt + ")", c.finalAttemptReviewCostUsd + " USD"], ["coût EF-03B tentatives précédentes (mêmes jumeaux)", c.previousAttemptsReviewCostUsd + " USD"], ["coût moyen d'une revue finalement VALID", c.avgCostValidReviewUsd + " USD"], ["coût moyen d'une revue finalement ERROR", c.avgCostErrorReviewUsd + " USD"], ["coût moyen par passe", c.avgCostPerPassUsd + " USD"], ["sorties max_tokens", c.maxTokensOutputs.passes + " passes, " + c.maxTokensOutputs.usd + " USD, durée moy. " + c.maxTokensOutputs.avgDurationSec + " s"], ["régénérations complètes (INFORMED_REPAIR_V02)", c.fullRegenerations.passes + " passes, " + c.fullRegenerations.usd + " USD, VALID directement : " + c.fullRegenerations.validDirectly + ", tronquées à nouveau : " + c.fullRegenerations.truncatedAgain], ["réparations ciblées (TARGETED_*)", c.targetedRepairs.passes + " passes, " + c.targetedRepairs.usd + " USD, VALID : " + c.targetedRepairs.valid + ", coût moyen " + c.targetedRepairs.avgUsd + " USD, sortie moy. " + c.targetedRepairs.avgOutputTokens + " jetons"], ["revues déjà VALID à une tentative précédente et recalculées à la tentative finale", c.previousAttemptsValidReviewsRecomputed + " revues, " + c.previousAttemptsValidRecomputationUsd + " USD"]].forEach((x) => L.push("| " + x[0] + " | " + x[1] + " |"));
  L.push(""); L.push("| stratégie | passes | USD | VALID | max_tokens |"); L.push("|---|---|---|---|---|"); Object.keys(c.byStrategy).forEach((k) => L.push("| " + k + " | " + c.byStrategy[k].passes + " | " + c.byStrategy[k].usd + " | " + c.byStrategy[k].valid + " | " + c.byStrategy[k].maxTokens + " |")); return L.join("\n") + "\n"; }
function replayMd(a) { const r = a.replay; const L = ["# EF-03B REPLAY v1 (hors ligne) — run `" + r.runId + "`", "", "0 appel fournisseur. Trois niveaux de preuve distingués.", "", "## OLD (mesuré)", "", "| attendues | VALID | ERROR | coût EF-03B tentative finale | coût EF-03B toutes tentatives | appels réels (tentative finale) |", "|---|---|---|---|---|---|", "| " + r.OLD.reviewsExpected + " | " + r.OLD.valid + " | " + r.OLD.error + " | " + r.OLD.finalAttemptReviewCostUsd + " USD | " + r.OLD.allAttemptsReviewCostUsd + " USD | " + r.OLD.realCallsFinalAttempt + " |", "", "## ACTUALLY_PROVEN (démontré hors ligne, déterministe)", "",
    "- " + r.ACTUALLY_PROVEN.validReviewsReusedAtZeroCost + " revues VALID réutilisées à coût 0 au replay (" + r.ACTUALLY_PROVEN.validReviewsReuseProof + ").", "- " + r.ACTUALLY_PROVEN.errorReviewsRecoverableOfflineFromHistoricalValid.length + " revue(s) en ERROR dont un candidat VALID d'une tentative précédente est **re-validé aujourd'hui** par le validateur gelé ET le parseur EF-03B gelé (0 appel) : " + r.ACTUALLY_PROVEN.errorReviewsRecoverableOfflineFromHistoricalValid.map((x) => x.twinId.replace("twin-", "") + " (t" + x.attemptId + " p" + x.pass + ")").join(", "), "- " + r.ACTUALLY_PROVEN.errorReviewsHistoricalValidButEvidenceChanged.length + " revue(s) en ERROR avec un candidat VALID historique **non réutilisable** (preuves du jumeau changées entre tentatives) : " + r.ACTUALLY_PROVEN.errorReviewsHistoricalValidButEvidenceChanged.map((x) => x.twinId.replace("twin-", "")).join(", "), "- sorties tronquées : findings complets par sortie = " + r.ACTUALLY_PROVEN.truncatedOutputsHadCompleteFindings.join(", ") + " (sur " + a.dims.length + ").", "- citations rejetées : correspondance exacte déterministe (Markdown / espaces / items joints) : " + JSON.stringify(r.ACTUALLY_PROVEN.nonLiteralRefsDeterministicMapping) + ".", "", "## SIMULATED (unités mesurées, mécanisme v1.0.10)", "",
    "| candidates au replay | famille troncature | famille littéralité | appels estimés | coût estimé | coût OLD des mêmes revues | régénérations complètes évitées |", "|---|---|---|---|---|---|---|", "| " + r.SIMULATED.candidatesForReplay + " | " + r.SIMULATED.ofWhichTruncationFamily + " | " + r.SIMULATED.ofWhichLiteralityFamily + " | " + r.SIMULATED.estimatedCallsRange.join("–") + " | " + r.SIMULATED.estimatedCostUsdRange.join("–") + " USD | " + r.SIMULATED.oldCostForSameReviewsUsd + " USD | " + r.SIMULATED.fullRegenerationsAvoided + " |", "", "Unités mesurées : passe 1 complète " + r.SIMULATED.unitCostsUsd.pass1FullUsd + " USD ; complétion / réparation ciblée " + r.SIMULATED.unitCostsUsd.completionUsd + " USD ; littéralisation sur extraits ≈ " + r.SIMULATED.unitCostsUsd.literalizationExcerptUsd + " USD ; régénération complète " + r.SIMULATED.unitCostsUsd.fullRegenUsd + " USD. " + r.SIMULATED.note, "", "## EXPECTED_NOT_YET_PROVEN", "", "- revues nécessitant des appels réels : " + r.EXPECTED_NOT_YET_PROVEN.reviewsRequiringRealCalls.map((x) => x.replace("twin-", "")).join(", "), "- récupération théorique : " + r.EXPECTED_NOT_YET_PROVEN.theoreticalRecovery, "- un run réel autorisé (après audit indépendant) reste requis pour prouver la réussite de ces revues."]; return L.join("\n") + "\n"; }

if (require.main === module) {
  const args = process.argv.slice(2); const runDir = args[0]; const oi = args.indexOf("--out"); const out = oi !== -1 ? args[oi + 1] : process.cwd();
  if (!runDir || !fs.existsSync(path.join(runDir, "enforcement-traces.json"))) { console.error("usage: node tools/ef03b-autopsy.js <runDir> --out <dossier>"); process.exit(2); }
  const a = analyse(path.resolve(runDir)); fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, "EF03B-REAL-RUN-AUTOPSY-v1.md"), md(a)); fs.writeFileSync(path.join(out, "EF03B-FAILURE-TAXONOMY-v1.json"), JSON.stringify({ schema: "EvidenceForge.EF03BFailureTaxonomy", runId: a.replay.runId, generatedAt: a.replay.generatedAt, categories: a.taxonomy, nonLiteralRefClasses: a.trnl.classes, examples: a.trnl.examples, outputVolume: a.fieldStats }, null, 2) + "\n"); fs.writeFileSync(path.join(out, "EF03B-FAILURE-TAXONOMY-v1.md"), taxonomyMd(a));
  fs.writeFileSync(path.join(out, "EF03B-COST-ANALYSIS-v1.json"), JSON.stringify(Object.assign({ schema: "EvidenceForge.EF03BCostAnalysis", runId: a.replay.runId, generatedAt: a.replay.generatedAt }, a.cost, { perReview: a.perReview.map((r) => ({ twinId: r.twinId, finalStatus: r.finalStatus, costUsd: r.costUsd, previousAttemptsCostUsd: r.previousAttemptsCostUsd, passes: r.passes.map((p) => ({ pass: p.pass, strategy: p.strategy, costUsd: p.costUsd, outputTokens: p.outputTokens, stopReason: p.stopReason, valid: p.valid, category: p.category || null })) })) }), null, 2) + "\n"); fs.writeFileSync(path.join(out, "EF03B-COST-ANALYSIS-v1.md"), costMd(a));
  fs.writeFileSync(path.join(out, "EF03B-REPLAY-v1.json"), JSON.stringify(a.replay, null, 2) + "\n"); fs.writeFileSync(path.join(out, "EF03B-REPLAY-v1.md"), replayMd(a));
  console.log("autopsie EF-03B ecrite dans " + out + " (appels fournisseur : 0) — revues " + a.cost.reviewsValid + " VALID / " + a.cost.reviewsError + " ERROR ; recuperables hors ligne : " + a.replay.ACTUALLY_PROVEN.errorReviewsRecoverableOfflineFromHistoricalValid.length);
}
module.exports = { analyse, CATS, codeToCat };
