"use strict";
/**
 * EvidenceForge MONOLITH v1.0.11 — test/test-ef03b.js : EF-03B REVIEW RESILIENCE (T-EF03B-01…25) + v1.0.11 LINEAGE PRESERVATION (T-EF03B-27…35, test/test-ef03b-lineage.js).
 * Charge par test/test-monolith.js. Aucun reseau, aucun fournisseur : le lot gele MONO-11 (review-enforcer, runEnforcedReview) et le
 * parseur EF-03B gele (MONO-01) sont executes REELLEMENT, avec l'adaptateur v1.0.10 branche sur un LLM factice scripte. Les fixtures
 * reproduisent les familles d'echec du run reel : sortie tronquee (stop_reason=max_tokens, 9 findings complets sur 10), citations
 * non litterales (marqueurs Markdown retires, items de liste joints), derive de schema, dimension dupliquee, cle absente, enum invalide.
 * Aucun nom de cas, aucune constante de mission, aucun secret.
 */
const fs = require("fs"), path = require("path");
module.exports = async function (h) {
  const { T, assert, tmp, sha, P, ROOT } = h;
  const EF3 = require("../lib/ef03b-resilience.js"); const SP = require("../lib/stage-professionals.js"); const EP = require("../lib/economic-panel.js");
  const RE = require(path.join(P.MONO11, "core", "review-enforcer.js")); const { F } = SP.loadSealedMono11();
  console.log("\n— v1.0.10 : EF-03B REVIEW RESILIENCE —");
  /* ---- fixtures generiques ---- */
  const DIMS = ["DIM-01", "DIM-02", "DIM-03"];
  const DOC = "# Fiche de recueil\n\nIntroduction generale du document cible.\n\n**Attention :** ne pas transformer ces distinctions en categories definitives.\n\n3. Faut-il demander ce qui est :\n   - difficile ;\n   - impossible ;\n   - evite ;\n   - seulement inconfortable ?\n\nLa fiche permet de recueillir librement les activites realisees.\n\n- [ ] Oui\n- [ ] Non\n\nConclusion : la structure reste prudente et generique.\n";
  const mkDoc = (content) => ({ targetId: "target-01", label: "Document", role: "review_target_not_evidence", content: content || DOC, sourceDocumentRef: sha(content || DOC) });
  const mkTwin = (i, works) => ({ twinId: "twin-" + i, professionalRef: "pro-" + i, referenceIdentity: { displayName: "Professionnel " + i }, documentaryBasis: { worksUsed: (works || ["Work A " + i, "Work B " + i]).map((w) => ({ workRef: w, title: w })), dimensionCoverage: {} } });
  const schema = { schema: "EvidenceForge.ReviewSchema", schemaVersion: "EF-03A-v1", stage: "EF-03A", missionQuestion: "Question de mission de test.", dimensions: DIMS.map((id, i) => ({ id, label: "Dimension " + (i + 1), definition: "Definition de la dimension " + (i + 1) + "." })), reviewTargets: [{ targetId: "target-01" }], schemaHash: sha("schema") };
  const finding = (id, over) => Object.assign({ dimensionId: id, disposition: "support", epistemicStatus: "documented", finding: "Constat pour " + id + ".", rationale: "Justification pour " + id + ".", targetEvidenceRefs: ["La fiche permet de recueillir librement les activites realisees."], twinBasisWorkRefs: ["Work A 1"], confidenceQualitative: "medium", limitations: ["Limite " + id] }, over || {});
  const validJson = (twinIdx, over) => JSON.stringify({ findings: DIMS.map((id) => finding(id, Object.assign({ twinBasisWorkRefs: ["Work A " + twinIdx] }, over && over[id] ? over[id] : {}))) });
  const truncate = (json, dimsComplete) => { /* coupe la sortie apres `dimsComplete` findings complets, au milieu du suivant (comme les sorties reelles a max_tokens) */ const o = JSON.parse(json); const kept = o.findings.slice(0, dimsComplete); const next = o.findings[dimsComplete]; const s = JSON.stringify({ findings: kept }); return s.slice(0, -2) + "," + JSON.stringify(next).slice(0, 60); };
  /** LLM factice : handler(prompt, meta, n) -> { text, stopReason?, usage? } ; journal des appels, validations, reuses */
  function fakeLlm(handler) { const calls = [], validations = [], reuses = []; let n = 0;
    return { calls, validations, reuses, model: "fake-model", async llmCall(prompt, meta) { n++; const r = await handler(prompt, meta, n); if (r instanceof Error) throw r; calls.push({ prompt, meta, text: r.text, stopReason: r.stopReason || "end_turn" }); return { text: r.text, callId: "c" + n + "-" + sha(r.text).slice(0, 12), providerRequestId: "fake-" + n, modelId: "fake-model", providerId: "fake", usage: r.usage || { input_tokens: Math.round(prompt.length / 4), output_tokens: Math.round(r.text.length / 4) }, stopReason: r.stopReason || "end_turn", reused: false }; },
      onValidation(v) { validations.push(v); }, recordReuse(i) { reuses.push(i); }, counts: () => ({ real: calls.length, reused: reuses.length }) }; }
  const run = async (llm, twin, opts) => { const d = (opts && opts.runDir) || tmp(); const adapter = EF3.createReviewAdapter(Object.assign({ llm, runDir: d, runId: "t", attemptId: 1, sealHash: "s".repeat(64), config: { maxTokens: 12288 }, twinsTotal: () => 18 }, opts || {})); const r = await RE.runEnforcedReview({ frozen: F, twin, targetDoc: mkDoc(), reviewSchema: schema, llmCall: adapter.llmCall, maxPasses: 3, onValidation: adapter.onValidation, runId: "t" }); return { r, adapter, dir: d, trace: fs.existsSync(path.join(d, EF3.TRACE_FILE)) ? fs.readFileSync(path.join(d, EF3.TRACE_FILE), "utf8").trim().split("\n").map(JSON.parse) : [] }; };
  const isReviewMeta = (m) => m && m.purpose === "EF-03B review";

  await T("T-EF03B-01", "reponse valide du premier coup : acceptee par le lot gele a la passe 1 ; 1 appel reel ; budget de sortie et max_tokens dimensionne presents ; registre alimente apres validation ; trace VALIDATED avec tous les champs", async () => {
    const llm = fakeLlm(() => ({ text: validJson(1) })); const { r, adapter, trace } = await run(llm, mkTwin(1));
    assert(r.review.reviewStatus === "complete" && r.trace.acceptedPass === 1 && llm.calls.length === 1, JSON.stringify(r.review.error)); assert(/CONTRAT DE BUDGET DE SORTIE/.test(llm.calls[0].prompt) && llm.calls[0].meta.maxTokens === 12288 && llm.calls[0].meta.purpose === "EF-03B review", "budget + max_tokens");
    const st = adapter.stats(); assert(st.realCalls === 1 && st.validated === 1 && st.registryReuses === 0 && adapter.registry.list().length === 1 && adapter.registry.list()[0].candidateSha256 === sha(validJson(1)), JSON.stringify(st));
    const v = trace.find((t) => t.state === "VALIDATED"); assert(v && ["reviewPass", "maxPasses", "strategy", "costUsd", "cumulativeReviewCostUsd", "validationErrorsCount", "validationErrorCodes", "twinId", "reviewIndex", "twinsTotal"].every((k) => k in v), JSON.stringify(v)); const p = trace[0]; assert(["stopReason", "inputTokens", "outputTokens", "repairScope", "reusedFieldsCount", "regeneratedFieldsCount"].every((k) => k in p || p[k] === undefined) && p.stopReason === "end_turn" && p.inputTokens > 0, JSON.stringify(p)); });

  await T("T-EF03B-02", "stop_reason=max_tokens => statut REVIEW_OUTPUT_TRUNCATED (jamais soumis tel quel comme complet) ; la reponse brute tronquee est marquee INVALID pour le reuse ; une completion ciblee est demandee pour les seules dimensions manquantes", async () => {
    const full = validJson(1); const llm = fakeLlm((prompt, meta) => meta.strategy === "TRUNCATION_COMPLETION" ? { text: JSON.stringify({ findings: [JSON.parse(full).findings[2]] }) } : { text: truncate(full, 2), stopReason: "max_tokens", usage: { input_tokens: 49000, output_tokens: 8192 } });
    const { r, adapter, trace } = await run(llm, mkTwin(1)); assert(r.review.reviewStatus === "complete" && r.trace.acceptedPass === 1, JSON.stringify(r.review.error));
    assert(trace.some((t) => t.state === EF3.REVIEW_OUTPUT_TRUNCATED && t.stopReason === "max_tokens" && t.outputTokens === 8192), "statut tronque"); const c = llm.calls[1]; assert(llm.calls.length === 2 && c.meta.purpose === "EF-03B review completion" && c.meta.strategy === "TRUNCATION_COMPLETION" && JSON.stringify(c.meta.repairScope) === JSON.stringify(["DIM-03"]) && /COMPLETION CIBLEE/.test(c.prompt) && /DIM-03/.test(c.prompt), JSON.stringify(c.meta));
    assert(llm.validations.some((v) => v.valid === false && v.errors && v.errors[0] === EF3.REVIEW_OUTPUT_TRUNCATED && v.callId === "c1-" + sha(truncate(full, 2)).slice(0, 12)), "brut tronque marque invalide"); assert(adapter.stats().truncations === 1 && adapter.stats().completions === 1, JSON.stringify(adapter.stats())); });

  await T("T-EF03B-03", "JSON tronque => aucune validation scientifique du texte tronque : si la completion echoue, le candidat reste incomplet (DIMENSION_MISSING) et le lot gele enchaine sa reprise ; rien de partiel n'est accepte ni inscrit au registre", async () => {
    const full = validJson(1); const llm = fakeLlm((prompt, meta, n) => meta.strategy === "TRUNCATION_COMPLETION" ? { text: "{\"findings\":[{\"dimensionId\":\"DIM-03\",\"disposition\":\"support\"" /* completion elle-meme illisible */ } : (n <= 2 ? { text: truncate(full, 2), stopReason: "max_tokens" } : { text: full }));
    const { r, adapter, trace } = await run(llm, mkTwin(1)); assert(r.review.reviewStatus === "complete" && r.trace.acceptedPass === 2, "accepte a la passe 2 (reprise gelee) : " + JSON.stringify(r.trace.acceptedPass));
    const p1 = r.trace.passes[0]; assert(p1.valid === false && p1.errorCodes.some((c) => /CARDINALITY|DIMENSION_MISSING/.test(c)), "passe 1 refusee pour dimension manquante, jamais pour un JSON accepte partiel : " + JSON.stringify(p1.errorCodes)); assert(adapter.registry.list().length === 1 && adapter.registry.list()[0].candidateSha256 === sha(full) && trace.filter((t) => t.state === "VALIDATED").length === 1, "registre : seul le candidat complet"); });

  await T("T-EF03B-04", "un seul champ invalide (targetEvidenceRefs d'une dimension, marqueur Markdown retire) => reprise CIBLEE sur extraits : 1 appel de litteralisation (repairScope = la dimension), span exact propose, acceptee a la passe 1 ; aucune regeneration complete", async () => {
    const bad = validJson(1, { "DIM-02": { targetEvidenceRefs: ["Attention : ne pas transformer ces distinctions en categories definitives."] } });
    const llm = fakeLlm((prompt, meta) => meta.strategy === "LITERALIZATION_EXCERPTS" ? { text: "{\"repairs\":[{\"dimensionId\":\"DIM-02\",\"targetEvidenceRefs\":[" + JSON.stringify(/passage exact localise \(a copier tel quel\) : (".*?")\n/.exec(prompt)[1].replace(/^"|"$/g, "").replace(/\\"/g, "\"")) + "]}]}" } : { text: bad });
    const { r, adapter } = await run(llm, mkTwin(1), { config: { maxTokens: 12288, excerptChars: 40 } }); assert(r.review.reviewStatus === "complete" && r.trace.acceptedPass === 1 && llm.calls.length === 2, JSON.stringify([r.review.error, llm.calls.length]));
    const c = llm.calls[1]; assert(c.meta.purpose === "EF-03B review literalization" && JSON.stringify(c.meta.repairScope) === JSON.stringify(["DIM-02"]) && /EXTRAIT DU DOCUMENT/.test(c.prompt) && c.prompt.length < DOC.length + 2500 && !/Introduction generale/.test(c.prompt), "extraits seulement, pas le document entier : " + c.prompt.length);
    assert(r.review.findings.find((f) => f.dimensionId === "DIM-02").targetEvidenceRefs[0] === "Attention :** ne pas transformer ces distinctions en categories definitives." && adapter.stats().literalizations === 1, JSON.stringify(r.review.findings[1].targetEvidenceRefs)); });

  await T("T-EF03B-05", "une seule dimension invalide (tronquee) => seule cette dimension est regeneree : reusedFieldsCount = 2, regeneratedFieldsCount = 1, repairScope = [DIM-03]", async () => {
    const full = validJson(2); const llm = fakeLlm((prompt, meta) => meta.strategy === "TRUNCATION_COMPLETION" ? { text: JSON.stringify({ findings: [JSON.parse(full).findings[2]] }) } : { text: truncate(full, 2), stopReason: "max_tokens" });
    const { r, trace } = await run(llm, mkTwin(2)); const c = trace.find((t) => t.strategy === "TRUNCATION_COMPLETION"); assert(r.review.reviewStatus === "complete" && c && c.reusedFieldsCount === 2 && c.regeneratedFieldsCount === 1 && JSON.stringify(c.repairScope) === JSON.stringify(["DIM-03"]) && c.salvagedFindings === 2, JSON.stringify(c)); });

  await T("T-EF03B-06", "elements deja valides conserves BYTE-IDENTIQUES apres completion et apres litteralisation (findings non concernes : meme JSON canonique)", async () => {
    const full = validJson(3); const kept = JSON.parse(full).findings.slice(0, 2).map((f) => JSON.stringify(f)); const llm = fakeLlm((prompt, meta) => meta.strategy === "TRUNCATION_COMPLETION" ? { text: JSON.stringify({ findings: [JSON.parse(full).findings[2]] }) } : { text: truncate(full, 2), stopReason: "max_tokens" });
    const { adapter } = await run(llm, mkTwin(3)); const cand = JSON.parse(adapter.registry.list()[0].candidate); assert(cand.findings.slice(0, 2).map((f) => JSON.stringify(f)).join("|") === kept.join("|"), "byte-identiques");
    const bad = validJson(3, { "DIM-02": { targetEvidenceRefs: ["Attention : ne pas transformer ces distinctions en categories definitives."] } }); const before = JSON.parse(bad).findings; const llm2 = fakeLlm((prompt, meta) => meta.strategy === "LITERALIZATION_EXCERPTS" ? { text: "{\"repairs\":[{\"dimensionId\":\"DIM-02\",\"targetEvidenceRefs\":[\"Attention :** ne pas transformer ces distinctions en categories definitives.\"]}]}" } : { text: bad });
    const { adapter: a2 } = await run(llm2, mkTwin(3)); const c2 = JSON.parse(a2.registry.list()[0].candidate); assert(JSON.stringify(c2.findings[0]) === JSON.stringify(before[0]) && JSON.stringify(c2.findings[2]) === JSON.stringify(before[2]), "dimensions non fautives intactes"); });

  await T("T-EF03B-07", "fusion deterministe : mergeFindings est pure (meme entree => meme sortie), ordre du schema, dimensions inconnues ignorees, jamais un doublon", () => {
    const a = [finding("DIM-01"), finding("DIM-03")], b = [finding("DIM-02", { finding: "X" }), finding("DIM-03", { finding: "DOUBLON" }), finding("DIM-09")];
    const m1 = EF3.mergeFindings(a, b, DIMS), m2 = EF3.mergeFindings(a, b, DIMS); assert(JSON.stringify(m1) === JSON.stringify(m2) && m1.findings.map((f) => f.dimensionId).join(",") === "DIM-01,DIM-02,DIM-03" && m1.findings[2].finding !== "DOUBLON" && JSON.stringify(m1.regeneratedDims) === JSON.stringify(["DIM-02"]) && m1.reusedDims.length === 2 && m1.missingDims.length === 0, JSON.stringify(m1));
    const s = EF3.salvageTruncatedFindings(truncate(validJson(1), 2), DIMS); assert(s.complete.length === 2 && JSON.stringify(s.missingDims) === JSON.stringify(["DIM-03"]) && JSON.stringify(EF3.salvageTruncatedFindings(truncate(validJson(1), 2), DIMS)) === JSON.stringify(s), "sauvetage deterministe"); });

  await T("T-EF03B-08", "aucune perte de provenance : targetEvidenceRefs / twinBasisWorkRefs des findings conserves inchanges ; findings regeneres valides par le parseur gele (citations et references verifiees) ; registre porte sceau, contrat, twin, cible, cle de prompt", async () => {
    const full = validJson(4); const llm = fakeLlm((prompt, meta) => meta.strategy === "TRUNCATION_COMPLETION" ? { text: JSON.stringify({ findings: [JSON.parse(full).findings[2]] }) } : { text: truncate(full, 2), stopReason: "max_tokens" });
    const { r, adapter } = await run(llm, mkTwin(4)); const o = JSON.parse(full).findings; r.review.findings.forEach((f, i) => assert(JSON.stringify(f.targetEvidenceRefs) === JSON.stringify(o[i].targetEvidenceRefs) && JSON.stringify(f.twinBasisWorkRefs) === JSON.stringify(o[i].twinBasisWorkRefs), f.dimensionId));
    const e = adapter.registry.list()[0]; assert(e.sourceSealHash === "s".repeat(64) && e.validationContract === "MONO-11-v2" && e.twinId === "twin-4" && e.targetId === "target-01" && /^[a-f0-9]{64}$/.test(e.basePromptSha256) && e.candidateSha256 === sha(e.candidate), JSON.stringify(Object.keys(e))); });

  await T("T-EF03B-09", "aucune modification silencieuse du sens : la litteralisation ne change que targetEvidenceRefs des dimensions fautives ; disposition / epistemicStatus / finding / rationale / limitations intacts ; jamais applique localement (le modele choisit ; [] accepte)", async () => {
    const bad = validJson(5, { "DIM-01": { targetEvidenceRefs: ["Faut-il demander ce qui est : difficile ; impossible ; evite ; seulement inconfortable ?"] } }); const before = JSON.parse(bad).findings;
    const llm = fakeLlm((prompt, meta) => meta.strategy === "LITERALIZATION_EXCERPTS" ? { text: "{\"repairs\":[{\"dimensionId\":\"DIM-01\",\"targetEvidenceRefs\":[]}]}" } : { text: bad }); const { r } = await run(llm, mkTwin(5));
    assert(r.review.reviewStatus === "complete" && r.trace.acceptedPass === 1, JSON.stringify(r.review.error)); const f = r.review.findings[0]; assert(JSON.stringify(f.targetEvidenceRefs) === "[]" && f.finding === before[0].finding && f.rationale === before[0].rationale && f.disposition === before[0].disposition && f.epistemicStatus === before[0].epistemicStatus && JSON.stringify(f.limitations) === JSON.stringify(before[0].limitations), "seul le champ cible a change, par choix du modele");
    assert(/JOINED_LIST_ITEMS/.test(JSON.stringify(EF3.classifyNonLiteralRef(before[0].targetEvidenceRefs[0], DOC))) && /passage exact localise/.test(llm.calls[1].prompt), "span exact propose, non impose"); assert(/CONTEXTE DE REPARATION .*jumeau="twin-5" .*empreinte=[a-f0-9]{64}/.test(llm.calls[1].prompt) && /^[a-f0-9]{64}$/.test(llm.calls[1].meta.repairContextFingerprint), "empreinte de contexte deterministe (jamais reutilisable pour un autre constat)"); });

  await T("T-EF03B-10", "3 echecs => fail-closed INCHANGE du lot gele : reviewStatus error, aucun candidat partiel accepte, registre vide, passes = 3, aucune 4e passe", async () => {
    const llm = fakeLlm((prompt, meta, n) => meta.strategy === "TRUNCATION_COMPLETION" ? { text: "pas de json" } : { text: truncate(validJson(6, { "DIM-01": { finding: "Variante " + n } }), 2), stopReason: "max_tokens" }); const { r, adapter } = await run(llm, mkTwin(6));   /* sorties tronquees differentes a chaque passe, comme en reel */
    assert(r.review.reviewStatus === "error" && r.trace.passes.length === 3 && r.trace.acceptedPass === null && r.review.findings.length === 0 && /validation locale refusee apres 3 passe/.test(r.review.error), JSON.stringify([r.review.error, r.trace.passes.length])); assert(adapter.registry.list().length === 0 && adapter.stats().validated === 0 && llm.calls.filter((c) => isReviewMeta(c.meta) || /informed-retry/.test(c.meta.purpose)).length === 3, "aucune acceptation partielle"); });

  await T("T-EF03B-11", "10 VALID existantes au registre => 0 appel reel : chaque revue servie par le registre, re-validee par le lot gele, journalisee comme reutilisation (recordReuse), acceptee a la passe 1", async () => {
    const dir = tmp(); const reg = EF3.createReviewRegistry({ runDir: dir }); const twins = Array.from({ length: 10 }, (_, i) => mkTwin(100 + i));
    twins.forEach((tw) => { const cand = validJson(tw.twinId.replace("twin-", "")); const basePrompt = F.M01.RR.buildReviewPrompt(tw, mkDoc(), schema) + RE.enforcementPreamble(schema); reg.put({ basePromptSha256: sha(basePrompt), twinId: tw.twinId, targetId: "target-01", runId: "t", candidateSha256: sha(cand), candidate: cand, validationContract: "MONO-11-v2", sourceSealHash: "s".repeat(64), source: "TEST" }); });
    const llm = fakeLlm(() => new Error("AUCUN APPEL REEL ATTENDU")); let ok = 0; const adapter = EF3.createReviewAdapter({ llm, runDir: dir, runId: "t", attemptId: 2, sealHash: "s".repeat(64) });
    for (const tw of twins) { const r = await RE.runEnforcedReview({ frozen: F, twin: tw, targetDoc: mkDoc(), reviewSchema: schema, llmCall: adapter.llmCall, maxPasses: 3, onValidation: adapter.onValidation }); if (r.review.reviewStatus === "complete" && r.trace.acceptedPass === 1) ok++; }
    assert(ok === 10 && llm.calls.length === 0 && llm.reuses.length === 10 && adapter.stats().registryReuses === 10 && adapter.stats().realCalls === 0, JSON.stringify([ok, llm.calls.length, llm.reuses.length])); });

  await T("T-EF03B-12", "10 VALID + 8 non VALID => appels uniquement pour les 8 (passe 1 chacune), 0 pour les 10 ; sceau different => pas de reuse (re-calcul)", async () => {
    const dir = tmp(); const reg = EF3.createReviewRegistry({ runDir: dir }); const valid = Array.from({ length: 10 }, (_, i) => mkTwin(200 + i)), invalid = Array.from({ length: 8 }, (_, i) => mkTwin(300 + i));
    valid.forEach((tw) => { const cand = validJson(tw.twinId.replace("twin-", "")); reg.put({ basePromptSha256: sha(F.M01.RR.buildReviewPrompt(tw, mkDoc(), schema) + RE.enforcementPreamble(schema)), twinId: tw.twinId, targetId: "target-01", runId: "t", candidateSha256: sha(cand), candidate: cand, validationContract: "MONO-11-v2", sourceSealHash: "s".repeat(64), source: "TEST" }); });
    const llm = fakeLlm((prompt, meta) => ({ text: validJson(meta.twinId.replace("twin-", "")) })); const adapter = EF3.createReviewAdapter({ llm, runDir: dir, runId: "t", attemptId: 2, sealHash: "s".repeat(64) }); let complete = 0;
    for (const tw of valid.concat(invalid)) { const r = await RE.runEnforcedReview({ frozen: F, twin: tw, targetDoc: mkDoc(), reviewSchema: schema, llmCall: adapter.llmCall, maxPasses: 3, onValidation: adapter.onValidation }); if (r.review.reviewStatus === "complete") complete++; }
    assert(complete === 18 && llm.calls.length === 8 && llm.calls.every((c) => /^twin-3/.test(c.meta.twinId) && c.meta.pass === 1) && adapter.stats().registryReuses === 10, JSON.stringify([complete, llm.calls.length, llm.calls.map((c) => c.meta.twinId)]));
    const llm2 = fakeLlm((prompt, meta) => ({ text: validJson(meta.twinId.replace("twin-", "")) })); const a2 = EF3.createReviewAdapter({ llm: llm2, runDir: dir, runId: "t", attemptId: 3, sealHash: "x".repeat(64) }); await RE.runEnforcedReview({ frozen: F, twin: valid[0], targetDoc: mkDoc(), reviewSchema: schema, llmCall: a2.llmCall, maxPasses: 3, onValidation: a2.onValidation }); assert(llm2.calls.length === 1, "sceau different => aucune reutilisation"); });

  await T("T-EF03B-13", "redemarrage apres interruption : les revues validees avant l'interruption (registre ecrit a chaque validation, avant tout checkpoint) sont reutilisees a 0 appel par un nouvel adaptateur (nouvelle tentative)", async () => {
    const dir = tmp(); const twins = [mkTwin(11), mkTwin(12), mkTwin(13)]; const llm = fakeLlm((prompt, meta, n) => n === 3 ? Object.assign(new Error("PROVIDER_STREAM_INTERRUPTED"), { code: "PROVIDER_STREAM_INTERRUPTED", fatal: true }) : { text: validJson(meta.twinId.replace("twin-", "")) });
    const a1 = EF3.createReviewAdapter({ llm, runDir: dir, runId: "t", attemptId: 1, sealHash: "s".repeat(64) }); let interrupted = false; for (const tw of twins) { try { await RE.runEnforcedReview({ frozen: F, twin: tw, targetDoc: mkDoc(), reviewSchema: schema, llmCall: a1.llmCall, maxPasses: 3, onValidation: a1.onValidation }); } catch (e) { interrupted = e.code === "PROVIDER_STREAM_INTERRUPTED"; break; } }
    assert(interrupted && a1.registry.list().length === 2, "2 revues validees avant l'interruption : " + a1.registry.list().length);
    const llm2 = fakeLlm((prompt, meta) => ({ text: validJson(meta.twinId.replace("twin-", "")) })); const a2 = EF3.createReviewAdapter({ llm: llm2, runDir: dir, runId: "t", attemptId: 2, sealHash: "s".repeat(64) }); let complete = 0; for (const tw of twins) { const r = await RE.runEnforcedReview({ frozen: F, twin: tw, targetDoc: mkDoc(), reviewSchema: schema, llmCall: a2.llmCall, maxPasses: 3, onValidation: a2.onValidation }); if (r.review.reviewStatus === "complete") complete++; }
    assert(complete === 3 && llm2.calls.length === 1 && llm2.calls[0].meta.twinId === "twin-13" && a2.stats().registryReuses === 2, JSON.stringify([complete, llm2.calls.map((c) => c.meta.twinId)])); });

  await T("T-EF03B-14", "TARGET_REF_NOT_LITERAL reproduit (famille reelle : marqueurs Markdown retires, items de liste joints, espaces / sauts de ligne, case a cocher) et repare selon contrat : classification deterministe, span EXACT present dans le document ; paraphrase => aucun span, reparation ciblee gelee inchangee", () => {
    const c1 = EF3.classifyNonLiteralRef("Attention : ne pas transformer ces distinctions en categories definitives.", DOC); assert(c1.klass === "MARKDOWN_MARKERS_STRIPPED" && DOC.indexOf(c1.exactSpan) !== -1 && c1.unique, JSON.stringify(c1));
    const c2 = EF3.classifyNonLiteralRef("Faut-il demander ce qui est : difficile ; impossible ; evite ; seulement inconfortable ?", DOC); assert(c2.klass === "JOINED_LIST_ITEMS" && DOC.indexOf(c2.exactSpan) !== -1 && /\n   - difficile/.test(c2.exactSpan), JSON.stringify(c2));
    const c3 = EF3.classifyNonLiteralRef("la structure   reste\nprudente et generique", DOC); assert(c3.klass === "WHITESPACE_LINEBREAK_ONLY" && DOC.indexOf(c3.exactSpan) !== -1, JSON.stringify(c3)); const c4 = EF3.classifyNonLiteralRef("Oui Non", DOC); assert(c4.klass === "JOINED_LIST_ITEMS" && DOC.indexOf(c4.exactSpan) !== -1, JSON.stringify(c4));
    const c5 = EF3.classifyNonLiteralRef("Le document affirme une prudence exemplaire.", DOC); assert(c5.klass === "PARAPHRASE_OR_ABSENT" && c5.exactSpan === null, JSON.stringify(c5)); assert(EF3.classifyNonLiteralRef("Conclusion : la structure reste prudente et generique.", DOC).klass === "LITERAL", "litteral");
    const src = fs.readFileSync(path.join(ROOT, "lib", "ef03b-resilience.js"), "utf8"); assert(/jamais applique localement/.test(src) && !/targetEvidenceRefs\s*=\s*\[?\s*exactSpan/.test(src), "aucune reparation locale d'une citation dans la source"); });

  const enforcerPath = async (name, badOver, expectCodes) => { const bad = validJson(7, badOver); const llm = fakeLlm((p, meta, n) => (n === 1 ? { text: bad } : { text: validJson(7) })); const { r, adapter } = await run(llm, mkTwin(7));
    assert(r.review.reviewStatus === "complete" && r.trace.acceptedPass === 2 && r.trace.passes[0].valid === false && r.trace.passes[0].errorCodes.some((c) => expectCodes.indexOf(c) !== -1) && r.trace.passes[1].strategy === "INFORMED_REPAIR_V02" && llm.calls.length === 2 && adapter.stats().literalizations === 0 && adapter.stats().completions === 0, name + " : " + JSON.stringify([r.trace.acceptedPass, r.trace.passes[0].errorCodes, llm.calls.length])); };
  await T("T-EF03B-15", "SCHEMA_DRIFT (cle non prevue) reproduit : refuse par le validateur gele, traite par la reprise informee gelee (passe 2), l'adaptateur n'intervient pas (ni completion ni litteralisation)", () => enforcerPath("drift", { "DIM-01": { extraField: "x" } }, ["EXTRA_KEY"]));
  await T("T-EF03B-16", "dimension dupliquee : refusee (DIMENSION_DUPLICATE / CARDINALITY), reprise gelee inchangee", async () => { const dup = JSON.parse(validJson(7)); dup.findings[2] = Object.assign({}, dup.findings[1]); const llm = fakeLlm((p, m, n) => (n === 1 ? { text: JSON.stringify(dup) } : { text: validJson(7) })); const { r } = await run(llm, mkTwin(7)); assert(r.trace.acceptedPass === 2 && r.trace.passes[0].errorCodes.indexOf("DIMENSION_DUPLICATE") !== -1, JSON.stringify(r.trace.passes[0].errorCodes)); });
  await T("T-EF03B-17", "champ obligatoire absent (rationale) : MISSING_KEY, reprise gelee inchangee", async () => { const o = JSON.parse(validJson(7)); delete o.findings[0].rationale; const llm = fakeLlm((p, m, n) => (n === 1 ? { text: JSON.stringify(o) } : { text: validJson(7) })); const { r } = await run(llm, mkTwin(7)); assert(r.trace.acceptedPass === 2 && r.trace.passes[0].errorCodes.indexOf("MISSING_KEY") !== -1, JSON.stringify(r.trace.passes[0].errorCodes)); });
  await T("T-EF03B-18", "enum invalide (disposition) : ENUM_DISPOSITION, reprise gelee inchangee", () => enforcerPath("enum", { "DIM-03": { disposition: "maybe" } }, ["ENUM_DISPOSITION"]));

  await T("T-EF03B-19", "sortie de 8192 jetons evitee quand la structure est complete avant ce volume : max_tokens = 12288 transmis au transport (llm.js honore meta.maxTokens, defaut 8192 conserve), budget de sortie dans le prompt ; une reponse complete de ~9000 jetons est acceptee sans completion", async () => {
    const big = validJson(8, { "DIM-01": { rationale: "R".repeat(12000) }, "DIM-02": { rationale: "R".repeat(12000) }, "DIM-03": { rationale: "R".repeat(12000) } }); assert(big.length > 36000, "~9 k jetons"); const llm = fakeLlm(() => ({ text: big, usage: { input_tokens: 49000, output_tokens: 9100 } })); const { r, adapter } = await run(llm, mkTwin(8));
    assert(r.review.reviewStatus === "complete" && llm.calls.length === 1 && llm.calls[0].meta.maxTokens === 12288 && adapter.stats().truncations === 0, JSON.stringify(adapter.stats()));
    const src = fs.readFileSync(path.join(ROOT, "lib", "llm.js"), "utf8"); assert(/Number\(meta && meta\.maxTokens\) > 0 \? Math\.min\(Math\.round\(Number\(meta\.maxTokens\)\), 65536\) : 8192/.test(src) && P.CONFIG.llm.reviewMaxTokens === 12288, "transport : meta.maxTokens, defaut 8192, config 12288"); });

  await T("T-EF03B-20", "aucun affaiblissement du validateur scientifique : le validateur et le parseur utilises sont ceux du lot gele (fichiers intacts, sceau verifie) ; un candidat du registre ALTERE (citation inventee) est refuse par le lot gele => appel reel ; l'adaptateur n'accepte jamais lui-meme", async () => {
    const fr = P.verifyFrozenLots(); assert(fr["MONO-11"].verified === true && fr["MONO-01"].verified === true, "lots geles intacts"); const src = fs.readFileSync(path.join(ROOT, "lib", "ef03b-resilience.js"), "utf8"); assert(/require\(path\.join\(P\.MONO11, "core", "review-enforcer\.js"\)\)/.test(src) && !/reviewStatus\s*[:=]\s*"complete"/.test(src), "validateur gele, aucune acceptation locale");
    const dir = tmp(); const tw = mkTwin(9); const reg = EF3.createReviewRegistry({ runDir: dir }); const tampered = validJson(9, { "DIM-01": { targetEvidenceRefs: ["citation inventee absente du document"] } }); reg.put({ basePromptSha256: sha(F.M01.RR.buildReviewPrompt(tw, mkDoc(), schema) + RE.enforcementPreamble(schema)), twinId: tw.twinId, targetId: "target-01", runId: "t", candidateSha256: sha(tampered), candidate: tampered, validationContract: "MONO-11-v2", sourceSealHash: "s".repeat(64), source: "TEST" });
    const llm = fakeLlm(() => ({ text: validJson(9) })); const adapter = EF3.createReviewAdapter({ llm, runDir: dir, runId: "t", attemptId: 2, sealHash: "s".repeat(64) }); const r = await RE.runEnforcedReview({ frozen: F, twin: tw, targetDoc: mkDoc(), reviewSchema: schema, llmCall: adapter.llmCall, maxPasses: 3, onValidation: adapter.onValidation }); assert(r.review.reviewStatus === "complete" && llm.calls.length === 1 && adapter.stats().registryReuses === 0, "entree alteree ignoree => appel reel"); });

  await T("T-EF03B-21", "transport v1.0.9 inchange : lib/llm-stream.js et lib/live-status.js (hors compteurs EF-03B) / proxy v0.8 byte-identiques a v1.0.9 ; llm.js conserve le streaming (stream:true, readSseResponse, gardes)", () => {
    const prev = path.join(P.ROOT, "..", "MONOLITH-v1.0.9"); assert(fs.existsSync(prev), "v1.0.9 presente"); ["lib/llm-stream.js", "worker/evidenceforge-llm-proxy-v0.8/src/worker.js", "lib/provider-diagnostic.js"].forEach((f) => assert(fs.readFileSync(path.join(prev, f)).equals(fs.readFileSync(path.join(ROOT, f))), f + " identique"));
    const l = fs.readFileSync(path.join(ROOT, "lib", "llm.js"), "utf8"); assert(/wantStream \? \{ stream: true \} : \{\}/.test(l) && /LS\.readSseResponse\(res, \{ inactivityMs: SCFG\.inactivityMs, maxTotalMs: SCFG\.maxTotalMs/.test(l) && /CODE_INTERRUPTED/.test(l), "streaming conserve"); });
  await T("T-EF03B-22", "Panel Sufficiency inchange (sha256 fd05e26b…) ; economic-panel, budget-guard, run-stop byte-identiques a v1.0.9", () => { assert(sha(fs.readFileSync(path.join(ROOT, "lib", "panel-sufficiency.js"))) === "fd05e26b708c4d4cdc59595838145669d05a267393629dbd922827c289bf7a3e"); const prev = path.join(P.ROOT, "..", "MONOLITH-v1.0.9"); ["lib/economic-panel.js", "lib/budget-guard.js", "lib/run-stop.js", "lib/panel-sufficiency.js"].forEach((f) => assert(fs.readFileSync(path.join(prev, f)).equals(fs.readFileSync(path.join(ROOT, f))), f)); });
  await T("T-EF03B-23", "MISSION_DOSSIER reste 1 cible (9 documents => 1 cible, 1 revue par jumeau)", () => { const docs = Array.from({ length: 9 }, (_, i) => ({ documentId: "doc-" + i, title: "Doc " + i, content: "Contenu " + i + ". ".repeat(200), hashSha256: sha("d" + i) })); const rt = EP.buildReviewTargets({ documents: docs, mode: "MISSION_DOSSIER" }); assert(rt.targets.length === 1 && rt.reviewsPerTwin === 1 && rt.sourceDocumentCount === 9); });
  await T("T-EF03B-24", "anti-hardcoding = 0 (lib, tools, test, config, index.html, server.js)", () => { const r = require("../tools/anti-hardcoding-scan.js"); const hits = r.scan(r.SCAN.flatMap(r.listFiles), r.caseTokens()); assert(hits.length === 0, JSON.stringify(hits)); });
  if (h.seedRunAtProfessionals) await T("T-EF03B-26", "REPLAY CIBLE (pipeline) : run COMPLETED => POST replay-reviews => STOPPED / REVIEWS_REPLAY_REQUESTED (reprenable), etapes TWINS_REVIEWS/QUALIFICATION/REPORT remises a PENDING, checkpoint aval ARCHIVE (jamais detruit), checkpoint professionnel intact ; reprise => l'aval seul est rejoue (runPanel jamais rappele), COMPLETED ; refus si panel absent ou run en cours", async () => {
    const { seedRunAtProfessionals, patchSP, patchSeal, fakeProCheckpoint, fakeDownCheckpoint, withFakeProviderOK, RS, PL } = h;
    await withFakeProviderOK(async () => { const r = seedRunAtProfessionals("Examinez cette demande de test de replay des revues"); const un = patchSeal(); let panelCalls = 0, downCalls = 0;
      const restore = patchSP({ runPanel: async (input) => { panelCalls++; return { checkpoint: fakeProCheckpoint(input.runId, input.attemptRunId), stats: { evaluated: 1 }, panelCounts: {} }; }, runDownstreamFromCheckpoint: async (input) => { downCalls++; return { checkpoint: fakeDownCheckpoint(input.runId, input.attemptRunId), summary: { twins: 1, blocked: 0, reviews: {}, qualification: "QUALIFIED_WITH_RESERVATIONS" } }; } });
      try { const out = await PL.advance(r.runId); assert(out.status === "COMPLETED" && panelCalls === 1 && downCalls === 1, JSON.stringify(out.status)); const cpHash = r.loadCheckpoint("checkpoint-professionals.json").contentHash; assert(r.loadJson("ef03b-resilience.json").schema === "EvidenceForge.EF03BResilienceSummary", "resume EF-03B persiste");
        let e = null; try { PL.replayReviews("efm-inexistant"); } catch (x) { e = x; } assert(e && e.code === "RUN_NOT_FOUND");
        const rp = PL.replayReviews(r.runId, { requestedBy: "Testeur" }); assert(rp.ok && rp.state.status === "STOPPED" && rp.state.error.code === "REVIEWS_REPLAY_REQUESTED" && rp.state.resumable === true && rp.state.stage === "TWINS_REVIEWS", JSON.stringify(rp.state.error));
        const st = r.read(); assert(st.stages.TWINS_REVIEWS.status === "PENDING" && st.stages.QUALIFICATION.status === "PENDING" && st.stages.REPORT.status === "PENDING" && st.stages.PROFESSIONALS.status === "DONE" && !st.checkpoints.downstream && st.checkpoints.professionals && st.replay.requestedBy === "Testeur", JSON.stringify(st.stages));
        assert(!fs.existsSync(path.join(r.dir, "checkpoint-downstream.json")) && fs.existsSync(path.join(r.dir, "replay-archive", rp.archiveTag, "checkpoint-downstream.archived.json")) && fs.existsSync(path.join(r.dir, "replay-archive", rp.archiveTag, "report.json")) && r.loadCheckpoint("checkpoint-professionals.json").contentHash === cpHash, "archive + checkpoint professionnel intact");
        assert(PL.RESUMABLE.indexOf("REVIEWS_REPLAY_REQUESTED") !== -1 && r.events().some((e2) => e2.event === "reviews_replay_requested"), "reprenable + journal");
        const out2 = await PL.advance(r.runId); assert(out2.status === "COMPLETED" && panelCalls === 1 && downCalls === 2 && out2.stages.TWINS_REVIEWS.status === "DONE" && r.loadJson("ef03b-resilience.json").attemptId === 2 && out2.attempts === 2, JSON.stringify([out2.status, panelCalls, downCalls]));
        let e3 = null; try { PL.replayReviews(r.runId); PL.replayReviews(r.runId); } catch (x) { e3 = x; } assert(e3 === null || e3.code === "ALREADY_RUNNING", "replay repetable hors run en cours"); } finally { restore(); un(); } });
    const r2 = h.seedRunAtProfessionals("Examinez cette demande sans panel termine"); let e4 = null; try { PL.replayReviews(r2.runId); } catch (x) { e4 = x; } assert(e4 && e4.code === "REPLAY_REQUIRES_PROFESSIONALS_CHECKPOINT", "refus sans panel : " + (e4 && e4.code)); });

  await T("T-EF03B-25", "secret scan = 0 ; aucune cle, aucun prompt, aucune reponse complete dans la trace EF-03B ni dans le registre (identifiants, compteurs, hachages, candidat JSON valide seulement)", async () => { const r = require("../tools/secret-scan.js").scan(); assert(r.ok === true, JSON.stringify(r.hits)); const llm = fakeLlm(() => ({ text: validJson(1) })); const { dir } = await run(llm, mkTwin(1)); const tr = fs.readFileSync(path.join(dir, EF3.TRACE_FILE), "utf8"); assert(!/CONTRAT DE BUDGET|DOCUMENT CIBLE|Introduction generale/.test(tr) && /"candidateSha256"/.test(tr), "trace sans prompt ni reponse"); });
  await require("./test-ef03b-lineage.js")(h);   /* v1.0.11 — LITERALIZATION LINEAGE PRESERVATION */
};
