(() => {
  "use strict";
  const validPoint=(p)=>Array.isArray(p)&&Number.isFinite(Number(p[0]))&&Number.isFinite(Number(p[1]));
  const sanitizeCoords=(coords=[])=> (Array.isArray(coords)?coords:[]).filter(validPoint);
  function haversine(a,b){if(!validPoint(a)||!validPoint(b))return 0;const r=Math.PI/180,lat1=Number(a[1])*r,lat2=Number(b[1])*r,dLat=(Number(b[1])-Number(a[1]))*r,dLon=(Number(b[0])-Number(a[0]))*r,h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
  function cumulativeDistances(coords=[]){coords=sanitizeCoords(coords);const out=[0];for(let i=1;i<coords.length;i++)out.push(out.at(-1)+haversine(coords[i-1],coords[i]));return out;}
  function minutes(distance,total,walking){if(!Number.isFinite(Number(distance))||!Number.isFinite(Number(total))||!Number.isFinite(Number(walking))||Number(total)<=0||Number(walking)<=0)return null;return Number(distance)/Number(total)*Number(walking);}
  function buildBacktrackFallbacks(coords=[],walkingMinutes=0){coords=sanitizeCoords(coords);if(coords.length<3)return[];const cum=cumulativeDistances(coords),total=cum.at(-1)||0;return[.25,.5,.75].map((fraction,index)=>{let checkpointIndex=cum.findIndex(v=>v>=total*fraction);if(checkpointIndex<1)checkpointIndex=1;const outboundMeters=cum[checkpointIndex],point=coords[checkpointIndex],fallbackMeters=outboundMeters*2;return{id:`backtrack-${index+1}`,kind:'backtrack',label:`Retour sur ses pas à ${Math.round(fraction*100)} %`,checkpointIndex,checkpoint:{lon:Number(point[0]),lat:Number(point[1])},outboundMeters,totalMeters:fallbackMeters,totalMinutes:minutes(fallbackMeters,total,walkingMinutes),geometry:[...coords.slice(0,checkpointIndex+1),...coords.slice(0,checkpointIndex).reverse()],evidence:'Aller-retour construit uniquement avec la portion de trace déjà parcourue.'};});}
  const key=(p)=>`${Number(p[0]).toFixed(5)}:${Number(p[1]).toFixed(5)}`;
  function buildNodeShortcuts(coords=[],walkingMinutes=0){coords=sanitizeCoords(coords);if(coords.length<8)return[];const cum=cumulativeDistances(coords),total=cum.at(-1)||0,first=new Map(),items=[];coords.forEach((point,index)=>{const k=key(point),start=first.get(k);if(start===undefined){first.set(k,index);return;}if(index-start<3)return;const skipped=cum[index]-cum[start],connection=haversine(coords[start],coords[index]);if(skipped<250||connection>2)return;const geometry=[...coords.slice(0,start+1),...coords.slice(index)],newTotal=cumulativeDistances(geometry).at(-1)||0,saved=total-newTotal;if(saved<=0)return;items.push({id:`shortcut-${start}-${index}`,kind:'existing-node',label:'Raccourci par point de passage commun',savedMeters:saved,savedMinutes:minutes(saved,total,walkingMinutes),totalMeters:newTotal,totalMinutes:minutes(newTotal,total,walkingMinutes),geometry,evidence:'Deux passages utilisent le même point géométrique ; aucun chemin extérieur n’est ajouté.'});});return items.sort((a,b)=>b.savedMeters-a.savedMeters).slice(0,3);}
  function analyzeFallbacks({coords=[],walkingMinutes=0,shortcutsRequested=false}={}){if(!shortcutsRequested)return{requested:false,status:'respected',shortcuts:[],fallbacks:[],evidence:'Aucun raccourci ou repli demandé.'};coords=sanitizeCoords(coords);if(coords.length<3)return{requested:true,status:'unknown',shortcuts:[],fallbacks:[],evidence:'Géométrie insuffisante pour calculer un repli réel.'};const shortcuts=buildNodeShortcuts(coords,walkingMinutes),fallbacks=buildBacktrackFallbacks(coords,walkingMinutes);return{requested:true,status:fallbacks.length?'respected':'unknown',shortcuts,fallbacks,evidence:shortcuts.length?`${shortcuts.length} raccourci réel et ${fallbacks.length} replis calculés.`:`${fallbacks.length} replis sur ses pas calculés ; aucun raccourci traversant n’est prouvé.`};}
  function safeAnalyzeFallbacks(input={}){try{return analyzeFallbacks(input)}catch(error){return{requested:Boolean(input.shortcutsRequested),status:'unknown',shortcuts:[],fallbacks:[],evidence:`Le calcul des replis a échoué sans interrompre le parcours : ${error.message}`,error:error.message};}}
  function applyFallbackAnalysis(route,analysis){const next={...route};next.shortcuts=analysis.shortcuts||[];next.fallbacks=analysis.fallbacks||[];next.fallbackAnalysis=analysis;next.checks=[...(Array.isArray(next.checks)?next.checks:[]),{constraint:'Raccourcis et replis réels',status:analysis.status,evidence:analysis.evidence,severity:analysis.requested?'hard':'advisory'}];if(analysis.requested&&analysis.status==='unknown'&&next.proposalStatus==='compatible'){next.proposalStatus='verify';next.canNavigate=false;next.unknowns=[...new Set([...(next.unknowns||[]),'Raccourci ou repli à vérifier'])];}return next;}
  globalThis.JMMJSFallbackCore=Object.freeze({sanitizeCoords,cumulativeDistances,buildBacktrackFallbacks,buildNodeShortcuts,analyzeFallbacks,safeAnalyzeFallbacks,applyFallbackAnalysis});
})();