#!/usr/bin/env node
"use strict";
/**
 * MONOLITH v1.0.7 — tools/economic-replay.js : REPLAY LOCAL, SANS APPEL REEL, d'un run existant sous la politique SUFFICIENCY_FIRST
 * + REVIEW FANOUT CONTROL. Lit uniquement les artefacts du run (selection, checkpoint professionnel, panel, suffisance, ledger, cibles)
 * et rejoue le controleur economique avec les observations REELLES deja produites (gate gele par candidat, dimensions soutenues, oeuvres).
 * Un candidat jamais evalue dans le run reel n'a aucune observation : le replay le marque NOT_OBSERVED (il aurait fallu un appel reel)
 * et ne l'invente pas. Sortie : <out>.json + <out>.md — AVANT (mesure) vs APRES (rejoue / projete). ESTIMATE — NOT GUARANTEE.
 * Usage : node tools/economic-replay.js <runDir> [--out <prefix>] [--budget <usd>] [--dossier-max-chars <n>]
 */
const fs = require("fs"), path = require("path");
const ROOT = path.resolve(__dirname, "..");
const args = process.argv.slice(2); const runDir = args[0]; if (!runDir || !fs.existsSync(path.join(runDir, "state.json"))) { console.error("usage: node tools/economic-replay.js <runDir> [--out prefix] [--budget usd]"); process.exit(2); }
const opt = (k, d) => { const i = args.indexOf(k); return i !== -1 && args[i + 1] != null ? args[i + 1] : d; };
const OUT = opt("--out", path.join(ROOT, "JMMJS-PANEL-COST-REPLAY-v1")); const BUDGET_OVERRIDE = opt("--budget", null);
process.env.EVIDENCEFORGE_RUNS_ROOT = process.env.EVIDENCEFORGE_RUNS_ROOT || path.dirname(runDir);
const P = require("../lib/paths.js"); const PSUF = require("../lib/panel-sufficiency.js"); const EP = require("../lib/economic-panel.js"); const CL = require("../lib/cost-ledger.js");
const J = (f) => { const p = path.join(runDir, f); return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, "utf8")) : null; };
const round2 = (v) => Math.round(v * 100) / 100, round4 = (v) => Math.round(v * 1e4) / 1e4; const mean = (xs) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null);

const state = J("state.json"), selection = J("professionals-selection.json"), cp = J("checkpoint-professionals.json"), suff = J("professionals-sufficiency.json"), panel = J("panel.json") || (cp && cp.panel), disc = J("professionals-discovery.json"), pc = J("plan-confirmation.json"), budget = J("budget.json");
if (!selection || !cp || !suff) { console.error("artefacts manquants (selection / checkpoint / suffisance)"); process.exit(2); }
const entries = CL.readEntries(runDir); const totals = CL.readTotals(runDir); const real = entries.filter((e) => CL.REAL_KINDS.indexOf(e.kind) !== -1 && e.cost);
const costBy = new Map(); real.forEach((e) => { if (e.candidateRef && e.stage === "PROFESSIONALS") costBy.set(e.candidateRef, (costBy.get(e.candidateRef) || 0) + e.cost.totalUsd); });   /* cout d'EVALUATION seulement (la couverture aval porte aussi candidateRef) */
const purposeStats = (re) => { const xs = real.filter((e) => re.test(e.purpose || "")).map((e) => e.cost.totalUsd); return { n: xs.length, usd: round4(xs.reduce((a, b) => a + b, 0)), mean: xs.length ? round4(mean(xs)) : null }; };
const oracle = purposeStats(/^EF-02D2/), coverage = purposeStats(/^EF-02D3/), reviews = purposeStats(/^EF-03B review$/), reviewRetry = purposeStats(/^EF-03B review informed-retry/);
const evaluatedIds = new Set(suff.history.filter((h) => h.rank != null).map((h) => h.candidateRef)); const approvedIds = new Set((panel && panel.approvedCandidateIds) || []);
const primaryDim = new Map(); ((disc && disc.discovery && disc.discovery.candidates) || []).forEach((c) => { if (c.candidateRef) primaryDim.set(c.candidateRef, c.dimensionRef || (Array.isArray(c.disciplines) && c.disciplines[0]) || null); });
const relOf = (id) => { const a = cp.evidence && cp.evidence["mono11:relevance:" + id]; return a ? (a.artifact || a) : null; };
const seedsOf = new Map(); ((disc && disc.discovery && disc.discovery.candidates) || []).forEach((c) => { if (c.candidateRef) seedsOf.set(c.candidateRef, (c.seedReferences || []).map((r) => r && r.providerWorkId).filter((x) => typeof x === "string" && x)); });
const dims = cp.dimensionSet.dimensions.map((d) => d.id); const order = selection.selectionOrder || selection.selectedIds;
const cands = order.map((id) => ({ candidateRef: id, dimension: primaryDim.get(id), seedWorkRefs: seedsOf.get(id) || [] }));
const esCfg = Object.assign({}, (P.CONFIG.professionals && P.CONFIG.professionals.earlyStop) || {}); delete esCfg.$comment;
const tracker = PSUF.createSufficiencyTracker({ dimensions: dims, candidates: cands, policy: esCfg });
const ecoCfg = EP.normalizeEconomicPolicy(P.CONFIG.professionals && P.CONFIG.professionals.economic); const plan = EP.planBatches({ orderedCandidates: cands, dimensions: dims, policy: ecoCfg });
const upstreamUsd = totals ? Object.keys(totals.byStage).filter((s) => ["PREFLIGHT", "MISSION", "DISCIPLINES", "PLAN", "RETRIEVAL", "CORPUS"].indexOf(s) !== -1).reduce((n, s) => n + totals.byStage[s].totalUsd, 0) : 0;
let spent = upstreamUsd; const samples = []; const events = []; const bud = BUDGET_OVERRIDE != null ? { mode: "LIMITED", costBudgetUsd: Number(BUDGET_OVERRIDE) } : (budget ? { mode: budget.mode, costBudgetUsd: budget.costBudgetUsd } : null);
const ctl = EP.createEconomicController({ tracker, plan, policy: ecoCfg, budget: bud, spentUsd: () => spent, perCandidateUsd: () => samples, log: (e) => events.push(e) });
let replayedEvaluations = 0, notObserved = 0, skipped = 0, deferred = 0; const perCandidateDefault = oracle.mean || 0; const stoppedAtNotObserved = [];
for (const c of cands) {
  const d = ctl.beforeEvaluate(c.candidateRef);
  if (!d.evaluate) { if (d.deferred) deferred++; else { tracker.skip(c.candidateRef, d.reason); skipped++; } continue; }
  if (!evaluatedIds.has(c.candidateRef)) { notObserved++; stoppedAtNotObserved.push(c.candidateRef); tracker.skip(c.candidateRef, "NOT_OBSERVED_IN_REAL_RUN"); continue; }   /* aucune observation reelle : jamais inventee */
  replayedEvaluations++; const u = costBy.has(c.candidateRef) ? costBy.get(c.candidateRef) : perCandidateDefault; spent += u; samples.push(u);
  const rel = relOf(c.candidateRef); tracker.observe({ candidateRef: c.candidateRef, corpus: rel ? "SUFFICIENT" : "INSUFFICIENT", relevanceClass: rel ? rel.relevanceClass : "UNKNOWN", approved: approvedIds.has(c.candidateRef), supportedDimensions: rel ? rel.supportingDimensions : [], partialDimensions: rel ? rel.partialDimensions : [], supportingDimensionsDetail: rel ? rel.supportingDimensions : [], supportingWorks: rel ? rel.supportingWorks : [] });
}
const rec = ctl.record(); const dec = tracker.decision();
/* ——— aval : cibles (dossier) et projection ——— */
const docs = (pc && pc.executionMission && pc.executionMission.targetDocuments) || []; const rt = EP.buildReviewTargets({ documents: docs, mode: ecoCfg.reviewTargetMode, dossierMaxChars: Number(opt("--dossier-max-chars", ecoCfg.dossierMaxChars)) });
const twinsBuiltReal = (() => { const ev = fs.existsSync(path.join(runDir, "events.jsonl")) ? fs.readFileSync(path.join(runDir, "events.jsonl"), "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((e) => e.event === "twins_built").pop() : null; return ev ? ev.built : null; })();
const approvedAfter = dec.approved; const twinsAfter = twinsBuiltReal != null ? Math.min(twinsBuiltReal, approvedAfter) : approvedAfter;
/* cout par revue avec cible = dossier : cout mesure par revue (cible ~5 000 car.) + surcout d'entree du dossier (tarif du modele du run, mesure dans le ledger : usd / token d'entree) */
const inTok = real.reduce((n, e) => n + ((e.usage && (e.usage.input || e.usage.input_tokens)) || 0), 0), inUsd = real.reduce((n, e) => n + ((e.cost && e.cost.inputUsd) || 0), 0); const usdPerInputToken = inTok ? inUsd / inTok : null;
const dossierTokens = Math.round(rt.characters / 4); const extraPerReview = usdPerInputToken != null ? usdPerInputToken * dossierTokens : 0;
const perReviewMeasured = reviews.n ? (reviews.usd + reviewRetry.usd) / reviews.n : null; const perReviewDossier = perReviewMeasured != null ? perReviewMeasured + extraPerReview : null;
const perCoverage = coverage.n ? coverage.usd / Math.max(1, new Set(real.filter((e) => /^EF-02D3/.test(e.purpose || "")).map((e) => e.candidateRef || e.twinId)).size) : null;
const proj = EP.projectDownstream({ approved: approvedAfter, expectedTwins: twinsAfter, targets: rt.targets.length, dimensions: dims.length, spentUsd: spent, initialPanelSize: rec.initialPanelSize, perReviewUsd: perReviewDossier != null ? [perReviewDossier, perReviewDossier, perReviewDossier] : null, perCoverageUsd: perCoverage != null ? [perCoverage, perCoverage, perCoverage] : null, thresholdUsd: ecoCfg.economicReviewThresholdUsd, outlierUsd: ecoCfg.economicOutlierUsd, budget: bud });
const before = { candidates: disc ? disc.candidates : null, identified: selection.poolCount, selected: selection.selectedCount, cap: selection.cap, evaluated: suff.evaluated, approved: suff.approved, twinsBuilt: twinsBuiltReal, targets: docs.length, reviewsExpected: twinsBuiltReal != null ? twinsBuiltReal * docs.length : null, aggregationGroups: docs.length * dims.length,
  spentUsd: totals ? round2(totals.totalUsd) : null, projectedUsd: (() => { const c = J("run-stop-state.json"); const per = perReviewMeasured || 0; return twinsBuiltReal != null && totals ? round2(totals.totalUsd + (twinsBuiltReal * docs.length - reviews.n) * per) : null; })(), panel: suff.panel, sufficiency: suff.state };
const after = { policy: ecoCfg.policy, initialPanelSize: rec.initialPanelSize, batchesClosed: rec.batches.length, evaluated: rec.evaluated, replayedEvaluations, skippedBySufficiency: skipped, deferredByBudget: deferred, notObserved, approved: dec.approved, scientificPanelState: dec.panel, economicState: rec.economicState, stopped: rec.stopped, diminishingReturns: rec.diminishingReturns, averageMarginalGainPerBatch: rec.averageMarginalGainPerBatch, duplicateReviewRate: rec.duplicateReviewRate,
  reviewTargetMode: rt.mode, targets: rt.targets.length, dossierCharacters: rt.characters, twins: twinsAfter, reviewDocuments: proj.EXPECTED_REVIEWS, reviewItems: proj.EXPECTED_REVIEWS * dims.length, aggregationGroups: proj.EXPECTED_AGGREGATION_GROUPS, projection: { status: proj.status, low: proj.LOW_COST, central: proj.CENTRAL_COST, high: proj.HIGH_COST, spentAtProjection: round2(spent), parts: proj.parts, outlier: proj.ECONOMIC_OUTLIER_WARNING, reviewRequired: proj.ECONOMIC_REVIEW_REQUIRED, budgetExceeded: proj.budgetExceeded }, unitCosts: { oraclePerCandidate: oracle.mean, coveragePerAdmitted: perCoverage != null ? round4(perCoverage) : null, reviewMeasured: perReviewMeasured != null ? round4(perReviewMeasured) : null, reviewWithDossier: perReviewDossier != null ? round4(perReviewDossier) : null, usdPerInputToken, dossierTokens } };
const out = { schema: "EvidenceForge.EconomicReplay", schemaVersion: "MONOLITH-v1.0.7", label: "ESTIMATE — NOT GUARANTEE (replay local, aucun appel reel)", runId: state.runId, replayedAt: new Date().toISOString(), before, after, batches: rec.batches.map((b) => ({ index: b.index, kind: b.kind, evaluated: b.contribution.evaluated, newApproved: b.contribution.newApproved, newDisciplinesCovered: b.contribution.newDisciplinesCovered, newIndependentPositions: b.contribution.newIndependentPositions, nearDuplicatePositions: b.contribution.nearDuplicatePositions, costUsd: b.costUsd, panelAfter: b.scientificPanelStateAfter, gapsAfter: b.gapsAfter })),
  limits: ["les observations rejouees sont celles du run reel (aucune nouvelle evaluation) ; un candidat jamais evalue reste NOT_OBSERVED", "cout par revue avec dossier = cout mesure par revue + surcout d'entree du dossier au tarif mesure du run (jamais un tarif invente)", "le nombre de jumeaux apres = min(jumeaux reellement construits, approuves rejoues)", "l'agregation est projetee au cout unitaire d'une revue (proxy)"] };
fs.writeFileSync(OUT + ".json", JSON.stringify(out, null, 2) + "\n");
const md = ["# JMMJS PANEL COST REPLAY v1 — run `" + state.runId + "` (replay local, aucun appel réel)", "", "**Politique rejouée :** " + ecoCfg.policy + " (v1.0.7) · cibles de revue : " + rt.mode + " · budget : " + (bud ? bud.mode + " " + bud.costBudgetUsd + " USD" : "aucun") + " · ESTIMATE — NOT GUARANTEE", "",
  "| Grandeur | AVANT (mesuré, v1.0.5) | APRÈS (rejoué / projeté, v1.0.7) |", "|---|---|---|",
  "| candidats découverts / identifiés | " + before.candidates + " / " + before.identified + " | inchangé |", "| retenus (plafond " + before.cap + ") | " + before.selected + " | " + before.selected + " retenus = garde ; panel initial **" + after.initialPanelSize + "**, lots de " + ecoCfg.expansionBatch + " |",
  "| évalués (oracle payant) | " + before.evaluated + " | **" + after.evaluated + "** (" + after.batchesClosed + " lots clos ; " + after.skippedBySufficiency + " non évalués par suffisance, " + after.deferredByBudget + " différés budget, " + after.notObserved + " non observables) |",
  "| approuvés | " + before.approved + " | " + after.approved + " |", "| état scientifique du panel | " + before.panel + " | " + after.scientificPanelState + " (" + after.economicState + ") |",
  "| jumeaux | " + before.twinsBuilt + " | " + after.twins + " |", "| cibles de revue | " + before.targets + " (1 par document) | **" + after.targets + "** (" + rt.mode + ", " + rt.characters + " caractères) |",
  "| **revues complètes** | **" + before.reviewsExpected + "** | **" + after.reviewDocuments + "** |", "| items de grille (revues × angles) | " + (before.reviewsExpected != null ? before.reviewsExpected * dims.length : "—") + " | " + after.reviewItems + " |", "| groupes d'agrégation (appels) | " + before.aggregationGroups + " | " + after.aggregationGroups + " |",
  "| coût déjà engagé / projeté | " + before.spentUsd + " USD engagés ; ≈ " + before.projectedUsd + " USD projetés | projection " + (after.projection.central != null ? after.projection.central + " USD central (" + after.projection.low + "–" + after.projection.high + ")" : "≥ " + after.projection.low + " USD (partielle)") + " |",
  "| ECONOMIC_OUTLIER_WARNING / gate | non disponible | " + (after.projection.outlier ? "OUI" : "non") + " / " + (after.projection.reviewRequired ? "confirmation humaine requise" : "non requise") + (after.projection.budgetExceeded ? " · dépasserait le budget " + bud.costBudgetUsd + " USD" : "") + " |",
  "| contribution marginale moyenne / lot | — | " + after.averageMarginalGainPerBatch + " (angles + positions indépendantes nouvelles) |", "| taux de quasi-doublons parmi les approuvés | — | " + (after.duplicateReviewRate != null ? Math.round(after.duplicateReviewRate * 100) + " %" : "—") + " |",
  "| rendements décroissants | — | " + (after.diminishingReturns.active ? "signal actif (" + after.diminishingReturns.consecutiveBatchesWithoutGain + " lots sans gain ; angles à rendement nul : " + after.diminishingReturns.zeroYieldDimensions.join(", ") + ")" : "non") + " |", "",
  "## Lots rejoués", "", "| lot | type | évalués | +approuvés | +angles | +positions indép. | quasi-doublons | coût USD | panel après | gaps après |", "|---|---|---|---|---|---|---|---|---|---|"]
  .concat(out.batches.map((b) => "| " + b.index + " | " + b.kind + " | " + b.evaluated + " | " + b.newApproved + " | " + b.newDisciplinesCovered + " | " + b.newIndependentPositions + " | " + b.nearDuplicatePositions + " | " + b.costUsd + " | " + b.panelAfter + " | " + b.gapsAfter.join(", ") + " |"))
  .concat(["", "## Coûts unitaires mesurés (ledger du run)", "", "- oracle EF-02D2 : " + oracle.n + " appels, " + oracle.usd + " USD, " + oracle.mean + " USD/appel", "- couverture EF-02D3 : " + coverage.n + " appels, " + coverage.usd + " USD, ≈ " + (perCoverage != null ? round4(perCoverage) : "—") + " USD par admis", "- revue EF-03B : " + reviews.n + " revues (" + reviewRetry.n + " reprises), ≈ " + (perReviewMeasured != null ? round4(perReviewMeasured) : "—") + " USD par revue (cible ≈ 5 000 car.) ; avec le dossier (" + dossierTokens + " jetons d'entrée estimés) ≈ " + (perReviewDossier != null ? round4(perReviewDossier) : "—") + " USD", "", "## Limites", ""].concat(out.limits.map((l) => "- " + l)));
fs.writeFileSync(OUT + ".md", md.join("\n") + "\n");
console.log(JSON.stringify({ before: { evaluated: before.evaluated, approved: before.approved, reviews: before.reviewsExpected, projected: before.projectedUsd }, after: { initialPanel: after.initialPanelSize, batches: after.batchesClosed, evaluated: after.evaluated, approved: after.approved, panel: after.scientificPanelState, reviews: after.reviewDocuments, items: after.reviewItems, projected: after.projection.central, low: after.projection.low, high: after.projection.high, outlier: after.projection.outlier, gate: after.projection.reviewRequired, avgGain: after.averageMarginalGainPerBatch, dupRate: after.duplicateReviewRate }, out: OUT + ".json" }, null, 1));
